import os

import re

from camel.app.error.toolexecutionerror import ToolExecutionError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.tools.tool import Tool


class Prokka(Tool):
    """
    Prokka is a software tool for the rapid annotation of prokaryotic genomes.
    """

    OUTPUT_KEYS = {
        'gff': 'GFF',
        'gbk': 'GENBANK',
        'faa': 'FASTA_PROT',
        'txt': 'TXT',
    }

    def __init__(self, camel):
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super(Prokka, self).__init__('Prokka', '1.11', camel)

    def _execute_tool(self):
        """
        Executes this tool.
        :return: None
        """
        self.__build_command()
        self._execute_command()
        self.__set_output()
        self._add_informs()

    def _check_input(self):
        """
        Checks the tool input.
        :return: None
        """
        if 'FASTA' not in self._tool_inputs:
            raise ValueError("No FASTA input found")
        if len(self._tool_inputs['FASTA']) != 1:
            raise ValueError("Only one FASTA file can be annotated at a time.")
        super(Prokka, self)._check_input()

    def _check_command_output(self):
        """
        Checks the command output to see if the program ran correctly.
        :return: None
        """
        if 'Thank you, come again.' not in self.stderr.splitlines()[-1]:
            raise ToolExecutionError("Error executing Prokka: {}".format(self.stderr))

    def __build_command(self):
        """
        Build the command line call.
        :return: None
        """
        self._command.command = ' '.join([
            self._tool_command,
            ' '.join(self._build_options()),
            self._tool_inputs['FASTA'][0].path
        ])

    def __set_output(self):
        """
        Sets the tool output.
        :return: None
        """
        for line in self.stderr.splitlines():
            m = re.match('^\[.*] (PROKKA_\d+/.*\.(\w{3}))', line.strip())
            if m and m.group(2) in Prokka.OUTPUT_KEYS:
                self._tool_outputs[Prokka.OUTPUT_KEYS[m.group(2)]] = [
                    ToolIOFile(os.path.join(self._folder, m.group(1)))]

    def _add_informs(self):
        """
        Adds the informs.
        :return: None
        """
        if not os.path.isfile(self._tool_outputs['TXT'][0].path):
            raise IOError("No stats file generated by Prokka.")
        with open(self._tool_outputs['TXT'][0].path) as handle:
            for line in handle.readlines():
                key, value = line.split(':')
                self._informs[key] = value.strip()
