# config file for camel generalities.

galaxy:
  # directory to dump stderr/stdout or data in case of pipeline error while running from galaxy
  # as Galaxy removes data and truncates stderr and stdout.
  dump_dir: /scratch/temp/galaxy_dumps/

config_dump_dir: /data/logging/snakemake
error_log_dir: /data/logging/error_logs

# Parameters are retrieved from Yaml files with the same name as the tool (can be omitted from config).
tool_service: yaml

testing:
  testfiles_dir: /testdata/camel/

temp_dir: /scratch/temp