dependencies: [medaka/1.7.3, bcftools/1.15.1, samtools/1.15.1, htslib/1.13, minimap2/2.26]
parameters:
  batch_size: {default: false, mandatory: false, option: --batch_size, value: '100'}
  chunk_len: {default: false, mandatory: false, option: --chunk_len, value: '10000'}
  chunk_ovlp: {default: false, mandatory: false, option: --chunk_ovlp, value: '1000'}
  model: {default: true, mandatory: true, option: --model, value: 'r941_min_hac_g507'}
  output: {default: true, mandatory: true, option: '', p_index: 0, value: raw.hdf}
  regions: {default: false, mandatory: false, option: --regions, value: ''}
  threads: {default: true, mandatory: false, option: --threads, value: '4'}
tool_command: medaka consensus
