####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Sherry_2023-abritamr
#############
# abritAMR #
#############
abritamr:
  amrfinderplus:
    path: /db/amrfinder/v4/latest