import re
from typing import Iterable

import pandas as pd

from camel.app.components.kraken2.taxonnode import TaxonNode
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.loggers import logger
from camel.app.tools.tool import Tool


class KrakenReportParser(Tool):
    """
    Parses Kraken output reports for fastq files.
    """

    def __init__(self, camel) -> None:
        """
        Initializes this tool.
        :param camel: CAMEL instance
        """
        super().__init__('Kraken2 report parser', '0.1', camel)

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        # Check parameters
        allowed_species = (
            self._parameters['allowed_species'].value.split(',')) if 'allowed_species' in self._parameters else []
        if self._parameters['level_of_depth'].value not in ['S', 'G']:
            logger.error("Please select either 'G' or 'S' for the level_of_depth parameter.")

        # Initialize informs
        self._informs['contaminants_warn'] = []
        self._informs['contaminants_fail'] = []
        self._informs['allowed'] = []

        # Parse the TSV file generated by Kraken 2
        data_report = pd.read_table(
            self._tool_inputs['TSV'][0].path, names=['perc', 'nb_all', 'nb_direct', 'rank', 'tax_id', 'name'])

        if 'normalize_for_len' in self._parameters:
            data_report = self.normalize_percentages(data_report)
        self.parse_kraken2_report(data_report, allowed_species)

        # Check if the expected species was detected
        if 'expected' not in self._informs:
            logger.warning("No reads matching the expected species found!")
            self._informs['expected'] = (self._parameters['expected_species'].value, 0)

        # Sort by occurrence
        self._informs['contaminants_warn'].sort(key=lambda x: -x[1])
        self._informs['contaminants_fail'].sort(key=lambda x: -x[1])
        self._informs['allowed'].sort(key=lambda x: -x[1])

        # Store the parameters
        self._informs['level_of_depth'] = self._parameters['level_of_depth'].value
        self._informs['threshold_fail'] = self._parameters['threshold_fail'].value
        self._informs['threshold_warn'] = self._parameters['threshold_warn'].value
        self._informs['normalize_for_len'] = 'normalize_for_len' in self._parameters

        # Save the output (even if the percentages are not normalised, it will be exported with a header)
        basename = self._tool_inputs['TSV'][0].path.name.replace('.tsv', '-normalized.tsv')
        path_out = self.folder / basename
        data_report.to_csv(path_out, sep='\t', index=False)
        self._tool_outputs['TSV'] = [ToolIOFile(path_out)]

    def normalize_percentages(self, data_report: pd.DataFrame) -> pd.DataFrame:
        """
        Normalizes the percentages for read length.
        Note: this requires the full Kraken 2 file in the input
        """
        logger.info('Normalizing percentages for read lengths')
        if not 'TSV_full' in self._tool_inputs:
            raise InvalidInputSpecificationError("'TSV_full' input is required for normalization")
        data_raw = pd.read_table(
            self._tool_inputs['TSV_full'][0].path,
            names=['is_classified', 'seq_id', 'tax_id', 'seq_len'], usecols=range(4))

        # Calculate the correct percentage for each read and group by tax id
        seq_len_total = data_raw['seq_len'].sum()
        data_raw['perc_corrected'] = 100 * data_raw['seq_len'] / seq_len_total
        perc_by_taxid = {tax_id: data['perc_corrected'].sum() for tax_id, data in data_raw.groupby('tax_id')}

        # Create column with the correct percentage in the report output
        data_report['perc_corrected'] = data_report['tax_id'].apply(lambda x: perc_by_taxid.get(x))

        # Set the taxon level based on the indentation
        data_report['level'] = data_report['name'].apply(lambda x: len(re.search(r'^( *)', x).group(1)) // 2)

        # Parse the taxonomic tree from the Kraken 2 report data
        taxon_tree = self.parse_taxonomic_tree(data_report)

        # Calculate the total percentage for each entry
        perc_by_node = {}
        for node in TaxonNode.traverse_dfs(taxon_tree):
            perc_by_node[node.name] = node.total_perc()

        # Unclassified
        perc_by_node[0] = data_raw[data_raw['tax_id'] == 0]['perc_corrected'].sum()

        # Update the percentages
        data_report['perc_orig'] = data_report['perc']
        data_report['perc'] = data_report['tax_id'].apply(lambda x: perc_by_node[x])
        return data_report

    def parse_kraken2_report(self, data_report: pd.DataFrame, allowed_species: Iterable[str]) -> None:
        """
        Parses the Kraken 2 output report and stores the results in the informs.
        :param data_report: Parsed report data
        :param allowed_species: List of allowed species.
        :return: None
        """
        for row in data_report.to_dict('records'):
            if row['rank'] != self._parameters['level_of_depth'].value:
                continue
            if row['perc'] < float(self._parameters['threshold_warn'].value):
                continue
            species_name = row['name'].strip()
            if species_name == self._parameters['expected_species'].value:
                self._informs['expected'] = (species_name, row['perc'])
            elif species_name in allowed_species:
                self._informs['allowed'].append((species_name, row['perc']))
            elif species_name in self._parameters['expected_species'].value:
                self._informs['expected'] = (species_name, row['perc'])
            elif row['perc'] < float(self._parameters['threshold_fail'].value):
                self._informs['contaminants_warn'].append((species_name, row['perc'],))
            else:
                self._informs['contaminants_fail'].append((species_name, row['perc'],))

    def parse_taxonomic_tree(self, data_report: pd.DataFrame) -> TaxonNode:
        """
        Parses the taxonomic tree from the Kraken 2 report output.
        :param data_report: Data parsed from the report
        :return: Taxon node with the root node
        """
        root = TaxonNode(1, None)
        stack = [(root, -1)]
        for row in data_report.to_dict('records')[1:]:
            # Skip unclassified
            if row['tax_id'] == 0:
                continue
            percentage = row['perc_corrected'] if not pd.isna(row['perc_corrected']) else None
            new_node = TaxonNode(row['tax_id'], percentage=percentage)

            # Find the parent node by checking levels
            while stack and stack[-1][1] >= row['level']:
                stack.pop()

            # Add this node as a child of the parent node
            # noinspection PyUnresolvedReferences
            stack[-1][0].add_child(new_node)

            # Push the new node to the stack with its level
            stack.append((new_node, row['level']))
        return root

    def _check_input(self) -> None:
        """
        Checks the tool input.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("TSV input is required.")
        super()._check_input()
