from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from camel.app.io.tooliofile import ToolIOFile
from camel.app.snakemake import snakemakeutils
from camel.app.snakemake.snakepipelineutils import SnakePipelineUtils
from camel.resources.snakefile import polish_assembly_short


class ShortReadPolishingWrapper:
    """
    This class is used as a wrapper class around the Illumina short read polishing Snakemake workflow.
    """

    @dataclass
    class PolishingOutput:
        """
        Class to store the polishing output.
        """
        fasta_contigs: Path
        log_file: Optional[Path] = None

    def __init__(self, working_dir: Path) -> None:
        """
        Initializes the read trimming wrapper.
        :param working_dir: Working directory
        :return: None
        """
        self._working_dir = Path(working_dir)
        self._output = None

    def run_workflow(self, pe_reads: list[Path], reference: Path, threads: int = 8) -> None:
        """
        Runs the read polishing workflow.
        :param pe_reads: Path to the PE FASTQ reads io file
        :param reference: Path to the genome to polish io file
        :param threads: Number of threads to use
        :return: None
        """
        # Create config file
        config_data = {
            'working_dir': str(self._working_dir),
        }
        config_file = SnakePipelineUtils.generate_config_file(config_data, Path(self._working_dir, 'polishing'))

        # Dump the input files in an IO file
        io_pickle_in = Path(self._working_dir / 'fq_dict.io')
        io_pickle_in.parent.mkdir(exist_ok=True, parents=True)
        fq_dict = {'PE': [ToolIOFile(x) for x in pe_reads]}
        snakemakeutils.dump_object(fq_dict, io_pickle_in)

        # Dump the reference file in an IO file
        io_pickle_fasta_in = Path(self._working_dir / polish_assembly_short.INPUT_ASSEMBLY_FASTA.format(assembly_type='flye'))
        io_pickle_fasta_in.parent.mkdir(exist_ok=True, parents=True)
        snakemakeutils.dump_object([ToolIOFile(reference)], io_pickle_fasta_in)

        # Output files
        output_files = {
            'FASTA': Path(polish_assembly_short.OUTPUT_POLISHING_FASTA.format(assembly_type='flye'))
        }
        SnakePipelineUtils.run_snakemake(
            snakefile=polish_assembly_short.SNAKEFILE,
            config_path=config_file,
            targets=[Path(p) for p in output_files.values()],
            working_dir=self._working_dir,
            threads=threads)
        self.__set_output(output_files)

    def __set_output(self, output_files: dict[str, Path]) -> None:
        """
        Sets the output of this tool.
        :param output_files: Output files by key.
        :return: None
        """
        log_path = self._working_dir / 'camel.log'
        self._output = ShortReadPolishingWrapper.PolishingOutput(
            fasta_contigs=snakemakeutils.load_object(self._working_dir / output_files['FASTA'])[0].path,
            log_file=log_path if log_path.exists() else None
        )

    @property
    def output(self) -> 'ShortReadPolishingWrapper.PolishingOutput':
        """
        Returns the outputs generated by the polishing workflow.
        :return: Polishing output
        """
        return self._output
