from dataclasses import dataclass
from pathlib import Path
from typing import List, Dict, Optional, Any

from camel.app.components.vcf.vcfutils import VCFUtils
from camel.app.io.tooliofile import ToolIOFile
from camel.app.snakemake.snakemakeutils import SnakemakeUtils
from camel.app.snakemake.snakepipelineutils import SnakePipelineUtils
from camel.resources.snakefile import variant_calling


@dataclass
class VariantCallingInput:
    """
    This data class contains the input for the variant calling workflow.
    The input can be:
     - FASTQ where the PE reads are required and SE reads optional
    """
    pe_reads: Optional[List[ToolIOFile]] = None
    se_reads_fwd: Optional[ToolIOFile] = None
    se_reads_rev: Optional[ToolIOFile] = None


@dataclass
class VariantCallingOutput:
    """
    This data class contains the output generated by the wrapper.
    """
    bam_file: ToolIOFile
    vcf_unfiltered: ToolIOFile
    nb_of_variants: int
    informs_mapping: Dict[str, str]
    informs_all: List[Dict[str, Any]]


class VariantCallingWrapper(object):
    """
    This class is used as a wrapper class around the variant calling Snakemake workflow.
    """

    def __init__(self, working_dir: str) -> None:
        """
        Initializes the variant calling wrapper.
        :param working_dir: Working directory
        """
        self._working_dir = Path(working_dir)
        self._output = None

    @property
    def output(self) -> VariantCallingOutput:
        """
        Returns the workflow output.
        :return: Output
        """
        return self._output

    def __create_input(self, input_files: VariantCallingInput) -> None:
        """
        Creates the input files for the workflow.
        :param input_files: Input files
        :return: None
        """
        fq_dict = {'PE': input_files.pe_reads}
        if input_files.se_reads_fwd is not None:
            fq_dict['SE_FWD'] = [input_files.se_reads_fwd]
        if input_files.se_reads_rev is not None:
            fq_dict['SE_REV'] = [input_files.se_reads_rev]
        SnakemakeUtils.dump_object(fq_dict, self._working_dir / 'fq_dict.io')

    def run_workflow(self, reference_info: Dict[str, any], sample_name: str,
                     input_files: VariantCallingInput, options: Dict[str, Any],
                     cores: int = 8) -> None:
        """
        Runs the variant calling workflow.
        :param reference_info: Reference information
        :param sample_name: Sample name
        :param input_files: Workflow input files
        :param options: Variant calling options
        :param cores: Number of cores
        :return: None
        """
        # Create input
        self.__create_input(input_files)
        config_data = self.__get_config_data(sample_name, reference_info, options)
        config_file = SnakePipelineUtils.generate_config_file(config_data, self._working_dir)

        # Execute Snakemake
        output_files = {
            'BAM': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_BAM,
            'VCF': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_UNFILTERED_VCF,
            'INFORMS_MAPPING': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_MAPPING_INFORMS,
            'INFORMS_ALL': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_INFORMS_ALL
        }
        SnakePipelineUtils.run_snakemake(
            variant_calling.SNAKEFILE_VARIANT_CALLING, config_file, list(output_files.values()), self._working_dir,
            cores)

        # Collect output
        self.__collect_output(output_files)

    def __get_config_data(self, sample_name: str, reference_info: Dict[str, Any], options: Dict[str, Any]) -> \
            Dict[str, Any]:
        """
        Returns the config data.
        :param sample_name: Sample name
        :param reference_info: Dictionary with the info on the reference genome
        :param options: Dictionary with variant calling options
        :return: Config data
        """
        options['reference'] = {
            'name': reference_info['name'],
            'path': reference_info['path'],
            'url': reference_info.get('url', None)
        }
        return {
            'sample_name': sample_name,
            'working_dir': self._working_dir,
            'variant_calling': options,
            'variant_filtering': {}
        }

    def __collect_output(self, output_files: Dict[str, str]) -> None:
        """
        Collects the output files of the workflow.
        :param output_files: Output files dictionary by key
        :return: None
        """
        vcf_file = SnakemakeUtils.load_object(output_files['VCF'])[0]
        number_of_variants = VCFUtils.count_variants(vcf_file.path)
        self._output = VariantCallingOutput(
            bam_file=SnakemakeUtils.load_object(output_files['BAM'])[0],
            vcf_unfiltered=vcf_file,
            nb_of_variants=number_of_variants,
            informs_mapping=SnakemakeUtils.load_object(output_files['INFORMS_MAPPING']),
            informs_all=SnakemakeUtils.load_object(output_files['INFORMS_ALL'])
        )
