from dataclasses import dataclass
from pathlib import Path
from typing import List, Dict, Any

from camel.app.components.vcf.vcfutils import VCFUtils
from camel.app.components.workflows.utils.fastqinput import FastqInput
from camel.app.io.tooliofile import ToolIOFile
from camel.app.snakemake.snakemakeutils import SnakemakeUtils
from camel.app.snakemake.snakepipelineutils import SnakePipelineUtils
from camel.resources.snakefile import variant_calling


@dataclass
class VariantCallingOutput:
    """
    This data class contains the output generated by the wrapper.
    """
    bam_file: ToolIOFile
    vcf_unfiltered: ToolIOFile
    nb_of_variants: int
    informs_mapping: Dict[str, str]
    informs_all: List[Dict[str, Any]]


class VariantCallingWrapper(object):
    """
    This class is used as a wrapper class around the variant calling Snakemake workflow.
    """

    def __init__(self, working_dir: Path) -> None:
        """
        Initializes the variant calling wrapper.
        :param working_dir: Working directory
        """
        self._working_dir = working_dir
        self._output = None

    @property
    def output(self) -> VariantCallingOutput:
        """
        Returns the workflow output.
        :return: Output
        """
        return self._output

    def run_workflow(self, reference_info: Dict[str, any], sample_name: str, fastq_input: FastqInput,
                     options: Dict[str, Any], cores: int = 8) -> None:
        """
        Runs the variant calling workflow.
        :param reference_info: Reference information
        :param sample_name: Sample name
        :param fastq_input: FASTQ input files
        :param options: Variant calling options
        :param cores: Number of cores
        :return: None
        """
        # Create input
        if not self._working_dir.exists():
            self._working_dir.mkdir(parents=True)
        SnakemakeUtils.dump_object(fastq_input.to_fq_dict(), self._working_dir / 'fq_dict.io')
        config_data = self.__get_config_data(sample_name, reference_info, options)
        config_data['read_type'] = fastq_input.read_type
        config_file = SnakePipelineUtils.generate_config_file(config_data, self._working_dir)

        # Execute Snakemake
        output_files = {
            'BAM': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_BAM,
            'VCF': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_UNFILTERED_VCF,
            'INFORMS_MAPPING': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_MAPPING_INFORMS,
            'INFORMS_ALL': self._working_dir / variant_calling.OUTPUT_VARIANT_CALLING_INFORMS_ALL
        }
        SnakePipelineUtils.run_snakemake(
            variant_calling.SNAKEFILE_VARIANT_CALLING, config_file, list(output_files.values()), self._working_dir,
            cores)

        # Collect output
        self.__collect_output(output_files)

    def __get_config_data(self, sample_name: str, reference_info: Dict[str, Any], options: Dict[str, Any]) -> \
            Dict[str, Any]:
        """
        Returns the config data.
        :param sample_name: Sample name
        :param reference_info: Dictionary with the info on the reference genome
        :param options: Dictionary with variant calling options
        :return: Config data
        """
        options['reference'] = {
            'name': reference_info['name'],
            'path': reference_info['path'],
            'url': reference_info.get('url', None)
        }
        return {
            'sample_name': sample_name,
            'working_dir': str(self._working_dir),
            'variant_calling': options,
            'variant_filtering': {},
            'input_type': 'illumina'
        }

    def __collect_output(self, output_files: Dict[str, Path]) -> None:
        """
        Collects the output files of the workflow.
        :param output_files: Output files dictionary by key
        :return: None
        """
        vcf_file = SnakemakeUtils.load_object(output_files['VCF'])[0]
        number_of_variants = VCFUtils.count_variants(vcf_file.path)
        self._output = VariantCallingOutput(
            bam_file=SnakemakeUtils.load_object(output_files['BAM'])[0],
            vcf_unfiltered=vcf_file,
            nb_of_variants=number_of_variants,
            informs_mapping=SnakemakeUtils.load_object(output_files['INFORMS_MAPPING']),
            informs_all=SnakemakeUtils.load_object(output_files['INFORMS_ALL'])
        )
