from pathlib import Path

from camel.app.core.command import Command
from camel.app.core.errors import ToolExecutionError
from camel.app.core.tool import Tool
from camel.app.core.io.tooliofile import ToolIOFile


class MultiQC(Tool):
    """
    =============================
    MulitQC 1.11
    =============================
    MultiQC is a reporting tool that parses summary statistics from results and log files generated by other bioinformatics
    tools.

    Required inputs:
    ----------------
    'TXT_log'           ToolIOFile object. MultiQC will produce a report based on details found in any log files that
                        it recognises.
                        Note: You can supply MultiQC with one or more directories which will be scanned, and MultiQC will
                        automatically recognize log files from many released bioinformatics tools. The 'Directory as input'
                        mode has not been added in the current Camel implementation because of the way Camel tools are used
                        in Snakemake pipelines.

    Output:
    -------
    'HTML'              ToolIOFile. MultiQC report summarizing all input files.

    Parameters:
    ___________
    report_name         Report filename. Use 'stdout' to print to standard out.
    force               Overwrite existing reports
    ignore              Ignore analysis files and directories. Multiple files separated by semicolon
    ignore_symlinks     Ignore symlinked directories and files
    output_directory    Create report in the specified output directory.
    prefix_names        Prepend directory to sample names
    prefix_names_depth  Prepend [INT] directories to sample names. Negative number to take from start of path. Only use
                        in combination with prefix_names
    template            [default|default_dev|gathered|geo|sections|simple]

    """

    def __init__(self) -> None:
        """
        Initialize tool
                :return: None
        """
        super().__init__('multiqc', '1.11')
        self._input_string = ''
        self._specific_parameters = ["ignore"]

    def _execute_tool(self) -> None:
        """
        Run a multiqc function
        :return: None
        """
        self._set_input()
        self._set_output()
        self._build_command()
        self._execute_command()
        self._set_informs()

    def _set_input(self) -> None:
        """
        Set input of multiqc function
        :return: None
        """
        self._input_string = " ".join([str(f.path) for f in self._tool_inputs["TXT_log"]])

    def _set_output(self) -> None:
        """
        Set output of multiqc function
        :return: None
        """
        if 'output_directory' in self._parameters:
            self._tool_outputs['HTML'] = [ToolIOFile(Path(self._parameters['output_directory'].value) / self._parameters['report_name'].value)]

        else:
            self._tool_outputs['HTML'] = [ToolIOFile(self.folder / self._parameters['report_name'].value)]

    def _build_command(self) -> None:
        """
        Build command of multiqc function
        :return: None
        """
        build_options = self._build_options(excluded_parameters=self._specific_parameters)
        # ignore can contain multiple files, separated by a semicolon
        if 'ignore' in self._parameters:
            build_options.extend([f'{self._parameters["ignore"].option} {f}' for f in self._parameters['ignore'].value.split(";")])

        self._command.command = " ".join([self._tool_command, self._input_string, *build_options])

    def _set_informs(self) -> None:
        """
        Set informs of multiqc function
        :return: None
        """
        for line in self._command.stderr.splitlines():
            if line.startswith("|"):
                empty, info, message = line.split("|")
                if message.strip().startswith("Report"):
                    self._informs["report_name"] = message.split(":")[1].strip()
                if message.strip().startswith("Data"):
                    self._informs["data_dir"] = message.split(":")[1].strip()

    def _check_command_output(self, command: Command) -> None:
        """
        Checks command output
        :return: None
        """
        for line in command.stderr.splitlines():
            if line.startswith("|"):
                empty, info, message = line.split("|")
                if message.strip().startswith("Error"):
                    raise ToolExecutionError(self.name, f"Command execution failed (stderr: {message}).")
