#####################
# Pipeline settings #
#####################
citations:
  main: null
  other:
    - Chen_2023-fastp
    - Shen_2024-seqkit2
    - Bankevich_2012-spades
    - Kolmogorov_2019-flye
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Li_2021-minimap2
    - Li_2009-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Bortolaia_2020-resfinder_4.0
    - Feldgarden_2019-ndaro
    - Chen_2016-vfdb
    - Carattoli_2020-plasmidfinder
    - Jolley_2010-bigsdb
    - Lam_2021-kleborate
    - Wyres_2016-kaptive
    - Robertson_2018-mob_suite
    - Hyatt_2010-prodigal
    - Pal_2014-bacmet

#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 5_330_000

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Klebsiella pneumoniae

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: 57.5

quast:
  ref:
    fasta: /db/refgenomes/Klebsiella_pneumoniae/NC_016845.1.fasta
    gff3: /db/refgenomes/Klebsiella_pneumoniae/NC_016845.1.gff3

confindr:
  db: /db/confindr/0.8.1

srst2:
  max_unaligned_overlap: 141

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

variant_calling:
  ploidy: 1
  report_include_bam: {export_bam}
  reference:
    path: /db/refgenomes/Klebsiella_pneumoniae/NC_016845.1.fasta
    name: <i>Klebsiella pneumoniae subsp. pneumoniae</i> HS11286 (NC_016845.1)
    url: https://www.ncbi.nlm.nih.gov/nuccore/NC_016845.1

amrfinder:
  db: /db/amrfinder/by_version/v3/latest

resfinder4:
  db: /db/resfinder4
  species: Klebsiella

bacmet:
  db: /db/bacmet/latest

mob_suite:
  db: /db/mob_suite/latest

############################
# Gene detection databases #
############################
gene_detection:
  vfdb_core:
    path: /db/gene_detection/VFDB_core
    perc_identity_cutoff: 90
    metadata:
      name: Gene
      key: gene

  plasmidfinder:
    path: /db/gene_detection/PlasmidFinder-entero
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 60
      srst2:
        max_divergence: 5
        min_coverage: 60
    message:
      content: The presence of a replicon does not mean that the corresponding plasmid is present.
      category: warning

###################
# Sequence typing #
###################
sequence_typing:
  mlst:
    path: /db/sequence_typing/klebsiella/mlst/
  scgmlst:
    path: /db/sequence_typing/klebsiella/scgmlst629_s/
  cgmlst:
    path: /db/sequence_typing/klebsiella/cgmlst/
    detection_method: blast
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info
