slurm:
  slurm_args:
    "is": ""
    "notemp": ""
    "jobs": "1000"
params_smk:
    'threads_bwa': 8
    'threads_picard': 2
    'threads_bqsr': 4
    'threads_apply_bqsr': 3
    'threads_haplotype_caller': 2
    'threads_cram': 2
    'memory_mb_bwa': 15000
    'memory_mb_picard': 50000
    'memory_mb_mark_duplicates_sort': 100000
    'memory_mb_bqsr': 50000
    'memory_mb_haplotype_caller': 10000
    'memory_mb_cram': 60000
