#!/usr/bin/env python
import argparse
import logging
from typing import Tuple, Any, List, Dict

import os
import yaml

from camel.app.camel import Camel
from camel.app.components.files.fastqutils import FastqUtils
from camel.app.error.snakemakeexecutionerror import SnakemakeExecutionError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.pipeline.pipeline import Pipeline
from camel.app.snakemake.snakepipelineutils import SnakePipelineUtils
from camel.scripts.stecpipeline import SNAKEFILE_MAIN, CONFIG_TEMPLATE


class MainSTECPipeline(object):
    """
    Main class to run the STEC pipeline.
    """

    PIPELINE_NAME = 'STEC pipeline'
    PIPELINE_VERSION = 1.0

    def run(self) -> None:
        """
        Runs the pipeline.
        :return: None
        """
        # Output file generated by Galaxy is deleted first (otherwise Snakemake does nothing)
        if os.path.isfile(self._args.output_html):
            os.remove(self._args.output_html)

        # Construct pipeline and log input and config file
        pipeline = Pipeline(MainSTECPipeline.PIPELINE_NAME, Camel.get_instance(),
                            logging_level='pipeline' if self._args.db_logging else None)
        if self._args.fastq_pe is not None:
            pipeline.set_initial_input({'FASTQ_PE': [ToolIOFile(x) for x in self._args.fastq_pe]})
        else:
            pipeline.set_initial_input({'FASTQ_SE': [ToolIOFile(self._args.fastq_se)]})
        config_file = self.__construct_config_file()
        pipeline.log_config_file(config_file)

        # Run Snakemake
        try:
            SnakePipelineUtils.run_snakemake(SNAKEFILE_MAIN, config_file, [], self._args.working_dir,
                                             self._args.threads)
        except SnakemakeExecutionError as err:
            pipeline.log_error_to_file(err)

        logging.info("Pipeline finished successfully")

    def __init__(self):
        """
        Initializes the main class.
        """
        self._args = MainSTECPipeline._parse_arguments()
        if not os.path.isdir(self._args.output_dir):
            os.mkdir(self._args.output_dir)
        self._sample_name = self.__get_sample_name()

    def __get_sample_name(self) -> str:
        """
        Determines the sample name from the command line arguments.
        :return: Sample name
        """
        if self._args.sample_name is not None:
            return self._args.sample_name
        if self._args.fastq_pe is not None:
            if self._args.fastq_pe_names is not None:
                return FastqUtils.get_sample_name(self._args.fastq_pe_names[0])
            else:
                return FastqUtils.get_sample_name(self._args.fastq_pe[0])
        if self._args.fastq_se is not None:
            if self._args.fastq_se_name is not None:
                return FastqUtils.get_sample_name(self._args.fastq_se_name, False)
            else:
                return FastqUtils.get_sample_name(self._args.fastq_se, False)
        raise ValueError("Cannot determine sample name from command line arguments.")

    def __construct_config_file(self) -> str:
        """
        Constructs the configuration file to run Snakemake.
        :return: Config file path
        """
        analyses = [key for key in (
            'kraken', 'resfinder', 'argannot', 'card', 'ncbi_amr', 'mlst_pasteur', 'mlst_warwick', 'cgmlst',
            'pointfinder', 'plasmidfinder', 'serotype', 'virulence') if vars(self._args)[key] is True]
        input_key, input_dict = self.__create_fastq_input_dict()
        with open(CONFIG_TEMPLATE) as handle_in:
            config_data = yaml.load(handle_in.read().format(
                sample_name=self._sample_name,
                version=MainSTECPipeline.PIPELINE_VERSION,
                logging=self._args.db_logging,
                fastq_key=input_key,
                fastq_input=input_dict,
                output_report=self._args.output_html,
                output_tabular=self._args.output_summary,
                output_dir=self._args.output_dir,
                working_dir=self._args.working_dir,
                detection_method=self._args.detection_method,
                read_type=self._args.read_type,
                analyses=yaml.dump(analyses),
                variant_filtering={},
                qc_typing_scheme='cgmlst' if self._args.cgmlst else 'mlst_warwick',
                export_fastq='true' if self._args.report_include_fastq else 'false',
                export_bam='true' if self._args.report_include_bam else 'false'
            ))
        return SnakePipelineUtils.generate_config_file(config_data, self._args.working_dir)

    def __create_fastq_input_dict(self) -> Tuple[str, List[Dict[str, Any]]]:
        """
        Creates the input dictionary with the FASTQ files.
        :return: Input key, input dictionary
        """
        if self._args.read_type == 'illumina':
            if self._args.fastq_pe is None:
                raise ValueError("Illumina input should be paired-end.")
            fq_files = SnakePipelineUtils.symlink_input_files(
                os.path.join(self._args.working_dir, 'input'), self._args.fastq_pe, self._args.fastq_pe_names, True)
            return 'fastq_pe', [{'name': name, 'path': path} for name, path in zip(
                self._args.fastq_pe_names, fq_files)]
        else:
            if self._args.fastq_se is None:
                raise ValueError("IonTorrent input should be single-end.")
            fq_file = SnakePipelineUtils.symlink_input_files(
                os.path.join(self._args.working_dir, 'input'), [self._args.fastq_se], [self._args.fastq_se_name],
                True)[0]
            return 'fastq_se', [{'name': self._args.fastq_se_name, 'path': fq_file}]

    @staticmethod
    def _parse_arguments() -> argparse.Namespace:
        """
        Parses the command line arguments.
        :return: Arguments
        """
        parser = argparse.ArgumentParser()

        # Input
        parser.add_argument('--sample-name', help="Name of the sample")
        parser.add_argument('--fastq-pe', nargs=2, help="FASTQ input files")
        parser.add_argument('--fastq-pe-names', nargs=2, help="FASTQ input file names")
        parser.add_argument('--fastq-se', help="Input SE FASTQ file")
        parser.add_argument('--fastq-se-name', help="Input SE FASTQ file name")
        parser.add_argument('--read-type', help="Type of reads.", choices=['illumina', 'iontorrent'],
                            default='illumina')
        parser.add_argument('--library', help="Adapter library that was used for the sequencing")

        # Configuration
        parser.add_argument('--detection-method', help="Type of allele detection: local alignment (blast), read "
                                                       "mapping (srst2)", choices=['blast', 'srst2'], required=True)
        parser.add_argument('--threads', type=int, default=8)
        parser.add_argument('--working-dir', default=os.path.abspath('.'), type=str)
        parser.add_argument('--db-logging', action='store_true')

        # Output
        parser.add_argument('--output-summary', help="Output file for the summary")
        parser.add_argument('--output-html', help="Output file for the HTML report", required=True)
        parser.add_argument('--output-dir', help="Output directory for the files in the HTML report", required=True)
        parser.add_argument('--report-include-fastq', help="Include the FASTQ files in the report", action='store_true')
        parser.add_argument('--report-include-bam', help="Include the BAM file in the report", action='store_true')

        # Kraken
        parser.add_argument('--kraken', action='store_true')

        # Gene detection
        parser.add_argument('--argannot', action='store_true')
        parser.add_argument('--card', action='store_true')
        parser.add_argument('--resfinder', action='store_true')
        parser.add_argument('--ncbi-amr', action='store_true')
        parser.add_argument('--pointfinder', action='store_true')
        parser.add_argument('--serotype', action='store_true')
        parser.add_argument('--virulence', action='store_true')
        parser.add_argument('--plasmidfinder', action='store_true')

        # Typing
        parser.add_argument('--mlst-pasteur', action='store_true')
        parser.add_argument('--mlst-warwick', action='store_true')
        parser.add_argument('--cgmlst', action='store_true')
        parser.add_argument('--wgmlst', action='store_true')
        return parser.parse_args()


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main = MainSTECPipeline()
    main.run()
