#####################
# Pipeline settings #
#####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Zankari_2012-resfinder
    - Feldgarden_2019-ndaro
    - Zankari_2017-pointfinder
    - Joensen_2014-virulencefinder
    - Chen_2016-vfdb
    - Carattoli_2020-plasmidfinder
    - Antipov_2016-plasmidspades
    - Jolley_2010-bigsdb

#########################
# Tool specific options #
#########################
read_trimming:
  export_fastq: '{export_fastq}'

contamination_check:
  db: /db/kraken2/latest/abfhpv/
  expected_species: Staphylococcus aureus

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: 32.7

srst2:
  max_unaligned_overlap: 141

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

spa_typing:
  db: /db/pipelines/saureus/profiles.fasta
  profiles: /db/pipelines/saureus/spatypes.csv

sccmec_typing:
  profiles: /db/pipelines/saureus/SCCmec_genes/profiles.yml

pointfinder:
  db: staphylococcus_aureus

############################
# Gene detection databases #
############################
gene_detection:
  resfinder:
    path: /db/gene_detection/ResFinder
    perc_identity_cutoff: 90
    metadata:
      name: Antibiotic(s)
      key: antibiotics

  ncbi_amr:
    path: /db/gene_detection/NCBI_AMR/
    perc_identity_cutoff: 90

  vfdb_core:
    path: /db/gene_detection/VFDB_core
    perc_identity_cutoff: 90
    metadata:
      name: Gene
      key: gene

  vf_exoenzyme:
    path: /db/gene_detection/VirulenceFinder-Saureus-exoenzyme
    metadata:
      name: Protein function
      key: protein_function

  vf_hostimm:
    path: /db/gene_detection/VirulenceFinder-Saureus-hostimm
    metadata:
      name: Protein function
      key: protein_function

  vf_toxin:
    path: /db/gene_detection/VirulenceFinder-Saureus-toxin
    metadata:
      name: Protein function
      key: protein_function

  sccmec_genes:
    path: /db/gene_detection/SCCmec_genes

  sccmec_cassette:
    path: /db/gene_detection/SCCmec_cassette
    force_detection_method: srst2

###################
# Sequence typing #
###################
sequence_typing:
  mlst:
    path: /db/sequence_typing/staphylococcus/mlst
  cgmlst:
    path: /db/sequence_typing/staphylococcus/cgmlst
    detection_method: blast
