import os

from app.io.tooliofile import ToolIOFile
from app.tools.velvet.velvetgoutputanalyzer import VelvetgOutputAnalyzer
from app.tools.tool import Tool


class Velvetg(Tool):
    """
    Velvetg construct an assembly (contigs) from reads kmer hash database generated by velveth
    """
    OUTPUT_FASTA = 'contigs.fa'
    LOG_FILE = 'Log'
    STATS_FILE = 'stats.txt'

    def __init__(self, camel):
        """
        Initialize Velvetg
        :param camel: Camel instance
        :return: None
        """
        super(Velvetg, self).__init__('velvetg', '1.2.10', camel)
        self._output_dir = None

    def _execute_tool(self):
        """
        Function to run BWA index
        :return: None
        """
        self.__build_command()
        self._execute_command()
        self.__set_output()
        self.__set_inform()

    def _check_input(self):
        """
        Check input for velvetg
        :return: None
        """
        super(Velvetg, self)._check_input()

        if 'DIR_DB' not in self._tool_inputs:
            raise ValueError('Velveth DB path (DIR_DB) is missing.')

    def __set_output(self):
        """
        Set output for velvetg
        :return: None
        """
        self._output_dir = self._tool_inputs['DIR_DB'][0].path
        self._tool_outputs['FASTA_Contig'] = [ToolIOFile(os.path.join(self._output_dir, Velvetg.OUTPUT_FASTA))]

    def __build_command(self):
        """
        Set command to run velvetg
        :return: None
        """
        self._command.command = "{} {} {}".format(
            self._tool_command,
            self._tool_inputs['DIR_DB'][0].path,
            " ".join(self._build_options()))

    def __set_inform(self):
        """
        Analyze the result of velvetg run to extract statistics. Three sources are analyzed: analyze Log file for basic
        assembly statistics; stats.txt for contigs stats (idea from VelvetOptimiser); and command line output
        (self._command.stdout) for 'Paired Library insert' & 'Coverage stats'
        :return: None
        """
        self.informs['tool_name'] = 'Velvet'

        self.informs.update(
            VelvetgOutputAnalyzer.analyze_log_file(os.path.join(self._output_dir, Velvetg.LOG_FILE))
        )
        self.informs['kmer'] = int(self._input_informs['velveth']['kmer'])
        self.informs.update(VelvetgOutputAnalyzer.analyze_velvetg_output(self.informs, self.stdout))
        # analyze self._command.stdout before stats file, as some information
        # from output is required to analyze the later.
        self.informs.update(
            VelvetgOutputAnalyzer.analyze_stats_file(self.informs, os.path.join(self._output_dir, Velvetg.STATS_FILE))
        )
