from dataclasses import dataclass
from pathlib import Path
from typing import Any

from camel.app.core.io.tooliofile import ToolIOFile
from camel.app.scriptutils.basepipe.fastqinput import FastqInput
from camel.app.core.snakemake import snakemakeutils
from camel.app.core.snakemake import snakepipelineutils
from camel.app.core.utils import vcfutils
from camel.snakefiles import variant_calling


@dataclass
class VariantCallingOutput:
    """
    This data class contains the output generated by the wrapper.
    """
    bam_file: ToolIOFile
    vcf_unfiltered: ToolIOFile
    nb_of_variants: int
    informs_mapping: dict[str, str]
    informs_all: list[dict[str, Any]]


class VariantCallingWrapper:
    """
    This class is used as a wrapper class around the variant calling Snakemake workflow.
    """

    def __init__(self, working_dir: Path) -> None:
        """
        Initializes the variant calling wrapper.
        :param working_dir: Working directory
        """
        self._working_dir = working_dir
        self._output = None

    @property
    def output(self) -> VariantCallingOutput:
        """
        Returns the workflow output.
        :return: Output
        """
        return self._output

    def run(self, reference_info: dict[str, Any], sample_name: str, fastq_input: FastqInput, input_type: str,
            options: dict[str, Any], cores: int = 8) -> None:
        """
        Runs the variant calling workflow.
        :param reference_info: Reference information
        :param sample_name: Sample name
        :param fastq_input: FASTQ input files
        :param input_type: Input type
        :param options: Variant calling options
        :param cores: Number of cores
        :return: None
        """
        # Create input
        if not self._working_dir.exists():
            self._working_dir.mkdir(parents=True)
        snakemakeutils.dump_object(fastq_input.to_fq_dict(), self._working_dir / 'fq_dict.io')
        config_data = self.__get_config_data(sample_name, reference_info, options)
        config_file = snakepipelineutils.generate_config_file(config_data, self._working_dir)

        # Execute Snakemake
        output_files = {
            'BAM': variant_calling.get_bam({'input': {'type': input_type}, 'working_dir': self._working_dir}),
            'VCF': Path(variant_calling.OUTPUT_UNFILTERED_VCF_GZ),
            'INFORMS_MAPPING': Path(variant_calling.OUTPUT_MAPPING_INFORMS),
            'INFORMS_ALL': Path(variant_calling.OUTPUT_INFORMS_ALL)
        }
        snakepipelineutils.run_snakemake(
            variant_calling.SNAKEFILE, config_file, list(output_files.values()), self._working_dir, cores)

        # Collect output
        self.__collect_output(output_files)

    def __get_config_data(self, sample_name: str, reference_info: dict[str, Any], options: dict[str, Any]) -> \
            dict[str, Any]:
        """
        Returns the config data.
        :param sample_name: Sample name
        :param reference_info: Dictionary with the info on the reference genome
        :param options: Dictionary with variant calling options
        :return: Config data
        """
        return {
            'reference': {
                'name': reference_info['name'],
                'fasta': reference_info['path'],
                'url': reference_info.get('url', None),
            },
            'working_dir': str(self._working_dir),
            'variant_calling': options,
            'variant_filtering': {},
            'input': {'sample_name': sample_name, 'type': 'illumina'},
        }

    def __collect_output(self, output_files: dict[str, Path]) -> None:
        """
        Collects the output files of the workflow.
        :param output_files: Output files dictionary by key
        :return: None
        """
        vcf_file = snakemakeutils.load_object(self._working_dir / output_files['VCF'])[0]
        number_of_variants = vcfutils.count_variants(vcf_file.path)
        self._output = VariantCallingOutput(
            bam_file=snakemakeutils.load_object(self._working_dir / output_files['BAM'])[0],
            vcf_unfiltered=vcf_file,
            nb_of_variants=number_of_variants,
            informs_mapping=snakemakeutils.load_object(self._working_dir / output_files['INFORMS_MAPPING']),
            informs_all=snakemakeutils.load_object(self._working_dir / output_files['INFORMS_ALL'])
        )
