import logging
from collections import OrderedDict

import os

from camel.app.components.filesystemhelper import FileSystemHelper
from camel.app.tools.bcftools.bcftoolsindex import BcftoolsIndex
from camel.app.tools.variantfiltering.depthfilter import DepthFilter
from camel.app.tools.variantfiltering.distancefilter import DistanceFilter
from camel.app.tools.variantfiltering.mappingqualityfilter import MappingQualityFilter
from camel.app.tools.variantfiltering.snpqualityfilter import SnpQualityFilter
from camel.app.tools.variantfiltering.zscorefilter import ZScoreFilter


class VcfFiltering(object):
    """
    Class that performs filtering on VCF files generated by Samtools.
    """

    def __init__(self, camel, directory, args):
        """
        Initializes the filtering object.
        :param camel: CAMEL instance
        :param directory: directory where the filtering is done.
        :param args: Command line arguments for the filters
        """
        self._camel = camel
        self._directory = directory
        self._filtering_info = OrderedDict(
            [(key, []) for key in ('Depth', 'SNP Quality', 'Mapping Quality', 'Distance', 'Z-Score')])
        self._args = args

    @property
    def info(self):
        """
        Returns the filtering info.
        :return: Filtering info
        """
        return self._filtering_info

    def apply(self, sample_name, vcf_file, bam_file):
        """
        Applies the SNP filtering on the given sample.
        :param sample_name: Sample name
        :param vcf_file: VCF file
        :param bam_file: BAM file
        :return: None
        """
        filtering_directory = os.path.join(self._directory, 'filtering', FileSystemHelper.make_valid(sample_name))
        os.makedirs(filtering_directory)
        vcf_file = self.__run_depth_filter(vcf_file, filtering_directory, self._args.min_total_depth,
                                           self._args.min_forward_depth, self._args.min_reverse_depth)
        vcf_file = self.__run_snp_quality_filter(vcf_file, filtering_directory, self._args.min_snp_quality)
        vcf_file = self.__run_mapping_quality_filter(vcf_file, filtering_directory)
        vcf_file = self.__run_distance_filter(vcf_file, filtering_directory)
        vcf_file = self.__run_zscore_filter(vcf_file, filtering_directory, bam_file)
        return vcf_file

    def __index_vcf(self, vcf_file, directory):
        """
        Indexes a VCF file.
        :param vcf_file: VCF file
        :param directory: Directory
        :return: Indexed VCF file
        """
        bcftools_index = BcftoolsIndex(self._camel)
        bcftools_index.add_input_files({'VCF_GZ': [vcf_file]})
        bcftools_index.run(directory)
        return bcftools_index.tool_outputs['VCF_GZ'][0]

    def __run_depth_filter(self, vcf_file, directory, min_total_depth, min_fwd_depth, min_rev_depth):
        """
        Applies the depth filter.
        :param vcf_file: VCF file
        :param directory: Directory
        :param min_total_depth: Minimal total depth
        :param min_fwd_depth: Minimal forward depth
        :param min_rev_depth: Minimal reverse depth
        :return: filtered VCF file
        """
        logging.info("Performing depth filtering.")
        depth_filter = DepthFilter(self._camel)
        depth_filter.add_input_files({'VCF_GZ': [vcf_file]})
        depth_filter.update_parameters(min_depth=min_total_depth,
                                       min_forward_depth=min_fwd_depth,
                                       min_reverse_depth=min_rev_depth)
        depth_filter.run(directory)
        self._filtering_info['Depth'].append(
            '{}/{}'.format(depth_filter.informs['variants_out'], depth_filter.informs['variants_in']))
        return depth_filter.tool_outputs['VCF_GZ'][0]

    def __run_snp_quality_filter(self, vcf_file, directory, min_snp_quality):
        """
        Applies the SNP quality filter.
        :param vcf_file: VCF file
        :param directory: Directory
        :param min_snp_quality: Minimal SNP quality
        :return: Filtered VCF file
        """
        logging.info("Performing snp quality filtering")
        snp_quality_filter = SnpQualityFilter(self._camel)
        snp_quality_filter.add_input_files({'VCF_GZ': [vcf_file]})
        snp_quality_filter.update_parameters(min_snp_quality=min_snp_quality)
        snp_quality_filter.run(directory)
        self._filtering_info['SNP Quality'].append('{}/{}'.format(
            snp_quality_filter.informs['variants_out'], snp_quality_filter.informs['variants_in']))
        return snp_quality_filter.tool_outputs['VCF_GZ'][0]

    def __run_mapping_quality_filter(self, vcf_file, directory):
        """
        Applies the mapping quality filter.
        :param vcf_file: VCF file
        :param directory: Directory
        :return: Filtered VCF file
        """
        logging.info("Performing mapping quality filtering")
        mapping_quality_filter = MappingQualityFilter(self._camel)
        mapping_quality_filter.add_input_files({'VCF_GZ': [vcf_file]})
        mapping_quality_filter.update_parameters(min_mapping_quality=self._args.min_mapping_quality)
        mapping_quality_filter.run(directory)
        self._filtering_info['Mapping Quality'].append('{}/{}'.format(
            mapping_quality_filter.informs['variants_out'], mapping_quality_filter.informs['variants_in']))
        return mapping_quality_filter.tool_outputs['VCF_GZ'][0]

    def __run_distance_filter(self, vcf_file, directory):
        """
        Applies the distance filter.
        :param vcf_file: VCF file
        :param directory: Directory
        :return: Filtered VCF file
        """
        vcf_file = self.__index_vcf(vcf_file, directory)
        logging.info("Performing distance filtering")
        distance_filter = DistanceFilter(self._camel)
        distance_filter.add_input_files({'VCF_GZ': [vcf_file]})
        distance_filter.update_parameters(min_distance=self._args.min_distance, keep_best=self._args.keep_best)
        distance_filter.run(directory)
        self._filtering_info['Distance'].append('{}/{}'.format(
            distance_filter.informs['variants_out'], distance_filter.informs['variants_in']))
        return distance_filter.tool_outputs['VCF_GZ'][0]

    def __run_zscore_filter(self, vcf_file, directory, bam_file):
        """
        Applies the Z-Score filter.
        :param vcf_file: VCF file
        :param directory: Directory
        :param bam_file: BAM file
        :return: Filtered VCF file
        """
        vcf_file = self.__index_vcf(vcf_file, directory)
        zscore_filter = ZScoreFilter(self._camel)
        zscore_filter.add_input_files({'VCF_GZ': [vcf_file], 'BAM': [bam_file]})
        zscore_filter.update_parameters(min_zscore=self._args.min_zscore, y_multiplier=self._args.y_mult)
        zscore_filter.run(directory)
        self._filtering_info['Z-Score'].append('{}/{}'.format(
            zscore_filter.informs['variants_out'], zscore_filter.informs['variants_in']))
        return zscore_filter.tool_outputs['VCF_GZ'][0]
