#############
# Databases #
#############
dbs:
  ampc:
    location: &db_ampc {DB_ROOT}/pipelines/yersinia/gene_detection-ampc
    required: false
    method: ftp
  amrfinder:
    location: &db_amrfinder {DB_ROOT}/amrfinder/v4/latest
    required: false
    method: ftp
  confindr:
    location: &db_confindr {DB_ROOT}/confindr/0.8.1
    required: false
    method: skip
  mobsuite:
    location: &db_mobsuite {DB_ROOT}/mob_suite/latest
    required: false
    method: ftp
  ncbi_human_read_scrubber:
    location: &db_ncbi_human_read_scrubber {DB_ROOT}/ncbi_human_read_scrubber/human_filter.db
    is_file: true
    required: false
    method: ftp
  ref_fasta:
    location: &ref_fasta {DB_ROOT}/refgenomes/Yersinia_enterocolitica/GCF_025758635.1.fasta
    is_file: true
    required: true
    method: ftp
  ref_gff3:
    location: &ref_gff3 {DB_ROOT}/refgenomes/Yersinia_enterocolitica/GCF_025758635.1.gff3
    is_file: true
    required: true
    method: ftp
  resfinder4:
    location: &db_resfinder4 {DB_ROOT}/resfinder4
    required: false
    method: ftp
  taxonomic:
    location: &db_taxonomic {DB_ROOT}/pipelines/yersinia/cgMLST_taxonomic.tsv
    is_file: true
    required: false
    method: ftp
  typing_cgmlst_enterobase:
    location: &db_typing_cgmlst_enterobase {DB_ROOT}/sequence_typing/yersinia/cgmlst_enterobase
    required: false
    method: mist
  typing_cgmlst_ye:
    location: &db_typing_cgmlst_ye {DB_ROOT}/sequence_typing/yersinia/cgmlst_yersinia_enterocolitica
    required: false
    method: mist
  typing_cgmlst_yersinia_spp:
    location: &db_typing_cgmlst_yersinia_spp {DB_ROOT}/sequence_typing/yersinia/cgmlst_yersinia_spp
    required: false
    method: mist
  typing_cgmlst_yp:
    location: &db_typing_cgmlst_yp {DB_ROOT}/sequence_typing/yersinia/cgmlst_yersinia_pseudotuberculosis
    required: false
    method: mist
  typing_mlst_achtman:
    location: &db_typing_mlst_achtman {DB_ROOT}/sequence_typing/yersinia/mlst_achtman
    is_file: false
    method: mist
  typing_mlst_mcnally:
    location: &db_typing_mlst_mcnally {DB_ROOT}/sequence_typing/yersinia/mlst_mcnally
    is_file: false
    method: mist
  typing_rmlst:
    location: &db_typing_rmlst {DB_ROOT}/sequence_typing/various/rmlst
    required: false
    method: skip
  vfdb_core:
    location: &db_vfdb_core {DB_ROOT}/gene_detection/VFDB_core
    required: false
    method: ftp

####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Chen_2023-fastp
    - Shen_2024-seqkit2
    - Bankevich_2012-spades
    - Kolmogorov_2019-flye
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Li_2021-minimap2
    - Danecek_2021-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Bortolaia_2020-resfinder_4.0
    - Feldgarden_2019-ndaro
    - Jolley_2010-bigsdb
    - Chen_2016-vfdb
    - Savin_2019-yersinia_cgmlst

####################
# Reference genome #
####################
reference:
  name: <i>Y. enterolitica</i> NW56 (GCF_025758635.1)
  fasta: *ref_fasta
  gff3: *ref_gff3
  url: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_025758635.1/

#########################
# Tool-specific options #
#########################
downsampling:
  coverage_max: {COV_MAX}

contamination_check:
  db: {K2_DB}
  expected_species: 'Yersinia'
  level_of_depth: G

quality_checks:
  typing_scheme: {QC_SCHEME}

assembly:
  spades:
    cov_cutoff: 'off'
  min_contig_length: 1000

amrfinder:
  db: *db_amrfinder

mob_suite:
  db: *db_mobsuite

confindr:
  db: *db_confindr

resfinder4:
  point: False
  db: *db_resfinder4

read_trimming: {{}}

read_scrubbing:
  db: *db_ncbi_human_read_scrubber

species_determination:
  tsv: *db_taxonomic

##################
# Gene detection #
##################
gene_detection:
  dbs:
    vfdb_core:
      path: *db_vfdb_core
      metadata:
        name: Gene
        key: gene
      hidden: true
    ampc:
      path: *db_ampc
      params:
        blastn:
          min_percent_identity: 95
          min_coverage: 60
        kma:
          min_percent_identity: 95
          min_coverage: 60
      metadata:
        name: Antibiotics
        key: antibiotics

###################
# Sequence typing #
###################
sequence_typing:
  dbs:
    cgmlst:
      path: *db_typing_cgmlst_yersinia_spp
      detection_method: blast
      write_all_matches: True
    mlst:
      path: *db_typing_mlst_achtman
    mlst_mcnally:
      path: *db_typing_mlst_mcnally
    cgmlst_ye:
      path: *db_typing_cgmlst_ye
      detection_method: blast
    cgmlst_yp:
      path: *db_typing_cgmlst_yp
    cgmlst_enterobase:
      path: *db_typing_cgmlst_enterobase
    rmlst:
      path: *db_typing_rmlst
      message:
        content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
        category: info
