import os

from camel.app.camel import Camel
from camel.app.components.sequencetyping.sequencetypingblasthit import SequenceTypingBlastHit
from camel.app.tools.tool import Tool

from camel.app.components.blast.alignmentextraction import AlignmentExtraction
from camel.app.components.filesystemhelper import FileSystemHelper
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.error.toolexecutionerror import ToolExecutionError
from camel.app.io.tooliofile import ToolIOFile


class AlignmentExtractor(Tool):
    """
    Tool that extracts alignments from TXT files generated by blastx or blastn (-outfmt 0).

    Input:
        - TXT: Text file containing all the alignments generated by blast.
        - VAL_Hits: Blast hit that needs to be extracted from the alignment

    Output:
        - TXT: Text file containing the extracted alignment of the hit
    """

    def __init__(self, camel: Camel) -> None:
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super().__init__('Typing: Alignment Extractor', '0.1', camel)

    def _execute_tool(self) -> None:
        """
        Runs this tool.
        :return: None
        """
        hit = self._tool_inputs['VAL_Hits'][0].value
        if hit.allele_id in (SequenceTypingBlastHit.SYMBOL_MULTI_HIT, SequenceTypingBlastHit.SYMBOL_NO_HIT):
            self._tool_outputs['TXT'] = []
            return
        alignments_file = self._tool_inputs['TXT'][0].path
        key = AlignmentExtraction.get_key(hit.blast_stats.subject_id, hit.blast_stats.query_id)
        alignments = AlignmentExtraction.get_alignments(alignments_file)
        if key in alignments:
            self._tool_outputs['TXT'] = [ToolIOFile(self.__save_alignment(
                f'{hit.locus}_{hit.allele_id}', alignments[key]))]
        else:
            raise ToolExecutionError("No alignment found for: '{}'".format(key))

    def _check_input(self) -> None:
        """
        Checks if the required inputs are specified.
        :return: None
        """
        if 'TXT' not in self._tool_inputs:
            raise InvalidInputSpecificationError("No TXT input found.")
        if 'VAL_Hits' not in self._tool_inputs:
            raise InvalidInputSpecificationError("No typing hits input found")
        if len(self._tool_inputs['TXT']) != 1 or len(self._tool_inputs['VAL_Hits']) != 1:
            raise InvalidInputSpecificationError("Can only extract one alignment")
        super(AlignmentExtractor, self)._check_input()

    def __save_alignment(self, allele_name: str, alignment: str) -> str:
        """
        Saves the given alignment.
        :param allele_name: Allele name
        :param alignment: Alignment
        :return: Filename of the saved alignment
        """
        filename = os.path.join(self._folder, '{}.txt'.format(FileSystemHelper.make_valid(allele_name)))
        with open(filename, 'w') as output_handle:
            output_handle.write(alignment)
        return filename
