from pathlib import Path

from camelcore.app.io.tooliofile import ToolIOFile
from camelcore.app.utils import fileutils

from camel.app.core.errors import InvalidToolInputError, ToolExecutionError
from camel.app.core.tool import Tool
from camel.app.toolkits.blast.alignmentextraction import AlignmentExtraction
from camel.app.toolkits.sequencetyping.sequencetypingutils import SYMBOL_ALLELE_MISSING
from camel.app.toolkits.sequencetyping.typingblasthit import TypingBlastHit


class AlignmentExtractor(Tool):
    """
    Tool that extracts alignments from TXT files generated by blastx or blastn (-outfmt 0).

    Input:
        - TXT: Text file containing all the alignments generated by blast.
        - VAL_Hits: Blast hit that needs to be extracted from the alignment

    Output:
        - TXT: Text file containing the extracted alignment of the hit
    """

    def __init__(self) -> None:
        """
        Initializes this tool.
        """
        super().__init__('Typing: Alignment Extractor', '0.1')

    def _execute_tool(self) -> None:
        """
        Runs this tool.
        :return: None
        """
        hit = self._tool_inputs['VAL_Hits'][0].value
        if hit.allele_id in {SYMBOL_ALLELE_MISSING, TypingBlastHit.SYMBOL_MULTI_HIT}:
            self._tool_outputs['TXT'] = []
            return
        alignments_file = self._tool_inputs['TXT'][0].path
        key = AlignmentExtraction.get_key(hit.blast_stats.subject_id, hit.blast_stats.query_id)
        alignments = AlignmentExtraction.get_alignments(alignments_file)
        if key in alignments:
            self._tool_outputs['TXT'] = [ToolIOFile(self.__save_alignment(
                f'{hit.locus}_{hit.allele_id}', alignments[key]))]
        else:
            raise ToolExecutionError(self.name, f"No alignment found for: '{key}'")

    def _check_input(self) -> None:
        """
        Checks if the required inputs are specified.
        :return: None
        """
        if 'TXT' not in self._tool_inputs:
            raise InvalidToolInputError("No TXT input found.")
        if 'VAL_Hits' not in self._tool_inputs:
            raise InvalidToolInputError("No typing hits input found")
        if len(self._tool_inputs['TXT']) != 1 or len(self._tool_inputs['VAL_Hits']) != 1:
            raise InvalidToolInputError("Can only extract one alignment")
        super()._check_input()

    def __save_alignment(self, allele_name: str, alignment: str) -> Path:
        """
        Saves the given alignment.
        :param allele_name: Allele name
        :param alignment: Alignment
        :return: Filename of the saved alignment
        """
        path_out = self._folder / f'{fileutils.make_valid(allele_name)}.txt'
        with path_out.open('w') as output_handle:
            output_handle.write(alignment)
        return path_out
