from pathlib import Path
from typing import List, Dict, Any

from camel.app.camel import Camel
from camel.app.components.blast.blasthitstatistics import BlastHitStatistics
from camel.app.components.blasttyping.blasthitfilteringhelper import BlastHitFilteringHelper
from camel.app.components.sequencetyping.sequencetypingblasthit import SequenceTypingBlastHit
from camel.app.components.sequencetyping.sequencetypingutils import SequenceTypingUtils
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.io.tooliovalue import ToolIOValue
from camel.app.loggers import logger
from camel.app.tools.tool import Tool


class BestHitSelector(Tool):
    """
    This tool selects the best hit from a tabular blast output.

    Input:
        TSV: Tabular file generated by Blastn with the following outfmt option: '7 pident sseqid sseq slen qseqid qstart
             qend'
    Output:
        VAL_Hit: The best hit.
    """

    def __init__(self, camel: Camel) -> None:
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super().__init__('Typing: Best Hit Selector', '0.1', camel)

    def _check_input(self) -> None:
        """
        Checks if the provided input is valid.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("TSV input is required")
        if len(self._tool_inputs['TSV']) != 1:
            raise InvalidInputSpecificationError("Only 1 TSV input can be processed")
        super()._check_input()

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        metadata = self._input_informs['locus']
        hits = self.__parse_blast_output(self._tool_inputs['TSV'][0].path, metadata)
        hits = BlastHitFilteringHelper.filter_percent_identity(hits, float(
            self._parameters['min_percent_identity'].value))
        hits = BlastHitFilteringHelper.filter_coverage(hits, float(self._parameters['min_percent_covered'].value))
        detected_hit = self.__get_detected_hit(hits, metadata)
        self._tool_outputs['VAL_Hit'] = [ToolIOValue(detected_hit)]

    @staticmethod
    def __parse_blast_output(path_blast_output: Path, metadata_locus: Dict[str, str]) -> \
            List[SequenceTypingBlastHit]:
        """
        Parses the output generated by blast.
        :param path_blast_output: BLAST output path
        :param metadata_locus: Dictionary with metadata of the locus
        :return: Blast hits
        """
        blast_hit_stats = BlastHitStatistics.parse_blast_output(path_blast_output)
        hits = []
        for stats in blast_hit_stats:
            allele_id = SequenceTypingUtils.get_allele_id(stats.subject_id, metadata_locus['allele_id_regex'])
            hits.append(SequenceTypingBlastHit(metadata_locus['name'], allele_id, metadata_locus['type'], stats))
        return hits

    @staticmethod
    def __get_detected_hit(hits: List[SequenceTypingBlastHit], metadata_locus: Dict[str, Any]) -> \
            SequenceTypingBlastHit:
        """
        Returns the detected hit.
        :param hits: Input BLAST typing hits
        :param metadata_locus: Locus metadata
        :return: Detected hit
        """
        if len(hits) == 0:
            logger.info("No hit passed filtering")
            return SequenceTypingBlastHit.create_empty_hit(metadata_locus['name'], metadata_locus['type'])
        else:
            best_hits = BlastHitFilteringHelper.detect_best_hits(hits)
            if len(best_hits) == 1:
                return best_hits[0]
            elif len(best_hits) > 1:
                return SequenceTypingBlastHit.create_multi_hit(
                    metadata_locus['name'], metadata_locus['type'], best_hits[0].blast_stats)
            else:
                return SequenceTypingBlastHit.create_empty_hit(metadata_locus['name'], metadata_locus['type'])
