import logging
from typing import List, Dict

from camel.app.components.blast.blastformat7parser import BlastFormat7Parser
from camel.app.components.blasttyping.blasthitfilteringhelper import BlastHitFilteringHelper
from camel.app.components.sequencetyping.sequencetypingblasthit import SequenceTypingBlastHit
from camel.app.components.sequencetyping.sequencetypingutils import SequenceTypingUtils
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.io.tooliovalue import ToolIOValue
from camel.app.tools.tool import Tool


class BestHitSelector(Tool):
    """
    This tool selects the best hit from a tabular blast output.
    The blast output needs to be generated with the following outfmt option:


    Input:
        TSV: Tabular file generated by Blastn with the following outfmt option: '7 pident sseqid sseq slen qseqid qstart
             qend'
    Output:
        VAL_Hit: The best hit.
    """

    def __init__(self, camel):
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super().__init__('Typing: Best Hit Selector', '0.1', camel)

    def _check_input(self) -> None:
        """
        Checks if the provided input is valid.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("TSV input is required")
        if len(self._tool_inputs['TSV']) != 1:
            raise InvalidInputSpecificationError("Only 1 TSV input can be processed")
        super()._check_input()

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        metadata = self._input_informs['locus']
        hits = self.__parse_blast_output(metadata)
        hits = BlastHitFilteringHelper.filter_percent_identity(hits, float(
            self._parameters['min_percent_identity'].value))
        hits = BlastHitFilteringHelper.filter_coverage(hits, float(self._parameters['min_percent_covered'].value))
        detected_allele = self.__get_detected_allele(hits, metadata)
        detected_allele.locus = metadata.get('name')
        self._tool_outputs['VAL_Hit'] = [ToolIOValue(detected_allele)]

    def __parse_blast_output(self, metadata: Dict[str, str]) -> List[SequenceTypingBlastHit]:
        """
        Parses the output generated by blast.
        :return: Blast hits
        """
        blast_output_data = BlastFormat7Parser.parse_output_file(self._tool_inputs['TSV'][0].path)
        hits = [SequenceTypingBlastHit.create_from_dict(output_dict, metadata.get('type')) for output_dict in
                blast_output_data]
        logging.info("{} hits parsed".format(len(hits)))
        return hits

    def __get_detected_allele(self, hits: List[SequenceTypingBlastHit], metadata: Dict[str, str]) \
            -> SequenceTypingBlastHit:
        """
        Returns the detected allele.
        :param hits: Input hits
        :param metadata: Locus metadata
        :return: Detected allele
        """
        if len(hits) == 0:
            logging.info("No hit passed filtering")
            detected_allele = SequenceTypingBlastHit.generate_empty_hit(
                metadata.get('name'), self._input_informs['locus']['type'])
        else:
            detected_allele = self.__select_best_hit(hits, metadata.get('name'), metadata.get('type'))
        if detected_allele.allele_id not in ('?', '-'):
            detected_allele.allele_id = SequenceTypingUtils.get_allele_id(
                detected_allele.subject, self._input_informs['locus']['allele_id_regex'])
            # detected_allele.set_allele_page_url_template(self._input_informs['locus'].get('allele_page_url'))
            detected_allele.set_allele_page_url_template("http://bigsdb.pasteur.fr/perl/bigsdb/bigsdb.pl?db=pubmlst_listeria_seqdef_public&page=alleleInfo&locus={}&allele_id={}")
        return detected_allele

    @staticmethod
    def __select_best_hit(hits: List[SequenceTypingBlastHit], locus_name: str, locus_type: str) \
            -> SequenceTypingBlastHit:
        """
        Selects the best allele from a set of hits.
        :param hits: Hits
        :param locus_name: Name of the locus
        :param locus_type: Type of locus
        :return: Best hit(s)
        """
        best_hits = BlastHitFilteringHelper.detect_best_hits(hits)
        if len(best_hits) == 1:
            return best_hits[0]
        elif len(best_hits) > 1:
            return SequenceTypingBlastHit.generate_multi_hit(locus_name, locus_type)
        else:
            return SequenceTypingBlastHit.generate_empty_hit(locus_name, locus_type)
