import logging
from typing import List

import os

from camel.app.camel import Camel
from camel.app.components.blast.blasthitstatistics import BlastHitStatistics
from camel.app.components.blasttyping.blasthitfilteringhelper import BlastHitFilteringHelper
from camel.app.components.genedetection.genedetectionblasthit import GeneDetectionBlastHit
from camel.app.components.genedetection.genedetectionutils import GeneDetectionUtils
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.error.toolexecutionerror import ToolExecutionError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.io.tooliovalue import ToolIOValue
from camel.app.tools.tool import Tool


class BlastHitFiltering(Tool):
    """
    Class that filters blast hits and reports the best hits. Perfect hits are always reported. The best hits are
    selected from groups of overlapping hits.

    Input:
        TSV: Tabular file generated by Blastn with '7 pident sseqid sseq slen qseqid qstart qend' as output format.
        INFORMS db_info: Information from the database manager. The metadata for the detected hits is extracted from
            this dictionary.

    Output:
        TSV: Tabular output file with the best hits and some statistics.
        VAL_Hits: A list with the detected hit objects.

    Important parameters:
    - extra_column_key & extra_column_name: If set, an extra metadata column is added to the detected hits. The key
      needs to match the key in the metadata dictionary.
    - filtering_method: Determines how the hits are filters. There are two options supported:
        * 'cluster' (default): The best hit for each cluster is reported.
        * 'score': The n best hits according to hit score are reported (controlled by the 'score_limit' parameter).
    """

    def __init__(self, camel: Camel) -> None:
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super().__init__('Gene Detection: Hit Filtering', '0.1', camel)

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        hits = self.__parse_tabular_blast_output(self._tool_inputs['TSV'][0].path)
        filtered_hits = self.__filter_hits(hits)
        self.__set_output(filtered_hits)

    def _check_input(self) -> None:
        """
        Checks whether the input is correct.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("No 'TSV' input found.")
        if 'db_info' not in self._input_informs:
            raise InvalidInputSpecificationError("No database informs found")
        super(BlastHitFiltering, self)._check_input()

    def __parse_tabular_blast_output(self, tsv_file: str) -> List[GeneDetectionBlastHit]:
        """
        Parses the tabular input file.
        :param tsv_file: TSV input file
        :return: Parsed BLAST hits per cluster
        """
        mapping = self._input_informs['db_info']['mapping']
        hits = []
        for stats in BlastHitStatistics.parse_blast_output(tsv_file):
            # Parse BLAST output
            seq_id = stats.subject_id.split('__')[2]
            hit = GeneDetectionBlastHit(
                mapping.get_metadata(seq_id, 'allele'),
                mapping.get_metadata(seq_id, 'accession'),
                stats
            )
            # Add metadata (when specified)
            if ('extra_column_key' in self._parameters) and ('extra_column_name' in self._parameters):
                metadata_value = mapping.get_metadata(seq_id, self._parameters['extra_column_key'].value)
                hit.add_metadata(self._parameters['extra_column_name'].value, metadata_value)
            hits.append(hit)

        logging.info(f"{len(hits)} hits parsed")
        return hits

    def __filter_hits(self, hits: List[GeneDetectionBlastHit]) -> List[GeneDetectionBlastHit]:
        """
        Filters hits based on the given tool parameters.
        :param hits: Input BLAST hits
        :return: List of filtered BLAST hits
        """
        hits = BlastHitFilteringHelper.filter_percent_identity(hits, float(
            self._parameters['min_percent_identity'].value))
        hits = BlastHitFilteringHelper.filter_coverage(hits, float(self._parameters['min_coverage'].value))
        logging.info("Filtering method: '{}'".format(self._parameters['filtering_method'].value))

        # Report best hit(s) for each database cluster
        if self._parameters['filtering_method'].value == 'cluster':
            hits = BlastHitFiltering.__get_best_hit_per_cluster(hits)
            hits.sort(key=lambda h: (h.locus, h.blast_stats.query_start))

        # Report best N hits based on BLAST score
        elif self._parameters['filtering_method'].value == 'score':
            if 'score_nb_of_hits' not in self._parameters:
                raise ToolExecutionError("'score_nb_of_hits' needs to be set when the filtering method is 'score'")
            hits = hits[:int(self._parameters['score_nb_of_hits'].value)]
        return hits

    def __set_output(self, hits: List[GeneDetectionBlastHit]) -> None:
        """
        Sets the output of this tool.
        :param hits: Detected hits
        :return: None
        """
        self._tool_outputs['VAL_Hits'] = [ToolIOValue(hit) for hit in hits]
        output_path = os.path.join(self._folder, self._parameters['output_filename'].value)
        GeneDetectionUtils.export_hits_tabular(hits, output_path)
        self._tool_outputs['TSV'] = [ToolIOFile(output_path)]

    @staticmethod
    def __get_best_hit_per_cluster(hits: List[GeneDetectionBlastHit]) -> List[GeneDetectionBlastHit]:
        """
        Returns the best hit for each cluster.
        :param hits: All hits
        :return: Best matching hits
        """
        hits_per_cluster = {}
        for hit in hits:
            cluster = hit.blast_stats.subject_id.split('__')[1]
            if cluster not in hits_per_cluster:
                hits_per_cluster[cluster] = []
            hits_per_cluster[cluster].append(hit)
        logging.debug('{} cluster(s) with hits'.format(len(hits_per_cluster)))

        reported_hits = []
        for _, hits in hits_per_cluster.items():
            selected_hits = BlastHitFilteringHelper.detect_best_hits(hits)
            reported_hits.extend(selected_hits)
        return reported_hits
