import logging
from typing import List

import os

from camel.app.camel import Camel
from camel.app.components.genedetection.genedetectionsrst2hit import GeneDetectionSRST2Hit
from camel.app.components.genedetection.genedetectionutils import GeneDetectionUtils
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.io.tooliovalue import ToolIOValue
from camel.app.tools.tool import Tool


class SRST2HitExtractor(Tool):
    """
    This tool extracts hits from SRST2 output.

    INPUT:
        - TSV: SRST2 output file
        - mapping: Mapping of sequence ids to the original headers
        - db_info: Database information

    OUTPUT:
        - TSV: Tabular output file with the hits
        - VAL_Hits: List os SRST2 Hit objects
    """

    def __init__(self, camel: Camel) -> None:
        """
        Initializes this tool.
        :param camel: CAMEL instance
        """
        super().__init__('Gene Detection: SRST2 Hit Extractor', '0.1', camel)

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        hits = self.__parse_srst2_output(self._tool_inputs['TSV'][0].path) if len(self._tool_inputs['TSV']) > 0 else []
        output_path = os.path.join(self._folder, self._parameters['output_filename'].value)
        GeneDetectionUtils.export_hits_tabular(hits, output_path)
        self._tool_outputs['TSV'] = [ToolIOFile(output_path)]
        self._tool_outputs['VAL_Hits'] = sorted([ToolIOValue(h) for h in hits], key=lambda v: v.value.locus)

    def _check_input(self) -> None:
        """
        Checks if the provided input is valid.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("TSV input is required")
        if 'db' not in self._input_informs:
            raise InvalidInputSpecificationError("Database information is required")
        super()._check_input()

    def __parse_srst2_output(self, output_file: str) -> List[GeneDetectionSRST2Hit]:
        """
        Parses the output file generated by SRST2.
        :param output_file: Output file
        :return: Parsed gene detection hits
        """
        mapping = self._input_informs['db']['mapping']
        hits = []
        with open(output_file) as handle:
            header_indices = {k: i for i, k in enumerate(handle.readline().strip().split('\t'))}
            for parts in [l.strip().split('\t') for l in handle.readlines()]:
                # Create hit object
                seq_id = parts[header_indices['allele']]
                hits.append(GeneDetectionSRST2Hit(
                    mapping.get_metadata(seq_id, 'allele'),
                    mapping.get_metadata(seq_id, 'accession', '-'),
                    int(parts[header_indices['length']]),
                    parts[header_indices['diffs']],
                    parts[header_indices['uncertainty']],
                    float(parts[header_indices['coverage']]),
                    float(parts[header_indices['divergence']]),
                    float(parts[header_indices['depth']])
                ))

                # Add metadata (when specified)
                if ('extra_column_key' in self._parameters) and ('extra_column_name' in self._parameters):
                    metadata_value = mapping.get_metadata(seq_id, self._parameters['extra_column_key'].value)
                    hits[-1].add_metadata(self._parameters['extra_column_name'].value, metadata_value)
        logging.info(f"{len(hits)} hits parsed")
        return hits
