####################
# Pipeline options #
####################
citations:
  main: Bogaerts_2019-neisseria_validation
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Danecek_2021-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Feldgarden_2019-ndaro
    - Bortolaia_2020-resfinder_4.0
    - Jolley_2010-bigsdb
    - Muzzi_2019-gmats
    - Marjuki_2019-neisseria_serogroup
    - Bratcher_2014-neisseria_cgmlst

#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 2_157_444

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Neisseria meningitidis

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: 51.5

quast:
  ref:
    fasta: /db/refgenomes/Neisseria_meningitidis/NZ_CP021520.1.fasta
    gff3: /db/refgenomes/Neisseria_meningitidis/NZ_CP021520.1.gff3

srst2:
  max_unaligned_overlap: 141

assembly:
  spades:
    cov_cutoff: 'off'
  min_contig_length: 0

variant_calling:
  ploidy: 1
  report_include_bam: {export_bam}
  reference:
    path: /db/refgenomes/Neisseria_meningitidis/NZ_CP021520.1.fasta
    name: <i>Neisseria meningitidis</i> (NZ_CP021520.1)
    url: https://www.ncbi.nlm.nih.gov/nuccore/NZ_CP021520.1

confindr:
  db: /db/confindr/0.8.1

gmats:
  db: /db/pipelines/neisseria/gMATS_DB.txt

mendevar:
  db: /db/pipelines/neisseria/mendevar_DB.txt

amrfinder:
  db: /db/amrfinder/by_version/latest
  organism: Neisseria_meningitidis

resfinder4:
  db: /db/resfinder4
  point: False

###################
# Sequence typing #
###################
sequence_typing:
  bast:
    path: /db/sequence_typing/neisseria/bast
  cgmlst:
    path: /db/sequence_typing/neisseria/cgmlst
    detection_method: blast
  feta:
    path: /db/sequence_typing/neisseria/feta
  fhbp:
    path: /db/sequence_typing/neisseria/fhbp
  mlst:
    path: /db/sequence_typing/neisseria/mlst
  pora:
    path: /db/sequence_typing/neisseria/pora
  porb:
    path: /db/sequence_typing/neisseria/porb
  resistance_genes:
    path: /db/sequence_typing/neisseria/resistance_genes
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info
  rplf:
    path: /db/sequence_typing/neisseria/rplf
  serogroup_a:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_a
  serogroup_b:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_b
  serogroup_c:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_c
  serogroup_e:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_e
  serogroup_h:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_h
  serogroup_l:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_l
  serogroup_w:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_w
  serogroup_x:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_x
  serogroup_y:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_y
  serogroup_z:
    path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_z
  vaccine_targets:
    path: /db/sequence_typing/neisseria/vaccine_targets
