import logging
from typing import Callable

import vcf
from vcf import model
from vcf.utils import trim_common_suffix

from camel.app.camel import Camel
from camel.app.components.blasthit.indel import Indel
from camel.app.components.vcf.vcfutils import VCFUtils
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.tools.tool import Tool


class VCFIndelScanner(Tool):
    """
    Class to scan through VCF files to extract all indels.

    Inputs:
    -----------------------
    - VCF: file contain variants detected

    Output Informs:
    -----------------------
    - indels: indel grouped by chromosome
    - vcf_tool: tool that generated input VCF
    """
    # TODO: multiple possible variances at one site, now warning in log
    # TODO: complex variance that could not be handled by consensus sequence generation method

    def __init__(self, camel: Camel) -> None:
        """
        Initialize tool
        :param camel: Camel instance
        :return: none
        """
        super().__init__('Influenza: VCFIndelScanner', '0.1', camel)
        self.indels = []
        self.vcf_tool = None

    def _execute_tool(self) -> None:
        """
        Function to run VCFIndelScanner
        :return: none
        """
        self.vcf_tool = self._identify_vcf_generation_tool()
        self.indels = VCFUtils.retrieve_variants(self._tool_inputs['VCF'][0].path, types=[VCFUtils.INDEL])
        self._set_output()

    def _check_input(self) -> None:
        """
        Check the required input
        """
        if 'VCF' not in self._tool_inputs:
            raise InvalidInputSpecificationError(
                f"VCFIndelScanner required 'VCF' file is missing from tool_inputs: {self._tool_inputs}")

        super()._check_input()

    def _identify_vcf_generation_tool(self) -> str:
        """
        Identify the tool that generates input VCF file from metadata
        :return: the name of the tool
        """
        gatk_callers = ['GATKCommandLine.HaplotypeCaller', 'GATKCommandLine.UnifiedGenotyper',
                        'GATKCommandLine.MuTect2', 'GATKCommandLine']

        vcf_reader = vcf.Reader(filename=str(self._tool_inputs['VCF'][0].path))

        logger.debug(f" VCF metadata: keys {vcf_reader.metadata.keys()} \n data {vcf_reader.metadata}")

        if 'bcftools_callCommand' in vcf_reader.metadata.keys():
            return 'samtools'

        if any(x in vcf_reader.metadata.keys() for x in gatk_callers):
            return 'gatk'

        if 'source' in vcf_reader.metadata.keys() and vcf_reader.metadata['source'][0].lower().find('freebayes') == 0:
            return 'freebayes'

        raise TypeError('Input VCF file is generated by unsupported tool. Supported tools: samtools, gatk, freebayes.')

    def _set_output(self) -> None:
        """
        Set the output specification
        :return: none
        """
        if self.vcf_tool in {'samtools', 'freebayes'}:
            self._gather_indels_by_chrom(self._convert_samtool_indel_into_tuple)
        elif self.vcf_tool == 'gatk':
            self._gather_indels_by_chrom(self._convert_indel_into_tuple)
        self._informs['vcf_tool'] = self.vcf_tool

    def _gather_indels_by_chrom(self, indel_converter: Callable) -> None:
        """
        Gather indels grouped by chromosome information.
        :param indel_converter: function to convert PyVCF indel record into our Indel Object
        :return: None
        """
        self._informs['indels'] = {}
        for x in self.indels:
            indel = indel_converter(x)
            if x.CHROM in self._informs['indels']:
                self._informs['indels'][x.CHROM].append(indel)
            else:
                self._informs['indels'][x.CHROM] = [indel]

    def _convert_samtool_indel_into_tuple(self, indel: vcf.model._Record) -> Indel:
        """
        Covert a samtools indel into Indel object
        :param indel: a samtools indel of vcf record object
        :return: Indel object
        """
        str_indel_before = str(indel)
        simplified_indel = self._simplify_samtools_indel(indel)
        str_indel_simplified = str(simplified_indel)
        if str_indel_before != str_indel_simplified:
            logger.debug("  samtools indels - before \t{!r}".format(str_indel_before))
            logger.debug("  samtools indels - simplified \t{!r}".format(str_indel_simplified))
        return self._convert_indel_into_tuple(simplified_indel)

    def _convert_indel_into_tuple(self, indel: vcf.model._Record) -> Indel:
        """
        Covert an indel into Indel object
        :param indel: an indel of vcf record type
        :return: Indel object
        """
        # PyVCF NOTE:
        # - Coordinate: http://genomewiki.ucsc.edu/index.php/Coordinate_Transforms
        #
        # GATK NOTE:
        # - GATK handles all simple indels of unlimited size
        # - GATK does not handle any complex substitution
        # - http://gatkforums.broadinstitute.org/gatk/discussion/5627/fastaalternatereferencemaker-indel-limitations
        #
        # GATK VCF record:
        #
        # - INSERTION
        #   * Record(CHROM=gi|16763390|ref|NC_003197.1|, POS=116394, REF=T, ALT=[TATAACGGGAAAG])
        #   * .var_type, .var_subtype, .start, .affected_start, .end, .affected_end
        #     ('indel', 'ins', 116393, 116394, 116394, 116394)
        #
        # - DELETION:
        #   * Record(CHROM=gi|16763390|ref|NC_003197.1|, POS=19756, REF=CACGCCGGCTGAGGATGAT, ALT=[C])
        #   * .var_type, .var_subtype, .start, .affected_start, .end, .affected_end
        #     ('indel', 'del', 19755, 19756, 19774, 19774)
        #
        if len(indel.ALT) > 1:
            logger.warning("INDEL with multiple alternative alleles found: type {!r}, {!r}".format(
                indel.var_subtype, str(indel)))

        if indel.is_deletion:
            indel_type = '-'
            indel_length = len(indel.REF) - 1
        else:
            indel_type = '+'
            indel_length = len(indel.ALT[0]) - 1
        # Note: there is -1 adjustment for start base preceeding INDEL which is always included in REF for 'del' or
        #       in ALT for 'ins'.

        # 1 base adjustment for start position, as PyVCF use 0-based coordinates (same as python list), while 1-based
        # one is adopted by us (following VCF specification)
        indel_start = indel.start + 1

        return Indel(indel_type, indel_start, indel_length)

    @staticmethod
    def _simplify_samtools_indel(indel: vcf.model._Record) -> vcf.model._Record:
        """
        Simplify a samtools indel by removing the flanking sequences and updating the coordinates
        :param indel: a samtools indel of vcf record object
        :return: updated indel of vcf record object
        """
        # samtools VCF records (from samtools own dummy example)
        #
        # - Except for the ref base where a indel starts (same as GATK), samtools indel always has TAIL BASES in both
        #   REF and ALT, need to be removed (by trim_common_suffix from vcf.utils of PyVCF package)
        #
        # - DELETION:
        #   * Record(CHROM=gi|16763390|ref|NC_003197.1|, POS=1781866, REF=TTTCCGCTTCCGCTTCC, ALT=[TTTCCGCTTCC])
        #   * tail: TTCCGCTTCC
        #   * trimmed_ref, trimmed_alt = 'TTTCCGC', 'T'
        #
        # - INSERTION:
        #   * Record(CHROM=gi|16763390|ref|NC_003197.1|, POS=4279957, REF=TGTGG, ALT=[TGCTGTGGTGG])
        #   * tail: GTGG
        #   * trimmed_ref, trimmed_alt = 'T', 'TGCTGTG'
        #
        trimmed_ref, trimmed_alt = trim_common_suffix(str(indel.REF), str(indel.ALT[0]))
        indel.REF = trimmed_ref
        indel.ALT[0] = vcf.model._Substitution(trimmed_alt)
        return indel
