from camel.app.core.io.tooliofile import ToolIOFile
from camel.app.core.tool import Tool


class VCFtools(Tool):
    """
    =============================
    VCFtools 1.16
    =============================
    VCFtools is a program package designed for working with VCF files, such as those generated by the 1000 Genomes Project.
    The aim of VCFtools is to provide easily accessible methods for working with complex genetic variation data in the
    form of VCF files


    Required inputs:
    ----------------
    'VCF'|'VCF_GZ':         ToolIOFile object. File in VCF|bg-zipped VCF format

    Output:
    -------
    'VCF_GZ':               ToolIOFile object. Processed file in bg-zipped VCF format
    """

    def _execute_tool(self) -> None:
        """
        Run a vcftools function
        :return: None
        """
        self._build_command()
        self._execute_command()
        self._set_output()

    def _set_output(self) -> None:
        """
        Set output of vcftools function
        :return: None
        """
        self._tool_outputs['VCF_GZ'] = [ToolIOFile(self.folder / self._parameters['output'].value)]

    def _build_command(self) -> None:
        """
        Build command of vcftools function
        :return: None
        """
        raise NotImplementedError("Method should be implemented by subclass.")
