import json
import logging
import re
from pathlib import Path
from typing import Tuple, Dict, Any, List

from Bio import SeqIO


class LocusMetadataHolder:
    """
    This holder class is used to avoid cluttering the log with huge metadata dictionaries.
    """

    def __init__(self, locus_metadata: List[Dict[str, Any]]) -> None:
        """
        Initializes the metadata holder.
        :param locus_metadata: Locus metadata
        """
        self.metadata_by_locus_name = {locus['name_valid']: locus for locus in locus_metadata}

    def __repr__(self) -> str:
        """
        Returns the internal representation.
        :return: Representation
        """
        return f'{self.__class__.__name__}({len(self.metadata_by_locus_name)} items)'


class SequenceTypingUtils(object):
    """
    This class contains utility functions for sequence typing.
    """

    @staticmethod
    def determine_delimiter(fasta_file: Path) -> str:
        """
        Returns the delimiter that is used in the FASTA file. Supported delimiters are '-' and '_'.
        :param fasta_file: FASTA file
        :return: None
        """
        with fasta_file.open() as handle:
            for seq in SeqIO.parse(handle, 'fasta'):
                m = re.match('.*([-_])\\d+$', seq.id)
                if m is None:
                    raise ValueError("Cannot determine allele delimiter")
                delimiter = m.group(1)
                logging.info("Detected delimited: '{}'".format(delimiter))
                return delimiter

    @staticmethod
    def get_allele_id(complete_name: str, regex: str = None) -> str:
        """
        Returns the allele id from a complete name.
        :param complete_name: Complete name (e.g. abcZ_2)
        :param regex: Allele id regex (e.g. '\\d+$')
        :return: Allele id
        """
        if regex is None:
            regex = '\\d+$'
        m = re.findall(regex, complete_name)
        if not len(m) == 1:
            raise ValueError("Cannot determine allele identifier for '{}' (RE: {})".format(complete_name, regex))
        return m[0]

    @staticmethod
    def determine_read_status(path_fq: Path) -> Tuple[str, str]:
        """
        Attempts to determine the forward / reverse state designator of the reads based on the filename.
        This is useful for SRST2 which can have problems with uncommon read names.
        Supported formats: read_1P.fastq, read_1.fastq
        :param path_fq: Path to input FASTQ file
        :return: Forward designator, reverse designator
        """
        if re.match('.*(_[12]P\\.).*', path_fq.name) is not None:
            return '1P', '2P'
        elif re.match('.*(_[12]\\.).*', path_fq.name) is not None:
            return '_1', '_2'
        raise ValueError(f"Cannot determine read name from: {path_fq}")

    @staticmethod
    def parse_summary_output(input_file: str) -> Dict[str, int]:
        """
        Parses the summary output generated by sequence typing and returns the number of hits of each type.
        :param input_file: Input file
        :return: Summary information
        """
        result_dict = {x: 0 for x in ['multi', 'no_allele', 'p_ident', 'length', 'found']}
        with open(input_file) as handle:
            for line in handle.readlines()[1:]:
                parts = line.strip().split('\t')
                if parts[1] == '?':
                    result_dict['multi'] += 1
                    continue
                if parts[1] == '-':
                    result_dict['no_allele'] += 1
                    continue
                if parts[2] != '100.00':
                    result_dict['p_ident'] += 1
                    continue
                l1, l2 = parts[3].split('/')
                if l1 != l2:
                    result_dict['length'] += 1
                else:
                    result_dict['found'] += 1
        return result_dict

    @staticmethod
    def parse_scheme_metadata(scheme_dir: Path) -> Dict[str, Any]:
        """
        Parses the metadata associated with the given scheme.
        :param scheme_dir: Scheme directory
        :return: Metadata
        """
        with (scheme_dir / 'scheme_metadata.txt').open() as handle:
            return json.load(handle)

    @staticmethod
    def has_profiles(scheme_data: Dict[str, Dict[str, Any]], scheme_key: str) -> bool:
        """
        Returns True if the scheme has profiles.
        :param scheme_data: Dictionary of all scheme data
        :param scheme_key: Scheme
        :return: True if the scheme has profiles file
        """
        folder = Path(scheme_data[scheme_key]['path'])
        return (folder / 'profiles.tsv').is_file()

    @staticmethod
    def get_detection_method(config_data: Dict[str, Any], scheme_key: str) -> str:
        """
        Returns the detection method for the given scheme.
        :return: Detection method
        """
        pipeline_setting = config_data['detection_method']
        return config_data['sequence_typing'][scheme_key].get('detection_method', pipeline_setting)
