import json
import logging
from typing import Tuple, Dict, List

import os
import re
from Bio import SeqIO


class SequenceTypingUtils(object):
    """
    This class contains utility functions for sequence typing.
    """

    @staticmethod
    def determine_delimiter(fasta_file):
        """
        Returns the delimiter that is used in the FASTA file. Supported delimiters are '-' and '_'.
        For example a FASTA file with the first entry '>abcZ_2' will return '_' as the delimiter.
        :param fasta_file: FASTA file
        :return: None
        """
        with open(fasta_file) as handle:
            for seq in SeqIO.parse(handle, 'fasta'):
                m = re.match('.*([-_])\d+$', seq.id)
                if m is None:
                    raise ValueError("Cannot determine allele delimiter")
                delimiter = m.group(1)
                logging.info("Detected delimiter: '{}'".format(delimiter))
                return delimiter

    @staticmethod
    def get_allele_id(complete_name: str, regex: str=None) -> str:
        """
        Returns the allele id from a complete name.
        :param complete_name: Complete name (e.g. abcZ_2)
        :param regex: Allele id regex (e.g. '\d+$')
        :return: Allele id
        """
        if regex is None:
            regex = '\d+$'
        m = re.findall(regex, complete_name)
        if not len(m) == 1:
            raise ValueError("Cannot determine allele identifier for '{}' (RE: {})".format(complete_name, regex))
        return m[0]

    @staticmethod
    def determine_read_status(read_name: str) -> Tuple[str, str]:
        """
        Attempts to determine the forward / reverse state designator of the reads based on the filename.
        This is useful for SRST2 which can have problems with uncommon read names.
        Supported formats: read_1P.fastq, read_1.fastq
        :param read_name: Input read name
        :return: Forward designator, reverse designator
        """
        if re.match('.*(_[12]P\.).*', read_name) is not None:
            return '1P', '2P'
        elif re.match('.*(_[12]\.).*', read_name) is not None:
            return '_1', '_2'
        raise ValueError(f"Cannot determine read name from: {read_name}")

    @staticmethod
    def parse_summary_output(input_file: str) -> Dict[str, int]:
        """
        Parses the summary output generated by sequence typing and returns the number of hits of each type.
        :param input_file: Input file
        :return: Summary information
        """
        result_dict = {x: 0 for x in ['multi', 'no_allele', 'p_ident', 'length', 'found']}
        with open(input_file) as handle:
            for l in handle.readlines()[1:]:
                parts = l.strip().split('\t')
                if parts[1] == '?':
                    result_dict['multi'] += 1
                    continue
                if parts[1] == '-':
                    result_dict['no_allele'] += 1
                    continue
                if parts[2] != '100.00':
                    result_dict['p_ident'] += 1
                    continue
                l1, l2 = parts[3].split('/')
                if l1 != l2:
                    result_dict['length'] += 1
                else:
                    result_dict['found'] += 1
        return result_dict

    @staticmethod
    def get_locus_type(locus_directory: str) -> str:
        """
        Returns the type of locus ('DNA', 'peptide').
        :param locus_directory: Locus directory
        :return: Locus type
        """
        locus_metadata_file = os.path.join(locus_directory, 'locus_metadata.txt')
        with open(locus_metadata_file) as handle:
            try:
                return json.load(handle)['type']
            except KeyError:
                raise ValueError(f"Metadata file does not contain locus type (dir: {locus_directory})")

    @staticmethod
    def get_loci(scheme_dir: str) -> Dict[str, List[str]]:
        """
        Returns the loci from the given database.
        :param scheme_dir: Database folder.
        :return: Loci by type ('DNA', 'peptide')
        """
        loci_by_type = {'DNA': [], 'peptide': []}
        for locus_dir in sorted(os.listdir(scheme_dir)):
            if not os.path.isdir(os.path.join(scheme_dir, locus_dir)) or locus_dir.startswith('.'):
                continue
            locus_type = SequenceTypingUtils.get_locus_type(os.path.join(scheme_dir, locus_dir))
            loci_by_type[locus_type].append(locus_dir)
        return loci_by_type

    @staticmethod
    def has_profiles(all_schemes: Dict[str, str], scheme_key: str) -> bool:
        """
        Returns True if the scheme has profiles.
        :param all_schemes: Dictionary of all schemes
        :param scheme_key: Scheme
        :return: True if the scheme has profiles file
        """
        folder = all_schemes.get(scheme_key)
        return os.path.isfile(os.path.join(folder, 'profiles.tsv'))
