import re
from pathlib import Path

import vcf

from camel.app.command.command import Command
from camel.app.components import toolutils
from camel.app.error import InvalidToolInputError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.loggers import logger
from camel.app.tools.bcftools.bcftoolsview import BcftoolsView
from camel.app.tools.tool import Tool


class Clair3(Tool):
    """
    Clair3 is a germline small variant caller for long-reads.
    """

    def __init__(self) -> None:
        """
        Initializes this tool
        """
        super().__init__('Clair3', '1.0.4')

    def _check_input(self) -> None:
        """
        Checks whether the provided input files are valid
        :return: None
        """
        if 'FASTA' not in self._tool_inputs:
            raise InvalidToolInputError('FASTA reference is required')
        if 'BAM' not in self._tool_inputs:
            raise InvalidToolInputError('BAM alignment file is required')

        input_folder = self._tool_inputs['FASTA'][0].path.parent
        base_fasta_name = self._tool_inputs['FASTA'][0].path.name
        fasta_index_file = [f for f in input_folder.glob(f'{base_fasta_name}.fai')]
        if not (len(fasta_index_file) > 0):
            raise InvalidToolInputError('FASTA reference needs to be indexed')
        super()._check_input()

    def _build_command(self, fasta_input: Path, bam_input: Path) -> None:
        """
        Builds the command to run clair3.
        :return: None
        """
        self._command.command = ' '.join([
            self._tool_command, f'--bam_fn {bam_input}', f'--ref_fn {fasta_input}',
            *self._build_options(delimiter='=',
                                 excluded_parameters=['haploid_precise', 'no_phasing', 'include_ctgs', 'long_indel']),
            *self._build_options(excluded_parameters=['chunk_size', 'model_path', 'platform', 'threads', 'output_path'])
        ])

    def _check_command_output(self, command: Command) -> None:
        """
        Checks command output.
        :return: None
        """
        toolutils.check_tool_execution(self, command, exit_code=0)

    def _set_output(self) -> None:
        """
        Collects the tool output.
        """
        dir_out = self.folder / self._parameters['output_path'].value
        path_out = dir_out / 'merge_output.vcf.gz'
        path_out_fixed = self.__filter_problematic_positions(path_out)
        # Convert back to VCF GZ
        bcftools_view = BcftoolsView()
        bcftools_view.add_input_files({
            'VCF': [ToolIOFile(path_out_fixed)]
        })
        bcftools_view.update_parameters(output_type='z', output_filename='clair3_variants-fixed.vcf.gz')
        bcftools_view.run(self.folder)
        self._tool_outputs['VCF'] = bcftools_view.tool_outputs['VCF_GZ']

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        fasta_input = Path(str(self._tool_inputs['FASTA'][0]))
        bam_input = Path(str(self._tool_inputs['BAM'][0]))
        self._build_command(fasta_input, bam_input)
        self._execute_command()
        self._set_output()

    def __filter_problematic_positions(self, vcf_in: Path) -> Path:
        """
        Filters the problematic positions reported by Clair3.
        The positions have AFs with multiple values (e.g., '0.3636,0.5606')
        :param vcf_in: Input file in VCF format (compressed)
        :return: VCF file with problematic positions removed
        """
        # Convert output VCF.GZ file to VCF format
        path_out_uncompressed = vcf_in.parent / vcf_in.name.replace('.gz', '')
        command = Command(f'module load bcftools/1.17; bcftools view {vcf_in} > {path_out_uncompressed};')
        command.run(self.folder)

        # Attempt to parse the uncompressed VCF
        format_ok = True
        try:
            list(vcf.Reader(filename=str(path_out_uncompressed)))
        except ValueError as err:
            format_ok = False
            logger.warning(f'Could not parse VCF generated by Clair3: {err}')

        # Parsing is OK -> return original file
        if format_ok:
            logger.debug('No problematic positions found in Clair3 output')
            return path_out_uncompressed

        # Parsing is not OK -> remove problematic lines
        lines_out = []
        with open(path_out_uncompressed) as handle:
            for line in handle.readlines():
                # Header lines
                if line.startswith('#'):
                    lines_out.append(line)
                    continue
                parts = line.strip().split('\t')
                m = re.search(r':\d+\.\d+,\d+\.\d+$', parts[-1])
                if not m:
                    lines_out.append(line)
                    continue
                logger.warning(f'Skipping variant at position {parts[1]} - incorrect format')

        # Create the output file
        path_out = vcf_in.parent / vcf_in.name.replace('.vcf', '-fixed.vcf')
        with open(path_out, 'w') as handle:
            handle.write(''.join(lines_out))
        return path_out
