####################
# Pipeline options #
####################

citations:
  other:
    - Bolger_2014-trimmomatic
    #TODO

#########################
# Tool specific options #
#########################

downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 4_762_259

#TODO: read trimming, ..., assembly

############################
# Gene detection databases #
############################

#TODO

###################
# Sequence typing #
###################

sequence_typing:
  cgmlst:
    #TODO: add yersinia to this db
    path: /db/sequence_typing/yersinia/cgmlst
    detection_method: blast