#########################################################################################
# This YAML file contains the additional configuration data for the Influenza pipeline  #
# The values are added to the configuration data constructed by the BasePipeline class. #
#########################################################################################
species:
  name: '{viral_species}'
  subtype: '{subtype}'

read_type: 'illumina'

read_trimming:
  export_fastq: '{export_fastq}'

quality_checks:
  expected_gc_content: 0
  coverage_mode: ref
  disabled_checks: ['typing', 'kraken', 'coverage']

decontamination:
  dbs: {deconseq_dbs}
  sequential: {deconseq_sequential}
  dbs_retain: {deconseq_retain}

analysis_type: {analysis_type}

species_info:
  influenza_A:
    gc_content: 43.66
    type: 'virus'
    name: 'Influenza A'
    seqIDParser_type: 'default'
    genome_segments: 'PB2,PB1,PA,HA,NP,NA,MP,NS'
    genome_size: 13500
    genome_typing_db:
      ncbi: '/db/refgenomes/influenza/ncbi/20201006/influenza_0N_2stdev_clustered_A.fa'
      ecdc: '/db/refgenomes/influenza.A/Cyril_references/cluster_fasta/HANA_dict.fa'
      avian: '/db/refgenomes/influenza.A/Avian/Avian_refs.fasta'

rule_parameters:
  blastn_genometyping:
#    output_format: '"6 qseqid sseqid qstart qend sstart send sstrand evalue bitscore"'
    ungapped: ''
#    qcov_hsp_perc: 85
    percent_identity: {blastn_genometyping_idcutoff}
    output_filename: 'blastn_genome_typing_read_hits.asn'
  mapping:
    bowtie2_mode: [sensitive, end_to_end]
  iterative_mapping:
    bowtie2_mode: [very_sensitive_local, local]
