import re


class BlastnTSVHit(object):
    """
    Class to handle customized blastn tabular output

    Supported blastn outfmt 6 columns:
    'qseqid sseqid pident length mismatch gapopen gaps qstart qend sstart send evalue bitscore strand qcovs qcovhsp'
    """
    # Note that although one would expect that qcovs and qcovhsp is float, in fact, they are reported as integer (as I
    # never see decimal digits reported). Indirectly, another package also think they are integer (see below). A direct
    # proof will need to check the source code.
    #
    # Reference: http://scikit-bio.org/docs/0.4.1/generated/skbio.io.format.blast6.html

    def __init__(self, hit):
        """
        Initialize
        :param hit: the txt string describe hit
        """
        hit_inform = hit.split("\t")
        self.qseqid = hit_inform[0]
        self.sseqid = hit_inform[1]
        self.pident = float(hit_inform[2])
        self.length = int(hit_inform[3])
        self.mismatch = int(hit_inform[4])
        self.gapopen = int(hit_inform[5])
        self.gaps = int(hit_inform[6])
        self.qstart = int(hit_inform[7])
        self.qend = int(hit_inform[8])
        self.sstart = int(hit_inform[9])
        self.send = int(hit_inform[10])
        self.evalue = hit_inform[11]
        self.bitscore = float(hit_inform[12])
        self.strand = hit_inform[13]
        self.qcovs = int(hit_inform[14])
        self.qcovhsp = int(hit_inform[15])
        self._hit_str = hit

    def __str__(self):
        return self._hit_str

    def __repr__(self):
        return str(self)

    def get_hit_id(self):
        """
        Generate a uniq hit id with sstart, send, and sstrand information
        :return: hit id as string
        """
        # Example id: NODE_10_length_1700_cov_25.444118:25-983(-)
        if self.strand == 'minus':
            return self.sseqid + ":" + str(self.sstart) + "-" + str(self.send) + "(-)"
        else:
            return self.sseqid + ":" + str(self.sstart) + "-" + str(self.send) + "(+)"

    @staticmethod
    def get_location_from_hit_id(hit_id):
        """
        Given hit_id generated using above function, return location information
        :param hit_id: blastn hit id generated using self.get_hit_id function
        :return: sstart
        :return: send
        :return: strand
        """
        # Example id: NODE_10_length_1700_cov_25.444118:25-983(-)
        location = hit_id.split(":")[-1]
        m = re.search(r"^(\d+)-(\d+)\(([+-])\)$", location)
        start, end, strand = m.groups()
        start = int(start)
        end = int(end)
        return start, end, strand

    @staticmethod
    def get_location_from_bedtool_seqid(seqid):
        """
        Given seqid generated by Bedtools getfasta function, return location information
        :param seqid: sequence id generated by Bedtools getfasta function
        :return: sstart
        :return: send
        :return: strand
        """
        # Example id: NODE_10_length_1700_cov_25.444118:25-983(-)
        #
        # NOTE that to extract the exact section of matching sequence, start position feed to Bedtools getfasta function
        # has been modified by 1 base (compare to the original blastn hit)
        location = seqid.split(":")[-1]
        m = re.search(r"^(\d+)-(\d+)\(([+-])\)$", location)
        start, end, strand = m.groups()
        start = int(start) + 1
        end = int(end)
        return start, end, strand


class BlastnTSVHitWithSeq(BlastnTSVHit):
    """
    Class to handle customized blastn tabular output with algined sequences

    Supported blastn outfmt 6 columns:
    'qseqid sseqid pident length mismatch gapopen gaps qstart qend sstart send qseq sseq evalue bitscore strand qcovs qcovhsp'
    """

    def __init__(self, hit):
        """
        Initialize
        :param hit: the txt string describe hit
        """
        # Note that due to the position of qseq and sseq in the output, call super is not good here
        hit_inform = hit.split("\t")
        self.qseqid = hit_inform[0]
        self.sseqid = hit_inform[1]
        self.pident = float(hit_inform[2])
        self.length = int(hit_inform[3])
        self.mismatch = int(hit_inform[4])
        self.gapopen = int(hit_inform[5])
        self.gaps = int(hit_inform[6])
        self.qstart = int(hit_inform[7])
        self.qend = int(hit_inform[8])
        self.sstart = int(hit_inform[9])
        self.send = int(hit_inform[10])
        self.qseq = hit_inform[11]
        self.sseq = hit_inform[12]
        self.evalue = hit_inform[13]
        self.bitscore = float(hit_inform[14])
        self.strand = hit_inform[15]
        self.qcovs = int(hit_inform[16])
        self.qcovhsp = int(hit_inform[17])
        self._hit_str = hit
        self._hit_str_without_seqs = "\t".join(
            [self.qseqid, self.sseqid, "{0:0.2f}".format(self.pident), str(self.length), str(self.mismatch),
             str(self.gapopen), str(self.gaps), str(self.qstart), str(self.qend), str(self.sstart), str(self.send),
             self.evalue, str(self.bitscore), self.strand, str(self.qcovs), str(self.qcovhsp)])

    def print_with_seqs(self):
        """
        Print hit information without sequences
        """
        return self._hit_str

    def __str__(self):
        return self._hit_str_without_seqs

    def __repr__(self):
        return str(self)


class BlastnTSVFile(object):
    """
    Class to handle blastn tsv output file
    """
    COLUMNS = "qseqid sseqid pident length mismatch gapopen gaps qstart qend sstart send evalue bitscore strand qcovs qcovhsp".split(
        " ")
    COLUMNS_WITH_SEQS = "qseqid sseqid pident length mismatch gapopen gaps qstart qend sstart send qseq sseq evalue bitscore strand qcovs qcovhsp".split(
        " ")

    def __init__(self, blastn_tsv, with_seq=False):
        """
        Initialize the class
        """
        self.blastn_tsv = blastn_tsv
        self.with_seq = with_seq

    def get_inform_column_names(self):
        """
        Return column names to show the blastn tsv data information (no sequence columns)
        :return: column names as a list
        """
        return self.COLUMNS

    def get_column_names(self):
        """
        Return column names of the blastn tsv data
        :return: column names as a list
        """
        if self.with_seq:
            return self.COLUMNS_WITH_SEQS
        else:
            return self.COLUMNS

    def read_hits(self, key='qseqid'):
        """
        Return hits information as hash
        :return: hits grouped by query
        """
        hits = {}
        with open(self.blastn_tsv, 'r') as hits_file:
            for hit_inform in hits_file.readlines():
                hit = BlastnTSVHitWithSeq(hit_inform) if self.with_seq else BlastnTSVHit(hit_inform)
                seqid = hit.qseqid if key == 'qseqid' else hit.sseqid
                if seqid in hits:
                    hits[seqid].append(hit)
                else:
                    hits[seqid] = [hit]
        return hits

    def read_hits_as_list(self):
        """
        Return hits information in a list
        :return: hits in a list
        """
        hits = []
        with open(self.blastn_tsv, 'r') as hits_file:
            for hit_inform in hits_file.readlines():
                hits.append(BlastnTSVHitWithSeq(hit_inform) if self.with_seq else BlastnTSVHit(hit_inform))
        return hits
