from pathlib import Path

from camel.app.camel import Camel
from camel.app.components.filesystemhelper import FileSystemHelper
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.error.toolexecutionerror import ToolExecutionError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.loggers import logger
from camel.app.tools.tool import Tool


class Bakta(Tool):
    """
    Bakta is a tool for the rapid & standardized annotation of bacterial genomes and plasmids from both isolates and MAGs
    """

    def __init__(self, camel: Camel) -> None:
        """
        Initializes this tool.
        :param camel: Camel instance
        return: None
        """
        super().__init__('Bakta', '1.9.4', camel)

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        # Build the Bakta command and execute it
        self.__build_command()
        self._execute_command()
        # Set the output
        self.__set_output()

    def _check_input(self) -> None:
        """
        Checks the input.
        :return: None
        """
        super()._check_input()
        if 'FASTA' in self._tool_inputs:
            if len(self._tool_inputs['FASTA']) != 1:
                raise InvalidInputSpecificationError("FASTA input requires exactly 1 file.")
        else:
            raise ValueError("FASTA input is required")

    def __build_command(self) -> None:
        """
        Builds the command.
        :return: None
        """
        self._command.command = ' '.join([
            self._tool_command,
            str(self._tool_inputs['FASTA'][0].path),
            *self._build_options()]
        )

    def _check_command_output(self) -> None:
        """
        Checks if the command was executed successfully.
        :return: None
        """
        if 'error' in self.stderr.lower():
            raise ToolExecutionError(f"Command execution failed (stderr: {self.stderr}).")
        if self._command.returncode != 0:
            raise ToolExecutionError(f"Command execution failed (Exit code: {self._command.returncode})")

    def __get_output_path(self, suffix: str) -> Path:
        """
        Returns the path for the output file with the given suffix.
        :param suffix: suffix for the filename
        :return: Path to the generated files
        """
        basename = self._parameters['out'].value
        return self.folder / f"{FileSystemHelper.make_valid(basename)}{suffix}"

    def __set_output(self) -> None:
        """
        Set the output specifications in the Camel ouptut list:
        - faa file
        - gff3 file
        - gbff file
        :return: None
        """
        self._tool_outputs['OUT'] = [ToolIOFile(os.path.join(self._folder, self._parameters['output_file'].value))]

        html_file_name = "{}_summary.html".format(os.path.join(self._folder, self._parameters['output_file'].value))
        self._tool_outputs['HTML'] = [ToolIOFile(html_file_name)]

    def _add_informs(self) -> None:
        """
        Adds the informs.
        :return: None
        """
        if not os.path.isfile(self._tool_outputs['TXT'][0].path):
            raise IOError("No stats file generated by Prokka.")
        with open(self._tool_outputs['TXT'][0].path) as handle:
            for line in handle.readlines():
                key, value = line.split(':')
                self._informs[key] = value.strip()
