#####################
# Pipeline settings #
#####################
citations:
  main: Timmermans_2021-enterococcus
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Bortolaia_2020-resfinder_4.0
    - Feldgarden_2019-ndaro
    - Joensen_2014-virulencefinder
    - Chen_2016-vfdb
    - Carattoli_2020-plasmidfinder
    - Jolley_2010-bigsdb
    - Hyatt_2010-prodigal
    - Pal_2014-bacmet

#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: {genome_size}

read_trimming:
  export_fastq: '{export_fastq}'

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: {k2_name}
  level_of_depth: {k2_level}

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: {gc_content}

quast:
  ref:
    fasta: {quast_fasta}
    gff3: {quast_gff}

confindr:
  db: /db/confindr/0.8.1

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

amrfinder:
  db: /db/amrfinder/by_version/latest
  species: {amrfinder_species}

resfinder4:
  db: /db/resfinder4
  species: {resfinder4_species}
  min_identity: 0.90
  min_cov: 0.60

mob_suite:
  db: /db/mob_suite/latest

bacmet:
  db: /db/bacmet/latest

############################
# Gene detection databases #
############################
gene_detection:
  vfdb_core:
    path: /db/gene_detection/VFDB_core
    perc_identity_cutoff: 90
    metadata:
      name: Gene
      key: gene
    hidden: true

  virulencefinder:
    path: /db/gene_detection/VirulenceFinder-Enterococcus
    metadata:
      name: Protein function
      key: protein_function

  plasmidfinder:
    path: /db/gene_detection/PlasmidFinder-gram_positive
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 60
      srst2:
        max_divergence: 5
        min_coverage: 60
    metadata:
      name: Notes
      key: notes
    message:
      content: The presence of a replicon does not mean that the corresponding plasmid is present.
      category: warning

###################
# Sequence typing #
###################
sequence_typing:
  mlst:
    path: {mlst_db}
  mlst_bezdicek:
    path: '/db/sequence_typing/enterococcus_faecium/mlst_bezdicek'
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info
  cgmlst:
    path: {cgmlst_db}
    detection_method: blast
