# This is used to configure the CAMEL loggers.
# Step handlers can be added by using a name that starts with 'step', pipeline handlers start with 'pipeline'.
# These handlers will create separate log files for each step / pipeline.
version: 1
formatters:
  basic:
    format: '%(process)6d - %(module)15s - %(levelname)7s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout

  main_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: basic
    filename: camel.log
    delay: True

  step_info:
    class: logging.FileHandler
    level: INFO
    formatter: basic
    filename: info.log
    delay: True

  pipeline_info:
    class: logging.FileHandler
    level: INFO
    formatter: basic
    filename: pipeline_info.log
    delay: True

  step_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: basic
    filename: debug.log
    delay: True
root:
  level: DEBUG
  handlers: [console, main_debug, step_info, step_debug, pipeline_info]

disable_existing_loggers: False