# config file for camel generalities.

galaxy:
  # directory to dump stderr/stdout or data in case of pipeline error while running from galaxy
  # as Galaxy removes data and truncates stderr and stdout.
  dump_dir: "/scratch/temp/galaxy_dumps/"