# config file for camel generalities.
temp_dir: "/scratch/temp/"

galaxy:
  # directory to dump stderr/stdout or data in case of pipeline error while running from galaxy
  # as Galaxy removes data and truncates stderr and stdout.
  dump_dir: "/scratch/temp/galaxy_dumps/"

testing:
  testfiles_dir: "/data/camel/testdata/"
