version: 1
formatters:
  basic:
    format: '%(process)6d - %(module)15s - %(levelname)7s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]