import os
import shutil
import tempfile
import unittest
from pathlib import Path

from camel.app.config import config
from camel.app.core.reports.htmlreport import HtmlReport
from camel.app.core.reports.htmlreportsection import HtmlReportSection
from camel.app.core.tool import Tool
from camel.app.loggers import logger
from camel.resources import CSS_STYLE


class CamelTestSuite(unittest.TestCase):
    """
    Base class for Camel test suites.
    """
    running_dir = None

    @staticmethod
    def get_test_file_dir(*args) -> Path:
        """
        Retrieves the directory with test files.
        :param args: Sub-directory or directories
        :return: Test files directory
        """
        dir_test = Path(config.dir_testdata, *args)
        if not dir_test.exists() or not dir_test.is_dir():
            raise FileNotFoundError(f"Cannot find test file directory: {dir_test}")
        return dir_test

    @staticmethod
    def get_reference_file_dir(*args) -> Path:
        """
        Retrieves the directory with reference files.
        :param args: Sub-directory or directories
        :return: Reference files directory
        """
        dir_ref = Path(config.dir_db, 'refgenomes', *args)
        if not dir_ref.exists() or not dir_ref.is_dir():
            raise FileNotFoundError(f"Cannot find reference file directory: {dir_ref}")
        return dir_ref

    def setUp(self) -> None:
        """
        Sets up the resources before running the test.
        :return: None
        """
        self.running_dir = Path(tempfile.mkdtemp(None, 'camel_', config.dir_temp))
        logger.debug(f"Directory for testing: {self.running_dir}")

    def tearDown(self) -> None:
        """
        Removes the working directory after executing the tests.
        :return: None
        """
        if os.environ.get('CAMEL_KEEP_TEST_DIRS') == '1':
            logger.debug(f"Keeping working directory (CAMEL_KEEP_TEST_DIRS): {self.running_dir}")
            return
        if Path(self.running_dir).exists():
            logger.debug(f"Removing working directory: {self.running_dir}")
            shutil.rmtree(self.running_dir)

    def verify_output_files(self, tool: Tool, key: str, nb_files: int = 1) -> None:
        """
        Verifies if the specified number of output files with the given key are created correctly.
        :param tool: Tool
        :param key: Output key
        :param nb_files: Number of output files that should be generated
        :return: None
        """
        self.assertIn(key, tool.tool_outputs, f"Key '{key}' missing from tool outputs")
        self.assertEqual(
            nb_files, len(tool.tool_outputs[key]),
            f"Unexpected number of tools outputs found: {len(tool.tool_outputs[key])}, expected {nb_files}")
        for i in range(0, nb_files):
            output_file_path = tool.tool_outputs[key][i].path
            self.assertTrue(output_file_path.exists(), f"Output file '{key}' (index: {i}) does not exist")
            self.assertGreater(output_file_path.stat().st_size, 0, f"Output file '{key}' (index: {i}) is empty")

    @staticmethod
    def export_report_section(report_section: HtmlReportSection, dir_out: Path) -> Path:
        """
        Exports the report section to the output directory.
        This method can be used to inspect the report generated by tools.
        :param dir_out: Output directory
        :param report_section: HTML report section
        :return: Path to the exported report
        """
        path_out = dir_out / 'report_section.html'
        path_out.parent.mkdir(exist_ok=True, parents=True)
        report = HtmlReport(path_out, path_out.parent)
        report.initialize('Exported report section', CSS_STYLE)
        report.add_html_object(report_section)
        report.save()
        logger.info(f'Report section exported to: {path_out}')
        return path_out
