#############
# Databases #
#############
dbs:
  db_confindr:
    location: &db_confindr {DB_ROOT}/confindr/0.8.1
  db_gene_detection_ncbi_amr:
    location: &db_gene_detection_ncbi_amr {DB_ROOT}/gene_detection/NCBI_AMR/
    required: true
  db_kraken2:
    location: &db_kraken2 {DB_ROOT}/kraken2_microbial/latest
  db_hrrt:
    location: &db_hrrt {DB_ROOT}/ncbi_human_read_scrubber/human_filter.db
    is_file: true
  ref_fasta:
    location: &ref_fasta {DB_ROOT}/refgenomes/Escherichia_coli/NC_002695.2.fasta
    is_file: true
    required: true
  ref_gff3:
    location: &ref_gff3 {DB_ROOT}/refgenomes/Escherichia_coli/NC_002695.2.gff
    is_file: true
    required: true

####################
# Reference genome #
####################
reference:
  name: NC_002695.2
  fasta: *ref_fasta
  gff3: *ref_gff3
  url: https://www.ncbi.nlm.nih.gov/nuccore/NC_002695.2/
  expected_size: 10_000

####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2

##########
# Assays #
##########
assembly:
  flye:
    min_overlap: 1000

confindr:
  db: *db_confindr

contamination_check:
  db: *db_kraken2
  expected_species: Escherichia coli

downsampling:
  coverage_max: {COV_MAX}

quality_checks:
  typing_scheme: null

gene_detection:
  dbs:
    ncbi_amr:
      path: *db_gene_detection_ncbi_amr
      metadata:
        name: Antibiotic(s)
        key: subclass
  options:
    method: blast

read_trimming: {{}}
read_scrubbing:
  db: *db_hrrt

variant_calling:
  ploidy: 1
  report_include_bam: false

variant_filtering:
  depth:
    min_fwd_depth: 1
    min_rev_depth: 1
