####################
# Reference genome #
####################
reference:
  name: NC_002695.2
  fasta: /db/refgenomes/Escherichia_coli/NC_002695.2.fasta
  gff3: /db/refgenomes/Escherichia_coli/NC_002695.2.gff
  url: https://www.ncbi.nlm.nih.gov/nuccore/NC_002695.2/
  expected_size: 10_000

####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2

##########
# Assays #
##########
assembly:
  flye:
    min_overlap: 1000

confindr:
  db: /db/confindr/0.8.1

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Escherichia coli

downsampling:
  coverage_max: {COV_MAX}

quality_checks:
  typing_scheme: null

gene_detection:
  dbs:
    ncbi_amr:
      path: /db/gene_detection/NCBI_AMR/
      metadata:
        name: Antibiotic(s)
        key: subclass
  options:
    method: blast

read_trimming: {{}}
read_scrubbing:
  db: /db/ncbi_human_read_scrubber/human_filter.db

variant_calling:
  ploidy: 1
  report_include_bam: false

variant_filtering:
  depth:
    min_fwd_depth: 1
    min_rev_depth: 1
