####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2

downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 10_000

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Escherichia coli

confindr:
  db: /db/confindr/0.8.1

assembly:
  flye:
    min_overlap: 1000

quality_checks:
  typing_scheme: null
  expected_gc_content: 50.5

quast:
  ref:
    fasta: /db/refgenomes/Escherichia_coli/NC_002695.2.fasta
    gff3: /db/refgenomes/Escherichia_coli/NC_002695.2.gff

gene_detection:
  ncbi_amr:
    path: /db/gene_detection/NCBI_AMR/
    metadata:
      name: Antibiotic(s)
      key: subclass

variant_calling:
  ploidy: 1
  report_include_bam: false
  reference:
    path: /db/refgenomes/Escherichia_coli/NC_002695.2.fasta
    name: NC_002695.2
    url: https://www.ncbi.nlm.nih.gov/nuccore/NC_002695.2/
    annotation_gff: /db/refgenomes/Escherichia_coli/NC_002695.2.gff

variant_filtering:
  depth:
    min_fwd_depth: 1
    min_rev_depth: 1