# Input / output
report: output/report.html
output_dir: output
working_dir: '/scratch/todel/GATK_Camel_test/pipeline/working/'

# Input
fastq_pe:
  - '/scratch/todel/GATK_Camel_test/pipeline/inputs_and_files/input1.fq'
  - '/scratch/todel/GATK_Camel_test/pipeline/inputs_and_files/input2.fq'

ref_genome:
  - '/data/refgenomes/Human/GATK-BroadIns/b37-genome/human_g1k_v37.fa'

fasta_ref: 'broad_b37_human_Genome_1K_v37'
vcf_known_snps: 'broad_b37_snps_high_confidence'
vcf_known_indels: 'broad_b37_indels_gold_standard'

run_markDuplicates: False