####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Kolmogorov_2019-flye
    - Wick_2022-polypolish
    - Zimin_2020-polca
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Langmead_2012-bowtie2
    - Camacho_2009-blast
    - Chen_2016-vfdb
    - Carattoli_2020-plasmidfinder
    - Robertson_2018-mob_suite
    - Carroll_2020a-btyper3
    - Carroll_2020b-btyper3

species: {species}

#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: {genome_size}

read_trimming:
  export_fastq: '{export_fastq}'

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Bacillus
  level_of_depth: G

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: {expected_gc_content}

quast:
  ref:
    fasta: {quast_fasta}
    gff3: {quast_gff}

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000
  canu:
    minimum_input_coverage: 0

variant_calling:
  ploidy: 1
  report_include_bam: {export_bam}
  reference:
    path: {quast_fasta}
    name: {reference_name}
    url: {reference_url}

confindr:
  db: /db/confindr/0.8.1

sequence_typing:
  mlst_cereus:
    path: /db/sequence_typing/bacillus_cereus/mlst
  mlst_subtilis:
    path: /db/sequence_typing/bacillus_subtilis/mlst
  cgmlst_cereus:
    path: /db/sequence_typing/bacillus_cereus/cgmlst
    detection_method: blast
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info

amrfinder:
  db: /db/amrfinder/by_version/latest

mob_suite:
  db: /db/mob_suite/latest
  contig_report: {mobsuite_contig_report}

fastani:
  path: /db/pipelines/bacillus/ref_list.txt

gene_detection:
  gmo:
    path: /db/pipelines/bacillus/databaseGMMV2
    force_detection_method: kma
    metadata:
      name: Additional data
      key: additional
  vfdb_core:
      path: /db/gene_detection/VFDB_core
      perc_identity_cutoff: 90
      min_coverage: 90
      metadata:
        name: Gene
        key: gene
  plasmidfinder:
    path: /db/gene_detection/PlasmidFinder-entero
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 60
      srst2:
        max_divergence: 5
        min_coverage: 60
    metadata:
      name: Notes
      key: notes
    message:
      content: Additional experimental validation should be required to confirm the presence of plasmids.
      category: warning