####################
# Pipeline options #
####################
citations:
  main: Bogaerts_2021-stec_pipeline
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Langmead_2012-bowtie2
    - Camacho_2009-blast

#########################
# Tool specific options #
#########################

downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: {genome_size}

contamination_check:
  db: /db/kraken2/latest/abfhpv/
  expected_species: {expected_species}

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: {expected_gc_content}

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

sequence_typing:
  mlst:
    path: {mlst_db}
  cgmlst:
    path: {cgmlst_db}
    detection_method: blast

resfinder:
  acq_overlap: {which_acqoverlap}
  min_cov: {which_mincov}
  threshold: {which_threshold}

gene_detection:
  gmo:
    path: /scratch/magodfroid/BacillusPipeline/PipelineData/