import argparse
import logging
from pathlib import Path
from typing import Optional, List, Dict, Sequence


class MainTabularFiltering(object):
    """
    This class is used to filter tabular output generated by the MLST tree tool.
    """

    def __init__(self, args: Optional[Sequence[str]] = None) -> None:
        """
        Initializes the filter.
        :param args: Arguments (if not specified, arguments are parsed from command line).
        """
        self._args = MainTabularFiltering._parse_arguments(args)
        if self._args.output is None:
            self._args.output = str(Path(self._args.input_tsv).parent / 'alleles_filtered.tsv')
        self._header = []
        self._total_nb_alleles = -1
        self._total_nb_samples = -1
        self._total_nb_samples_filtered = -1

    def run(self) -> None:
        """
        Runs the filtering process.
        :return: None
        """
        allele_ids_by_loci = self.__parse_input_file(self._args.input_tsv)

        # Determine low quality samples
        bad_samples = self.__get_low_quality_samples(allele_ids_by_loci, self._args.min_perc_loci)
        bad_sample_indices = [i for i, sample in enumerate(self._header[1:]) if sample in bad_samples]

        # Filter output
        filtered_allele_ids_by_loci = {}
        for locus, allele_ids in allele_ids_by_loci.items():
            filtered_allele_ids_by_loci[locus] = [x for i, x in enumerate(allele_ids) if i not in bad_sample_indices]
        self._total_nb_samples_filtered = self._total_nb_samples - len(bad_samples)
        logging.info(f"{self._total_nb_samples_filtered} samples after filtering")
        bad_loci = self.__get_low_quality_loci(filtered_allele_ids_by_loci, self._args.min_perc_samples)

        # Create output file
        self.__create_output_file(filtered_allele_ids_by_loci, bad_loci, bad_samples, self._args.output)

    @staticmethod
    def _parse_arguments(args: Optional[Sequence[str]] = None) -> argparse.Namespace:
        """
        Parses the command line arguments.
        :return: Parsed arguments
        """
        parser = argparse.ArgumentParser()
        parser.add_argument('--input-tsv', required=True, help="Tabular input file")
        parser.add_argument('--output', help="Output file")
        parser.add_argument('--min-perc-loci', default=90, type=int,
                            help="Samples with less than this % of loci detected are filtered out")
        parser.add_argument('--min-perc-samples', default=90, type=int,
                            help="Loci that are detected in less than this % of samples are filtered out")
        return parser.parse_args(args)

    def __parse_input_file(self, input_file: str) -> Dict[str, List[str]]:
        """
        Parses the tabular input file generated by the MLST tree tool
        :param input_file: Input file path
        :return: Allele ids by locus name
        """
        allele_ids_by_loci = {}
        with open(input_file) as handle:
            self._header = [p.strip() for p in handle.readline().split('\t')]
            for line in handle.readlines():
                parts = [p.strip() for p in line.split('\t')]
                allele_ids_by_loci[parts[0]] = parts[1:]
        self._total_nb_alleles = len(allele_ids_by_loci)
        logging.info(f"{self._total_nb_alleles} alleles found")
        self._total_nb_samples = len(self._header) - 1
        logging.info(f"{self._total_nb_samples} samples found")
        return allele_ids_by_loci

    def __get_low_quality_samples(self, allele_ids_by_loci: Dict[str, List[str]], min_perc_loci: int) -> List[str]:
        """
        Returns the samples for which not enough alleles were detected.
        :param allele_ids_by_loci: Allele ids by locus name
        :param min_perc_loci: Minimal percentage of loci required per sample
        :return: List of samples
        """
        bad_samples = []
        for i, sample in enumerate(self._header[1:]):
            nb_of_missing = 0
            for locus, allele_ids in allele_ids_by_loci.items():
                if allele_ids[i] in ('-', '?'):
                    nb_of_missing += 1
            perc_of_loci_missing = 100 * nb_of_missing / self._total_nb_alleles
            if 100 - perc_of_loci_missing < min_perc_loci:
                bad_samples.append(sample)
                logging.info(
                    f"Throwing out sample: {sample} ({perc_of_loci_missing:.2f}% of loci not found)")
        return bad_samples

    def __get_low_quality_loci(self, allele_ids_by_loci: Dict[str, List[str]], min_perc_samples: int) -> List[str]:
        """
        Returns the loci that are not found in enough samples.
        :param allele_ids_by_loci: Allele ids by locus
        :param min_perc_samples: Minimal percentage of samples that need to have locus detected
        :return: List of loci
        """
        bad_loci = []
        for locus, allele_ids in allele_ids_by_loci.items():
            nb_of_missing = len([a for a in allele_ids if a in ('-', '?')])
            perc_of_samples_missing_locus = 100 * nb_of_missing / self._total_nb_samples_filtered
            logging.debug(
                f"Locus '{locus}' - missing in {nb_of_missing} samples ({perc_of_samples_missing_locus:.2f} %)")
            if 100 - perc_of_samples_missing_locus < min_perc_samples:
                bad_loci.append(locus)
                logging.info(f"Throwing out locus: {locus} (found in {self._total_nb_samples - nb_of_missing}/"
                             f"{self._total_nb_samples} samples)")
        logging.info(f"{len(bad_loci)} (out of {self._total_nb_alleles}) loci removed")
        return bad_loci

    def __create_output_file(self, allele_ids_by_loci: Dict[str, List[str]], bad_loci: List[str],
                             bad_samples: List[str], output_path: str) -> None:
        """
        Creates the output file.
        :param allele_ids_by_loci: Allele ids by locus
        :param bad_loci: Loci that did not pass filtering
        :param bad_samples: Samples that did not pass filtering
        :param output_path: Output file path
        :return: None
        """
        filtered_loci_sorted = sorted([locus for locus in allele_ids_by_loci.keys() if locus not in bad_loci])
        with open(output_path, 'w') as handle:
            handle.write('\t'.join(['#Name', 'ST'] + filtered_loci_sorted))
            handle.write('\n')
            for i, sample in enumerate([sample for sample in self._header[1:] if sample not in bad_samples]):
                handle.write(
                    '\t'.join([sample, '-'] + [allele_ids_by_loci[locus][i] for locus in filtered_loci_sorted]))
                handle.write('\n')
        logging.info(f"Output file generated: {output_path}")


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main = MainTabularFiltering()
    main.run()
