import logging
import os

from app.components.blast.alignmentextraction import AlignmentExtraction
from app.components.filesystemhelper import FileSystemHelper
from app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from app.io.tooliofile import ToolIOFile
from app.tools.tool import Tool


class AlignmentExtractor(Tool):
    """
    Tool that extracts alignments from TXT files generated by BLAST.
    The input of this tool:
    - 1 TXT file with all the alignments
    - List of blast hits
     The output:
    - List of alignment files in the same order as the input ('TXT' key in the tool outputs)
    """

    def __init__(self, camel):
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super(AlignmentExtractor, self).__init__('Resistance Characterization: Alignment Extraction', '0.1', camel)

    def _execute_tool(self):
        """
        Executes this tool.
        :return: None
        """
        alignments = AlignmentExtraction.get_alignments(self._tool_inputs['TXT'][0].path)
        self._tool_outputs['TXT'] = []
        if 'VAL_Hits' not in self._tool_inputs:
            return
        for input_ in self._tool_inputs['VAL_Hits']:
            key = AlignmentExtraction.get_key(input_.value.subject, input_.value.query)
            if key in alignments:
                alignment = self.__save_alignment(input_.value.subject, alignments[key])
                self._tool_outputs['TXT'].append(ToolIOFile(alignment))
            else:
                raise ValueError("No alignment found for: '{}'".format(key))

    def _check_input(self):
        """
        Checks if the required inputs are specified.
        :return: None
        """
        if 'TXT' not in self._tool_inputs:
            raise InvalidInputSpecificationError("No TXT input found.")
        if 'VAL_Hits' not in self._tool_inputs:
            logging.warning("No blast hits input found")
        super(AlignmentExtractor, self)._check_input()

    def __save_alignment(self, subject_name, alignment):
        """
        Saves the given alignment.
        :param alignment: Alignment
        :return: Filename of the saved alignment
        """
        filename = os.path.join(self._folder, '{}.txt'.format(FileSystemHelper.make_valid(subject_name)))
        with open(filename, 'w') as output_handle:
            output_handle.write(alignment)
        return filename
