import json
import logging
from typing import List

import os
import re

from app.components.blast.blastformat7parser import BlastFormat7Parser
from app.components.blasttyping.blasthitclustering import BlastHitClustering
from app.components.blasttyping.blasthitfiltering import BlastHitFiltering
from app.components.genedetection.genedetectionblasthit import GeneDetectionBlastHit
from app.components.genedetection.genedetectionutils import GeneDetectionUtils
from app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from app.io.tooliofile import ToolIOFile
from app.io.tooliovalue import ToolIOValue
from app.tools.tool import Tool


class HitFiltering(Tool):
    """
    Class that filters blast hits and reports the best hits. Perfect hits are always reported. The best hits are
    selected from groups of overlapping hits.

    Input:
        TSV: Tabular file generated by Blastn with '7 pident sseqid sseq slen qseqid qstart qend' as output format.
        INFORMS db_info: Information from the database manager. The metadata for the detected hits is extracted from
            this dictionary.

    Output:
        TSV: Tabular output file with the best hits and some statistics.
        VAL_Hits: A list with the detected hit objects.

    Important parameters:
    - extra_column_key & extra_column_name: If set, an extra metadata column is added to the detected hits. The key
      needs to match the key in the metadata dictionary.
    - filtering_method: Determines how the hits are filters. There are two options supported:
        * 'cluster' (default): The best hit for each cluster is reported.
        * 'score': The n best hits according to hit score are reported (controlled by the 'score_limit' parameter).
    """

    def __init__(self, camel):
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super().__init__('Gene Detection: Hit Filtering', '0.1', camel)

    def _execute_tool(self):
        """
        Executes this tool.
        :return: None
        """
        blast_output_data = BlastFormat7Parser.parse_output_file(self._tool_inputs['TSV'][0].path)
        hits = [GeneDetectionBlastHit.create_from_dict(output) for output in blast_output_data]
        hits = BlastHitFiltering.filter_percent_identity(hits, float(self._parameters['min_percent_identity'].value))
        hits = BlastHitFiltering.filter_coverage(hits, float(self._parameters['min_coverage'].value))

        logging.info("Filtering method: '{}'".format(self._parameters['filtering_method'].value))
        if self._parameters['filtering_method'].value == 'cluster':
            hits = HitFiltering.__get_best_hit_per_cluster(hits)
            hits.sort(key=lambda h: (h.locus, h.query_start))
        elif self._parameters['filtering_method'].value == 'score':
            limit = self._parameters['score_limit'].value if 'score_limit' in self._parameters else 5
            hits = hits[:limit]
        self.__add_metadata(hits)

        output_path = os.path.join(self._folder, self._parameters['output_filename'].value)
        self.__create_output_file(hits, output_path)
        self._tool_outputs['TSV'] = [ToolIOFile(output_path)]

    def _check_input(self):
        """
        Checks whether the input is correct.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("No 'TSV' input found.")
        if 'db_info' not in self._input_informs:
            raise InvalidInputSpecificationError("No database informs found")
        super(HitFiltering, self)._check_input()

    def __add_metadata(self, hits):
        """
        Adds metadata to the filtered hits.
        :return: None
        """
        for hit in hits:
            new_id = hit.subject.split('__')[3]
            full_header = self._input_informs['db_info']['mapping'].get(new_id)
            _, metadata = GeneDetectionUtils.parse_header(full_header)

            hit.locus = metadata['allele']
            hit.accession = metadata['accession']
            if 'extra_column_key' in self._parameters:
                column_value = metadata[self._parameters['extra_column_key'].value]
                if not column_value:
                    column_value = '-'
                hit.set_extra_column(self._parameters['extra_column_name'].value, column_value)
        self._tool_outputs['VAL_Hits'] = [ToolIOValue(hit) for hit in hits]

    @staticmethod
    def __get_best_hit_per_cluster(hits: List[GeneDetectionBlastHit]) -> List[GeneDetectionBlastHit]:
        """
        Returns the best hit for each cluster.
        :param hits: Hits
        :return: Best matching hits
        """
        hits_per_cluster = {}
        for hit in hits:
            cluster = hit.subject.split('__')[1]
            if cluster not in hits_per_cluster:
                hits_per_cluster[cluster] = []
            hits_per_cluster[cluster].append(hit)

        reported_hits = []
        for _, hits in hits_per_cluster.items():
            reported_hits.extend(BlastHitFiltering.detect_best_hits(hits))
        return reported_hits

    @staticmethod
    def __create_output_file(hits, path):
        """
        Creates the tabular output file.
        :param hits: Detected hits
        :param path: Output path
        :return: None
        """
        with open(path, 'w') as handle:
            if len(hits) > 0:
                handle.write('\t'.join(hits[0].get_table_column_names()))
                handle.write('\n')
                for hit in hits:
                    handle.write(hit.to_table_row())
                    handle.write('\n')
