#############
# Databases #
#############
dbs: {{}}

####################
# Pipeline options #
####################
citations:
  main: Bogaerts_2019-neisseria_validation
  other:
    - Chen_2023-fastp
    - Shen_2024-seqkit2
    - Bankevich_2012-spades
    - Kolmogorov_2019-flye
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Li_2021-minimap2
    - Danecek_2021-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Feldgarden_2019-ndaro
    - Bortolaia_2020-resfinder_4.0
    - Jolley_2010-bigsdb
    - Muzzi_2019-gmats
    - Marjuki_2019-neisseria_serogroup
    - Bratcher_2014-neisseria_cgmlst

####################
# Reference genome #
####################
reference:
  name: <i>Neisseria meningitidis</i> (NZ_CP021520.1)
  fasta: /db/refgenomes/Neisseria_meningitidis/NZ_CP021520.1.fasta
  gff3: /db/refgenomes/Neisseria_meningitidis/NZ_CP021520.1.gff3
  url: https://www.ncbi.nlm.nih.gov/nuccore/NZ_CP021520.1
  expected_gc: 51.5

#########################
# Tool-specific options #
#########################
amrfinder:
  db: /db/amrfinder/v4/latest
  organism: Neisseria_meningitidis

assembly:
  spades:
    cov_cutoff: 'off'
  min_contig_length: 0

confindr:
  db: /db/confindr/0.8.1

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Neisseria meningitidis

downsampling:
  coverage_max: {COV_MAX}

gmats:
  db: /db/pipelines/neisseria/gMATS_DB.txt

mendevar:
  db: /db/pipelines/neisseria/mendevar_DB.txt

quality_checks:
  typing_scheme: {QC_SCHEME}

read_scrubbing: {{}}

read_trimming: {{}}

resfinder4:
  db: /db/resfinder4
  point: False

variant_calling:
  ploidy: 1
  report_include_bam: False

variant_filtering: {{}}

###################
# Sequence typing #
###################
sequence_typing:
  dbs:
    bast:
      path: /db/sequence_typing/neisseria/bast
    cgmlst:
      path: /db/sequence_typing/neisseria/cgmlst
    cgmlst_v3:
      path: /db/sequence_typing/neisseria/cgmlst_v3
    feta:
      path: /db/sequence_typing/neisseria/feta
    fhbp:
      path: /db/sequence_typing/neisseria/fhbp
    mlst:
      path: /db/sequence_typing/neisseria/mlst
    pora:
      path: /db/sequence_typing/neisseria/pora
    porb:
      path: /db/sequence_typing/neisseria/porb
    resistance_genes:
      path: /db/sequence_typing/neisseria/resistance_genes
    rmlst:
      path: /db/sequence_typing/various/rmlst
      message:
        content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
        category: info
    rplf:
      path: /db/sequence_typing/neisseria/rplf
    serogroup_a:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_a
    serogroup_b:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_b
    serogroup_c:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_c
    serogroup_e:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_e
    serogroup_h:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_h
    serogroup_l:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_l
    serogroup_w:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_w
    serogroup_x:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_x
    serogroup_y:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_y
    serogroup_z:
      path: /db/sequence_typing/neisseria/capsule_region_a_serogroup_z
    vaccine_targets:
      path: /db/sequence_typing/neisseria/vaccine_targets
