import logging
import os
from typing import List, Dict

from camel.app.camel import Camel
from camel.app.components.genedetection.genedetectionkmahit import GeneDetectionKMAHit
from camel.app.components.genedetection.genedetectionutils import GeneDetectionUtils
from camel.app.components.genedetection.mapping import Mapping
from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.io.tooliovalue import ToolIOValue
from camel.app.tools.tool import Tool


class KMAGeneDetectionHitExtractor(Tool):
    """
    Extracts Gene detection hits from the KMA output.
    """

    def __init__(self, camel: Camel) -> None:
        """
        Initializes this tool.
        :param camel: CAMEL instance
        """
        super().__init__('KMA gene detection hit extractor', '1.0', camel)

    def _check_input(self) -> None:
        """
        Checks if the provided input is valid.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError('TSV input is required')
        if 'db' not in self._input_informs:
            raise InvalidInputSpecificationError('DB informs are required')
        super()._check_input()

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        hits = KMAGeneDetectionHitExtractor.__parse_kma_output_file(
            self._tool_inputs['TSV'][0].path, self._input_informs['db']['mapping'])
        hits_filtered = self.__filter_hits(hits)
        hits_by_cluster = self.__cluster_hits(hits_filtered)
        hits_selected = self.__get_best_hit_per_cluster(hits_by_cluster)
        self.__set_output(hits_selected)

    @staticmethod
    def __parse_kma_output_file(path_output: str, mapping: Mapping) -> List[GeneDetectionKMAHit]:
        """
        Parses the output file generated by KMA.
        :param path_output: Output file path
        :param mapping: Mapping of seq_id to original header
        :return: List of hits
        """
        hits = []
        with open(path_output) as handle:
            lines = handle.readlines()
            if len(lines) < 2:
                return []
            header_indices = {h: i for i, h in enumerate(lines[0].strip().split('\t'))}
            for line in lines[1:]:
                parts = [x.strip() for x in line.split('\t')]
                seq_id = parts[header_indices['#Template']].split('__')[2]
                hits.append(GeneDetectionKMAHit(
                    mapping.get_metadata(seq_id, 'allele'),
                    mapping.get_metadata(seq_id, 'accession'),
                    parts[header_indices['#Template']],
                    int(parts[header_indices['Score']]),
                    int(parts[header_indices['Template_length']]),
                    float(parts[header_indices['Template_Identity']]),
                    float(parts[header_indices['Template_Coverage']]),
                    float(parts[header_indices['Depth']])
                ))
        return hits

    def __filter_hits(self, hits: List[GeneDetectionKMAHit]) -> List[GeneDetectionKMAHit]:
        """
        Filters the detected hits based on the tool parameters.
        :param hits: List of input hits
        :return: List of filtered hits
        """
        # Percent identity filtering
        min_percent_identity = float(self._parameters['min_percent_identity'].value)
        hits_filtered_identity = [h for h in hits if h.percent_identity >= min_percent_identity]
        logging.info(f"{len(hits_filtered_identity)}/{len(hits)} hits passed identity filtering")

        # Percent coverage filtering
        min_percent_coverage = float(self._parameters['min_percent_coverage'].value)
        hits_filtered_coverage = [h for h in hits_filtered_identity if h.subject_coverage >= min_percent_coverage]
        logging.info(f"{len(hits_filtered_coverage)}/{len(hits_filtered_identity)} hits passed identity filtering")
        return hits

    @staticmethod
    def __cluster_hits(hits: List[GeneDetectionKMAHit]) -> Dict[str, List[GeneDetectionKMAHit]]:
        """
        Groups hits based on the database cluster they belong to.
        :param hits: List of input hits
        :return: Dictionary of hits per cluster
        """
        hits_by_cluster = {}
        for hit in hits:
            cluster = hit.subject.split('__')[1]
            if cluster not in hits_by_cluster:
                hits_by_cluster[cluster] = []
            hits_by_cluster[cluster].append(hit)
        logging.info(f"{len(hits_by_cluster)} clusters with hits found")
        return hits_by_cluster

    @staticmethod
    def __get_best_hit_per_cluster(hits_by_cluster: Dict[str, List[GeneDetectionKMAHit]]) -> List[GeneDetectionKMAHit]:
        """
        Returns the best hit for each cluster.
        :param hits_by_cluster: Dictionary of hits per cluster
        :return: List of best hit for each cluster
        """
        reported_hits = []
        for _, hits in hits_by_cluster.items():
            if len(hits) < 1:
                continue
            reported_hits.append(sorted(hits, key=lambda x: -x.score)[0])
        return reported_hits

    def __set_output(self, hits_selected: List[GeneDetectionKMAHit]) -> None:
        """
        Sets the output of this tool.
        :param hits_selected: Selected hits
        :return: None
        """
        output_path = os.path.join(self._folder, 'gene-detection-{}.tsv'.format(
            self._input_informs['db']['name'].lower()))
        GeneDetectionUtils.export_hits_tabular(hits_selected, output_path)
        self._tool_outputs['TSV'] = [ToolIOFile(output_path)]
        self._tool_outputs['VAL_hits'] = [ToolIOValue(h) for h in hits_selected]
