from pathlib import Path

from camel.app.core.io.tooliofile import ToolIOFile
from camel.app.tools.bwa.bwa import BWA


class BWAMap(BWA):
    """
    Read mapping using 'bwa mem' from BWA.

    INPUTs:
    - FASTQ_PE, FASTQ_SE, FASTQ_INT: FASTQ input file(s) containing NGS reads
    - INDEX_GENOME_PREFIX: String containing the prefix used for index files generated by 'bwa index'
    - SAMPLE_NAME: String specifying the sample name used as readgroup annotations in SAM file

    OUTPUT:
    - SAM file containing read mapping information

    UPDATE:
    - since v0.7.15, bwa mem support both PE and SE reads mapping through interleaved fastq file with revamped '-p'
      option (smart pairing) (see changelog)
    """
    OUTPUT_NAME = 'bwa_readmap.sam'
    DEFAULT_SAMPLE_NAME = 'sampleA'

    def __init__(self) -> None:
        """
        Initialize BWAMap
        :return: None
        """
        super().__init__('bwa_mem', '0.7.17')
        self._fastq_inputs_str = None
        self._readgroup_str = ''

    def _execute_tool(self) -> None:
        """
        Function to run BWA mem to map reads
        :return: None
        """
        self.__set_input()
        self.__set_output()
        self.__build_command()
        self._execute_command()

    def __set_input(self) -> None:
        """
        Set input
        :return: None
        """
        if 'FASTQ_PE' in self._tool_inputs:
            self._fastq_inputs_str = ' '.join(str(f.path) for f in self._tool_inputs['FASTQ_PE'])
        elif 'FASTQ_SE' in self._tool_inputs:
            self._fastq_inputs_str = str(self._tool_inputs['FASTQ_SE'][0].path)
        elif 'FASTQ_INT' in self._tool_inputs:
            self._fastq_inputs_str = f"-p {self._tool_inputs['FASTQ_INT'][0].path}"

        if 'SAMPLE_NAME' in self._tool_inputs:
            self._readgroup_str += f"@RG\tID:{self._tool_inputs['SAMPLE_NAME'][0].value}\tSM:{self._tool_inputs['SAMPLE_NAME'][0].value}"
        elif 'add_read_group' in self._parameters:
            # Read Group format: '@RG\tID:foo\tSM:bar'
            self._readgroup_str += f"@RG\tID:{BWAMap.DEFAULT_SAMPLE_NAME}\tSM:{BWAMap.DEFAULT_SAMPLE_NAME}"

    def _check_input(self) -> None:
        """
        Check input for BWA mem.
        :return: None
        """
        if 'FASTQ_PE' in self._tool_inputs:
            if len(self._tool_inputs['FASTQ_PE']) != 2:
                raise ValueError("Paired end fastq inputs require exactly 2 files.")
        elif 'FASTQ_SE' in self._tool_inputs:
            if len(self._tool_inputs['FASTQ_SE']) > 1:
                raise ValueError("Single end fastq input requires exactly 1 file.")
        elif 'FASTQ_INT' in self._tool_inputs:
            if len(self._tool_inputs['FASTQ_INT']) > 1:
                raise ValueError("Interleaved fastq input requires exactly 1 file.")
        else:
            raise ValueError("No supported FASTQ_PE, FASTQ_SE, or FASTQ_INT input found")

        if 'INDEX_GENOME_PREFIX' not in self._tool_inputs:
            raise ValueError('No genome index input (INDEX_GENOME_PREFIX) found.')
        super()._check_input()

    def __set_output(self) -> None:
        """
        Set proper outputs for BWA mem
        :return: None
        """
        self._tool_outputs['SAM'] = [ToolIOFile(self.folder / BWAMap.OUTPUT_NAME)]

    def __build_command(self, pipe_in: bool = False, pipe_out: bool =  False) -> None:
        """
        Build command to run BWA mem
        :return: None
        """
        command_parts = [
            self._tool_command,
            ' '.join(self._build_options(excluded_parameters=['add_read_group'])),
            str(self._tool_inputs['INDEX_GENOME_PREFIX'][0].value),
            self._fastq_inputs_str]

        if self._readgroup_str:
            command_parts.append(f' -R {self._readgroup_str!r} ')

        if not pipe_out:
            command_parts.append(f' > {self._tool_outputs["SAM"][0].path} ')

        self._command.command = ' '.join(command_parts)

    def _before_pipe(self, dir_: Path, pipe_in: bool, pipe_out: bool) -> None:
        """
        Prepares the command that will be piped.
        :param dir_: Running directory
        :param pipe_in: True if tool receives piped input
        :param pipe_out: True if tool generates piped output
        :return: None
        """
        self.__set_input()
        self.__set_output()
        self.__build_command(pipe_in, pipe_out)

    def _after_pipe(self, stderr: str, is_last_in_pipe: bool) -> None:
        """
        Performs the required steps after executing the tool as part of a pipe.
        :param stderr: Stderr for this command in the pipe
        :param is_last_in_pipe: Boolean to indicate if this is the last step in the pipe
        :return: None
        """
        pass
