import os
import re

import logging


class AlignmentExtraction(object):
    """
    Class that extracts alignments from output files generated by Blast.
    The files have to be created with the '-outfmt 0' option.
    """

    MAX_QUERY_LENGTH = 65

    @staticmethod
    def get_alignments(alignment_file):
        """
        Returns the individual alignments from the input file.
        :param alignment_file: file containing the alignments
        :return: Dictionary of alignments
        """
        with open(alignment_file) as handle:
            full_text = handle.read()
            text_parts = full_text.split('> ')

        alignments = {}

        last_query = AlignmentExtraction.__get_query(text_parts[0])
        for text_part in text_parts:
            if AlignmentExtraction.__is_alignment(text_part):
                query = last_query
                subject = text_part.split('\n')[0].split(' ')[0]
                key = (subject, query)
                if key in alignments:
                    raise ValueError("Duplicate key: {}\n{}".format(key, sorted(list(alignments.keys()),
                                                                                key=lambda x: (x[1], x[0]))))
                alignments[key] = AlignmentExtraction.__clean_alignment(text_part)
            if AlignmentExtraction.__get_query(text_part):
                last_query = AlignmentExtraction.__get_query(text_part)
        logging.info("{} alignments found in '{}'".format(len(alignments), os.path.basename(alignment_file)))
        return alignments

    @staticmethod
    def get_key(subject, query):
        """
        Generates the key for the given query.
        :param subject: Subject
        :param query: Query
        :return: key
        """
        return subject, AlignmentExtraction.__cleanup_query_line(query)

    @staticmethod
    def __get_query(text_part):
        """
        Returns the last query from the given text part.
        :param text_part: Text part
        :return: Query
        """
        for line in reversed(text_part.split('\n')):
            if line.startswith('Query='):
                return AlignmentExtraction.__cleanup_query_line(line)

    @staticmethod
    def __is_alignment(text):
        """
        Checks if the given text block is an alignment.
        :param text: Text part
        :return: True if the text is an alignment
        """
        if not re.search('^Length=', text, re.MULTILINE):
            return False
        try:
            AlignmentExtraction.__get_alignment_end_line_number(text)
        except ValueError:
            return False
        return True

    @staticmethod
    def __clean_alignment(alignment):
        """
        Cleans the given alignment. Trailing information is removed.
        :return: Cleaned alignment
        """
        return '\n'.join(alignment.split('\n')[0:AlignmentExtraction.__get_alignment_end_line_number(alignment) + 1])

    @staticmethod
    def __get_alignment_end_line_number(alignment):
        """
        Returns the line number of the last line of the alignment.
        :param alignment: Alignment
        :return: Line number
        """
        match = re.search(r'(Sbjct  \d+ +[\w-]+  \d+\n\n\n)', alignment)
        if match:
            last_line = match.group(1)
            return alignment.split('\n').index(last_line.strip())
        else:
            raise ValueError('Cannot determine the last line of the alignment')

    @staticmethod
    def __cleanup_query_line(line):
        """
        Cleans up the given query line.
        :param line: Line containing the query
        :return: Query
        """
        return line.replace('Query= ', '').split(' ')[0].strip()[0:AlignmentExtraction.MAX_QUERY_LENGTH]
