from camel.app.command.command import Command
from camel.app.components import toolutils
from camel.app.error import InvalidToolInputError
from camel.app.io.tooliofile import ToolIOFile
from camel.app.tools.tool import Tool


class Krona(Tool):
    """
    Krona allows hierarchical data to be explored with zooming, multi-layered pie charts.
    This implementation handles input generated by Kraken.

    Input:
        TSV: A TSV file generated by Kraken.
    Output:
        HTML: Interactive HTML report with a pie chart containing the detected taxonomies.
    """

    def __init__(self) -> None:
        """
        Initializes this tool.
        """
        super().__init__('Krona', '2.7')

    def _execute_tool(self) -> None:
        """
        Executes this tool.
        :return: None
        """
        output_path = self.folder / 'krona_out.html'
        self._command.command = 'cut -f2,3 {} | {} {} -o {} -'.format(
            self._tool_inputs['TSV'][0].path, self._tool_command, ' '.join(self._build_options()), str(output_path))
        self._execute_command()
        self._tool_outputs['HTML'] = [ToolIOFile(output_path)]

    def _check_input(self) -> None:
        """
        Checks if the provided input is valid.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidToolInputError("TSV input is required")
        if len(self._tool_inputs['TSV']) != 1:
            raise InvalidToolInputError("Exactly one TSV input is required")
        super()._check_input()

    def _check_command_output(self, command: Command) -> None:
        """
        Checks if the tool was executed successfully.
        :param command: Command to check
        :return: None
        """
        toolutils.check_tool_execution(self, command, exit_code=0)
