####################
# Pipeline options #
####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Coster_2023-nanoplot
    - Shen_2016-seqkit
    - Wood_2019-kraken2
    - Ondov_2016-mash
    - Li_2009-bwa
    - Li_2018-minimap2
    - Li_2009-samtools
    - Li_2011-bcftools
    - Zheng_2021-clair3
    - Aksamentov_2021-nextclade

####################
# Reference genome #
####################
reference: {{}}

#########################
# Tool specific options #
#########################
antivirals:
  db: /db/pipelines/viral_consensus/version_1.1/antivirals

downsampling:
  disabled: true
  coverage_max_by_segment: {COV_MAX_SEGMENT}

read_trimming: {{}}

contamination_check:
  db: /db/kraken2_full/latest/
  expected_species: {EXPECTED_SPECIES}

quality_checks:
  expected_gc_content: 51.5
