#!/usr/bin/env python
import argparse
from pathlib import Path
from typing import Optional, Sequence

from Bio import SeqIO

from camel.app.camel import Camel
from camel.app.loggers import logger


class MainExtractConsensusSeqs(object):
    """
    Tool that extracts the consensus sequences generated by the viral consensus pipeline.
    """

    def __init__(self, args: Optional[Sequence[str]] = None) -> None:
        """
        Initializes this tool.
        :param args: Command line arguments
        return: None
        """
        self._args = MainExtractConsensusSeqs._parse_arguments(args)

    @staticmethod
    def _parse_arguments(args: Optional[Sequence[str]]) -> argparse.Namespace:
        """
        Parses the command line arguments.
        :param args: Command line arguments
        :return: Parsed arguments
        """
        parser = argparse.ArgumentParser()
        parser.add_argument('--dir', type=Path, action='append')
        parser.add_argument(
            '--segment', type=str,
            help='The segment to extract (can be left blank if there is only sequence per FASTA file')
        parser.add_argument('--no-ambiguous', action='store_true')
        parser.add_argument('--output', type=Path, required=True, help='Stores the output in FASTA format')
        return parser.parse_args(args)

    def run(self) -> None:
        """
        Extracts the sequences from the output directories.
        :return: None
        """
        sequences_out = []
        logger.info(f'Attempting to extract sequences from {len(self._args.dir)} directories')
        for path_dir in self._args.dir:
            try:
                # Collect FASTA file
                dir_sub = 'iterative_mapping' if self._args.no_ambiguous else 'multi_allelic'
                path_fasta = next(p for p in (path_dir / dir_sub).glob('*.fasta') if '-ref' not in p.name)
            except StopIteration:
                logger.warning(f'No FASTA file found in directory: {path_dir}')
                continue

            # Store sequence
            seq = MainExtractConsensusSeqs._extract_seq_record(path_fasta, self._args.segment)
            if seq is None:
                continue
            sequences_out.append(seq)

        # Create output file
        with self._args.output.open('w') as handle:
            SeqIO.write(sequences_out, handle, 'fasta')
        logger.info(f'Output file created: {self._args.output} ({len(sequences_out)} sequences)')

    @staticmethod
    def _extract_seq_record(path_fasta: Path, segment: str) -> SeqIO.SeqRecord:
        """
        Extracts the sequence record
        :param path_fasta: Path to FASTA file
        :param segment:
        :return: Extracts the SeqRecord with the target segment
        """
        logger.debug(f'Parsing: {path_fasta}')
        with path_fasta.open() as handle:
            seqs = list(SeqIO.parse(handle, 'fasta'))
            logger.debug(f'{len(seqs)} sequences parsed from {path_fasta.name}')

        # Single sequence in FASTA file
        if len(seqs) == 1:
            return seqs[0]

        # Check if segment was specified
        if segment is None:
            raise ValueError("'--segment' needs to be specified for FASTA files with multiple sequences")

        # Multiple sequences in FASTA file
        try:
            return next(s for s in seqs if s.id.lower().endswith(segment.lower()))
        except StopIteration:
            logger.info(f"Sequence '{segment}' not found in: {path_fasta.name}")


if __name__ == '__main__':
    Camel.get_instance()
    extract_seqs = MainExtractConsensusSeqs()
    extract_seqs.run()
