#!/usr/bin/env python
import dataclasses
from pathlib import Path
from typing import Union

import click
from Bio import SeqIO

from camel.app.cli import cliutils
from camel.app.loggers import logger, initialize_logging
from camel.app.scriptutils.basescript.basescript import BaseScript
from camel.app.scriptutils.model import BaseInput, BaseOutput, BaseOptions


@dataclasses.dataclass(frozen=True)
class Input(BaseInput):
    """
    Input for the consensus sequence extraction script.
    """
    dir: list[Path] = dataclasses.field(metadata={'help': 'Input directories'})

@dataclasses.dataclass(frozen=True)
class Output(BaseOutput):
    """
    Output for the consensus sequence extraction script.
    """
    output: Path = dataclasses.field(metadata={'help': 'Output FASTA file'})

@dataclasses.dataclass(frozen=True)
class Options(BaseOptions):
    """
    Options for the consensus sequence extraction script.
    """
    segment: str | None = dataclasses.field(default=None, metadata={
        'help': 'The segment to extract (can be left blank if there is only sequence per FASTA file'})
    no_ambiguous: bool = dataclasses.field(default=False, metadata={'help': 'Exclude ambiguous sequences'})


class MainExtractConsensusSeqs(BaseScript[Input, Output, Options]):
    """
    Tool that extracts the consensus sequences generated by the viral consensus pipeline.
    """

    def __init__(self, in_: Input, out: Output, opts: Options) -> None:
        """
        Initializes the main script.
        :param in_: Script input
        :param out: Script output
        :param opts: Options
        :return: None
        """
        super().__init__(
            name='Viral consensus pipeline: extract consensus sequences',
            version='1.0.0',
            script_in=in_,
            script_out=out,
            script_opts=opts
        )

    def _execute(self) -> None:
        """
        Extracts the sequences from the output directories.
        :return: None
        """
        sequences_out = []
        logger.info(f'Attempting to extract sequences from {len(self._script_in.dir)} directories')
        for path_dir in self._script_in.dir:
            try:
                # Collect FASTA file
                dir_sub = 'iterative_mapping' if self._script_opts.no_ambiguous else 'multi_allelic'
                path_fasta = next(p for p in (path_dir / dir_sub).glob('*.fasta') if '-ref' not in p.name)
            except StopIteration:
                logger.warning(f'No FASTA file found in directory: {path_dir}')
                continue

            # Store sequence
            seq = MainExtractConsensusSeqs._extract_seq_record(path_fasta, self._script_opts.segment)
            if seq is None:
                continue
            sequences_out.append(seq)

        # Create the output file
        with self._script_out.output.open('w') as handle:
            SeqIO.write(sequences_out, handle, 'fasta')
        logger.info(f'Output file created: {self._script_out.output} ({len(sequences_out)} sequences)')

    @staticmethod
    def _extract_seq_record(path_fasta: Path, segment: str) -> Union[SeqIO.SeqRecord, None]:
        """
        Extracts the sequence record
        :param path_fasta: Path to FASTA file
        :param segment:
        :return: Extracts the SeqRecord with the target segment
        """
        logger.debug(f'Parsing: {path_fasta}')
        with path_fasta.open() as handle:
            seqs = list(SeqIO.parse(handle, 'fasta'))
            logger.debug(f'{len(seqs)} sequences parsed from {path_fasta.name}')

        # Single sequence in FASTA file
        if len(seqs) == 1:
            return seqs[0]

        # Check if segment was specified
        if segment is None:
            raise ValueError("'--segment' needs to be specified for FASTA files with multiple sequences")

        # Multiple sequences in FASTA file
        try:
            return next(s for s in seqs if s.id.lower().endswith(segment.lower()))
        except StopIteration:
            logger.info(f"Sequence '{segment}' not found in: {path_fasta.name}")
            return None

@click.command(
    name='viral_consensus_extract',
    short_help='Extract consensus sequences from the viral consensus pipeline output')
@cliutils.add_click_options_from_dataclass(Input)
@cliutils.add_click_options_from_dataclass(Output)
@cliutils.add_click_options_from_dataclass(Options)
def main(**kwargs) -> None:
    """
    Wrapper for NCBI AMRFinder+.
    """
    script = MainExtractConsensusSeqs(
        in_=Input(**cliutils.from_kwargs(Input, kwargs)),
        out=Output(**cliutils.from_kwargs(Output, kwargs)),
        opts=Options(**cliutils.from_kwargs(Options, kwargs))
    )
    script.run()


if __name__ == '__main__':
    initialize_logging()
    main()
