from pathlib import Path

from camel.app.camel import Camel
from camel.app.pipeline.step import Step
from camel.app.snakemake.snakemakeutils import SnakemakeUtils
from camel.app.snakemake.snakepipelineutils import SnakePipelineUtils
from camel.resources.snakefile import medaka_polishing

camel = Camel.get_instance()

rule assembly_flye_map_reads:
    """
    Maps the reads to the flye assembly.
    """
    input:
        FQ = Path(config['working_dir']) / 'fq_dict.io',
        FASTA = Path(config['working_dir']) / medaka_polishing.INPUT_ASSEMBLY_FASTA
    output:
        SAM = Path(config['working_dir']) / 'medaka' / 'minimap2' / 'sam.io'
    params:
        dir_ = Path(config['working_dir']) / 'medaka' / 'minimap2'
    run:
        from camel.app.tools.minimap2.minimap2mapping import Minimap2Mapping
        minimap2 = Minimap2Mapping(Camel.get_instance())
        SnakemakeUtils.add_pickle_input(minimap2, 'FASTA', Path(input.FASTA))
        minimap2.add_input_files(SnakePipelineUtils.extracts_fq_input(
            Path(input.FQ), key_se='FASTQ', read_type='SE'))
        step = Step(str(rule), minimap2, Camel.get_instance(), params.dir_)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(minimap2, output)

rule assembly_flye_sam_to_bam:
    """
    Converts the SAM file generated by bowtie2 to BAM format.
    """
    input:
        SAM = rules.assembly_flye_map_reads.output.SAM
    output:
        BAM = Path(config['working_dir']) / 'medaka' / 'minimap2' / 'bam.io'
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'minimap2'
    run:
        from camel.app.tools.samtools.samtoolsview import SamtoolsView
        samtools_view = SamtoolsView(camel)
        step = Step(str(rule), samtools_view, camel, params.running_dir)
        SnakemakeUtils.add_pickle_inputs(samtools_view, input)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(samtools_view, output)

rule assembly_flye_sort_bam:
    """
    Sorts the BAM alignment.
    """
    input:
        BAM = rules.assembly_flye_sam_to_bam.output.BAM
    output:
        BAM = Path(config['working_dir']) / 'medaka' / 'minimap2' / 'bam_sorted.io'
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'minimap2'
    run:
        from camel.app.tools.samtools.samtoolssort import SamtoolsSort
        samtools_sort = SamtoolsSort(camel)
        step = Step(str(rule), samtools_sort, camel, params.running_dir)
        SnakemakeUtils.add_pickle_inputs(samtools_sort, input)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(samtools_sort, output)

rule assembly_flye_samtools_flagstat:
    """
    Runs samtools flagstat to determine the mapping rate.
    """
    input:
        BAM = rules.assembly_flye_sam_to_bam.output.BAM
    output:
        INFORMS = Path(config['working_dir']) / medaka_polishing.OUTPUT_ASSEMBLY_MAPPING_RATE_INFORMS
    params:
        dir_ = Path(config['working_dir']) / 'medaka' / 'samtools_flagstat'
    run:
        from camel.app.tools.samtools.samtoolsflagstat import SamtoolsFlagstat
        flagstat = SamtoolsFlagstat(Camel.get_instance())
        SnakemakeUtils.add_pickle_inputs(flagstat, input)
        flagstat.run(Path(params.dir_).absolute())
        # Calculate mapping rate
        flagstat.informs['mapping_perc'] = 100 * flagstat.informs['mapped'][0] / flagstat.informs['total'][0]
        SnakemakeUtils.dump_tool_outputs(flagstat, output)

rule assembly_flye_samtools_depth:
    """
    Runs samtools depth on the BAM file of the reads mapped to the assembly.
    """
    input:
        BAM = rules.assembly_flye_sort_bam.output.BAM
    output:
        TSV = Path(config['working_dir']) / 'medaka' / 'samtools_depth' / 'tsv.io',
        INFORMS = Path(config['working_dir']) / medaka_polishing.OUTPUT_ASSEMBLY_DEPTH_INFORMS
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'samtools_depth'
    run:
        from camel.app.tools.samtools.samtoolsdepth import SamtoolsDepth
        samtools_depth = SamtoolsDepth(camel)
        step = Step(str(rule), samtools_depth, camel, params.running_dir)
        SnakemakeUtils.add_pickle_inputs(samtools_depth, input)
        step.run_step()
        samtools_depth.informs['_tag'] = 'Coverage calculation'
        SnakemakeUtils.dump_tool_outputs(samtools_depth, output)

rule assembly_flye_index_bam:
    """
    Indexes the BAM file.
    """
    input:
        BAM = rules.assembly_flye_sort_bam.output.BAM
    output:
        BAI = Path(config['working_dir']) / 'medaka' / 'minimap2' / 'samtools_sort.bam.bai'
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'minimap2'
    run:
        from camel.app.tools.samtools.samtoolsindex import SamtoolsIndex
        samtools_index = SamtoolsIndex(camel)
        SnakemakeUtils.add_pickle_inputs(samtools_index, input)
        samtools_index.update_parameters(generate_bai_index=True)
        step = Step(str(rule), samtools_index, camel, params.running_dir, config)
        step.run_step()

rule assembly_flye_medaka_consensus:
    """
    Runs the medaka consensus algorithm.
    """
    input:
        BAM = rules.assembly_flye_sort_bam.output.BAM,
        BAI = rules.assembly_flye_index_bam.output.BAI
    output:
        HDF = Path(config['working_dir']) / 'medaka' / 'raw_hdf.io',
        INFORMS = Path(config['working_dir']) / 'medaka' / 'commands-consensus.io'
    params:
        running_dir = Path(config['working_dir']) / 'medaka',
        medaka_options = config.get('polishing', {}).get('medaka', {}).get('consensus', {})
    threads: 8
    run:
        from camel.app.tools.medaka.medakaconsensus import MedakaConsensus
        medaka = MedakaConsensus(camel)
        SnakemakeUtils.add_pickle_input(medaka, 'BAM', Path(input.BAM))
        medaka.update_parameters(**params.medaka_options)
        medaka.update_parameters(threads=threads)
        step = Step(str(rule), medaka, camel, params.running_dir, config)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(medaka, output)

rule polishing_medaka_stitch:
    """
    Runs the medaka stitch algorithm.
    """
    input:
        HDF = rules.assembly_flye_medaka_consensus.output.HDF,
        FASTA = rules.assembly_flye_filter_contig_length.output.FASTA
    output:
        FASTA = Path(config['working_dir']) / 'medaka' / 'fasta.io',
        INFORMS = Path(config['working_dir']) / 'medaka' / 'commands-stitch.io'
    params:
        working_dir = Path(config['working_dir']) / 'medaka',
        medaka_options = config.get('polishing',{}).get('medaka',{}).get('stitch',{})
    threads: 8
    run:
        from camel.app.tools.medaka.medakastitch import MedakaStitch
        medaka = MedakaStitch(camel)
        SnakemakeUtils.add_pickle_inputs(medaka, input)
        medaka.update_parameters(**params.medaka_options, threads=threads)
        step = Step(str(rule), medaka, camel, params.working_dir, config)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(medaka, output)

rule polishing_medaka_quast:
    """
    Generates assembly statistics using QUAST.
    """
    input:
        FASTA = rules.polishing_medaka_stitch.output.FASTA
    output:
        TSV = Path(config['working_dir']) / 'medaka' / 'quast' / 'tsv.io'
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'quast'
    run:
        from camel.app.tools.quast.quast import Quast
        quast = Quast(camel)
        SnakemakeUtils.add_pickle_inputs(quast, input)
        step = Step(str(rule), quast, camel, params.running_dir)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(quast, output)

rule polishing_medaka_quast_extract_informs:
    """
    Extracts the information from the QUAST output file.
    """
    input:
        TSV = rules.polishing_medaka_quast.output.TSV
    output:
        INFORMS = Path(config['working_dir']) / 'medaka' / 'quast' / 'informs.io'
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'quast'
    run:
        from camel.app.tools.quast.quastinformextractor import QuastInformExtractor
        quast_inform_extractor = QuastInformExtractor(camel)
        SnakemakeUtils.add_pickle_inputs(quast_inform_extractor, input)
        step = Step(str(rule), quast_inform_extractor, camel, params.running_dir)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(quast_inform_extractor, output)

rule polishing_medaka_report:
    """
    Creates the HTML report for the assembly.
    """
    input:
        FASTA_Raw = Path(config['working_dir']) / medaka_polishing.INPUT_ASSEMBLY_FASTA,
        FASTA_Contig = rules.polishing_medaka_stitch.output.FASTA,
        INFORMS_spades = rules.polishing_medaka_stitch.output.INFORMS,
        INFORMS_quast = rules.polishing_medaka_quast_extract_informs.output.INFORMS
    output:
        VAL_HTML = Path(config['working_dir']) / medaka_polishing.OUTPUT_ASSEMBLY_REPORT
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'report',
        sample_name = config['sample_name']
    run:
        from camel.app.tools.pipelines.assembly.htmlreporterassembly import HtmlReporterAssembly
        from camel.app.io.tooliovalue import ToolIOValue
        reporter = HtmlReporterAssembly(camel)
        reporter.add_input_files({'SAMPLE_NAME': [ToolIOValue(params.sample_name)],
                                  'ASSEMBLER': [ToolIOValue('Medaka')]})
        SnakemakeUtils.add_pickle_inputs(reporter, input)
        step = Step(str(rule), reporter, camel, params.running_dir)
        step.run_step()
        SnakemakeUtils.dump_tool_outputs(reporter, output)

rule polishing_medaka_dump_summary_info:
    """
    Dumps the summary information from the assembly pipeline.
    """
    input:
        INFORMS_quast = rules.assembly_flye_quast_extract_informs.output.INFORMS
    output:
        Path(config['working_dir']) / medaka_polishing.OUTPUT_ASSEMBLY_SUMMARY
    params:
        running_dir = Path(config['working_dir']) / 'medaka' / 'summary'
    run:
        quast_informs = SnakemakeUtils.load_object(Path(input.INFORMS_quast))
        summary_data = [
            ('assembly_n50', quast_informs['contig']['N50']),
            ('assembly_nb_contigs', quast_informs['contig']['# contigs']),
            ('assembly_total_length', quast_informs['genome']['Total length'])
        ]
        with open(output[0], 'w') as handle:
            for key, value in summary_data:
                handle.write(f'{key}\t{value}')
                handle.write('\n')

rule polishing_medaka_empty_report:
    """
    Creates an empty report for the gene detection when plasmidSPAdes assembly fails.
    """
    output:
        VAL_HTML = Path(config['working_dir']) / medaka_polishing.OUTPUT_ASSEMBLY_REPORT_EMPTY
    run:
        from camel.app.snakemake.snakemakeutils import SnakemakeUtils
        from camel.app.snakemake.snakepipelineutils import SnakePipelineUtils
        SnakePipelineUtils.create_empty_report_section("Medaka polishing", Path(output.VAL_HTML))
