# This file handles the functions common to the different trimming workflows.
from pathlib import Path
from typing import Dict, Any, List

from camel.resources.snakefile import trimming_illumina, trimming_iontorrent


def get_read_type(config: Dict[str, Any]) -> str:
    """
    Returns the read type from the Snakemake configuration
    """
    if 'read_type' not in config:
        return 'illumina'
    elif config['read_type'] in ('illumina', 'iontorrent'):
        return config['read_type']
    raise ValueError(f"Invalid read type in config: {config['read_type']}")


def get_trimming_report(config: Dict[str, Any]) -> Path:
    """
    Returns the path to the read trimming report.
    :param config: Snakemake configuration
    :return: Path to read trimming report
    """
    if get_read_type(config) == 'illumina':
        relative_path = trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_REPORT
    else:
        relative_path = trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_REPORT
    return Path(config['working_dir']) / relative_path


def get_trimming_summary(config: Dict[str, Any]) -> Path:
    """
    Returns the path to the read trimming summary file.
    :param config: Snakemake configuration
    :return: Path to read trimming summary file
    """
    if get_read_type(config) == 'illumina':
        relative_path = trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_SUMMARY
    else:
        relative_path = trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_SUMMARY
    return Path(config['working_dir']) / relative_path


def get_trimming_command_informs(config: Dict[str, Any]) -> List[Path]:
    """
    Returns a list of informs IO files for the read trimming steps.
    :return: List of informs IO files
    """
    if get_read_type(config) == 'illumina':
        io_paths = [trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_INFORMS]
    else:
        io_paths = [
            trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_INFORMS_FILT_LEN,
            trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_INFORMS_FILT_QUAL]
    return [Path(config['working_dir']) / io for io in io_paths]


def get_trimming_dir(config: Dict[str, Any]) -> Path:
    """
    Returns the read trimming directory.
    :param config: Snakemake configuration
    :return: Path to read trimming folder
    """
    if get_read_type(config) == 'illumina':
        dir_ = trimming_illumina.FOLDER_TRIMMING_ILLUMINA
    else:
        dir_ = trimming_iontorrent.FOLDER_TRIMMING_IONTORRENT
    return Path(config['working_dir']) / dir_


def get_trimming_fastqc(key: str, config: Dict[str, Any]) -> Path:
    """
    Returns the data file generated by FastQC.
    :param key: Key for the step ('pre' or 'post' trimming)
    :param config: Snakemake config
    :return: Path to FastQC file
    """
    if get_read_type(config) == 'illumina':
        if key == 'pre':
            return Path(config['working_dir']) / trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_FASTQC_TXT_PRE
        elif key == 'post':
            return Path(config['working_dir']) / trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_FASTQC_TXT_POST
    else:
        if key == 'pre':
            return Path(config['working_dir']) / trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_FASTQC_PRE
        elif key == 'post':
            return Path(config['working_dir']) / trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_FASTQC_POST
    raise ValueError("Cannot find FastQC file for given key")
