# This file handles the functions common to the different trimming workflows.
from pathlib import Path
from typing import Dict, Any, List

from camel.resources.snakefile import trimming_illumina, trimming_iontorrent, trimming_ont


def get_read_type(config: Dict[str, Any], read_type: str = None) -> str:
    """
    Returns the read type from the Snakemake configuration
    """
    if read_type:
        print("HERE!!!")
        print(read_type)
        if read_type not in ['illumina', 'iontorrent', 'nanopore']:
            raise ValueError(f"Invalid read type in config: {read_type}")
        return read_type
    else:
        if 'read_type' not in config:
            return 'illumina'
        elif config['read_type'] in ('illumina', 'iontorrent', 'nanopore'):
            return config['read_type']
        raise ValueError(f"Invalid read type in config: {config['read_type']}")


def get_trimming_report(config: Dict[str, Any], read_type: str = None) -> Path:
    """
    Returns the path to the read trimming report.
    :param read_type: read type
    :param config: Snakemake configuration
    :return: Path to read trimming report
    """
    if read_type is None:
        read_type = config['read_type']
    if read_type == 'illumina':
        relative_path = trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_REPORT
    elif read_type == 'iontorrent':
        relative_path = trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_REPORT
    else:
        relative_path = trimming_ont.OUTPUT_TRIMMING_ONT_REPORT
    return Path(config['working_dir']) / relative_path


def get_trimming_summary(config: Dict[str, Any], read_type: str = None) -> Path:
    """
    Returns the path to the read trimming summary file.
    :param read_type: read_type
    :param config: Snakemake configuration
    :return: Path to read trimming summary file
    """
    if get_read_type(config, read_type) == 'illumina':
        relative_path = trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_SUMMARY
    elif get_read_type(config, read_type) == 'iontorrent':
        relative_path = trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_SUMMARY
    else:
        relative_path = trimming_ont.OUTPUT_TRIMMING_ONT_SUMMARY
    return Path(config['working_dir']) / relative_path


def get_trimming_command_informs(config: Dict[str, Any], read_type: str = None) -> List[Path]:
    """
    Returns a list of informs IO files for the read trimming steps.
    :param config: Snakemake configuration
    :param read_type: read type
    :return: List of informs IO files
    """
    if get_read_type(config, read_type) == 'illumina':
        io_paths = [trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_INFORMS]
    elif get_read_type(config, read_type) == 'iontorrent':
        io_paths = [
            trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_INFORMS_FILT_LEN,
            trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_INFORMS_FILT_QUAL]
    else:
        io_paths = [trimming_ont.OUTPUT_TRIMMING_ONT_INFORMS]
    return [Path(config['working_dir']) / io for io in io_paths]


def get_trimming_dir(config: Dict[str, Any], read_type: str = None) -> Path:
    """
    Returns the read trimming directory.
    :param read_type: read type
    :param config: Snakemake configuration
    :return: Path to read trimming folder
    """
    if get_read_type(config, read_type) == 'illumina':
        dir_ = trimming_illumina.FOLDER_TRIMMING_ILLUMINA
    elif get_read_type(config, read_type) == 'iontorrent':
        dir_ = trimming_iontorrent.FOLDER_TRIMMING_IONTORRENT
    else:
        dir_ = trimming_ont.DIRECTORY_TRIMMING_ONT
    return Path(config['working_dir']) / dir_


def get_trimming_fastqc(key: str, config: Dict[str, Any], read_type: str = None) -> Path:
    """
    Returns the data file generated by FastQC.
    :param read_type: read type
    :param key: Key for the step ('pre' or 'post' trimming)
    :param config: Snakemake config
    :return: Path to FastQC file
    """
    if get_read_type(config, read_type) == 'illumina':
        if key == 'pre':
            return Path(config['working_dir']) / trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_FASTQC_TXT_PRE
        elif key == 'post':
            return Path(config['working_dir']) / trimming_illumina.OUTPUT_TRIMMING_ILLUMINA_FASTQC_TXT_POST
    elif get_read_type(config, read_type) == 'iontorrent':
        if key == 'pre':
            return Path(config['working_dir']) / trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_FASTQC_PRE
        elif key == 'post':
            return Path(config['working_dir']) / trimming_iontorrent.OUTPUT_TRIMMING_IONTORRENT_FASTQC_POST
    else:
        if key == 'pre':
            return Path(config['working_dir']) / trimming_ont.OUTPUT_TRIMMING_ONT_NANOPLOT_TXT_PRE
        elif key == 'post':
            return Path(config['working_dir']) / trimming_ont.OUTPUT_TRIMMING_ONT_NANOPLOT_TXT_POST
    raise ValueError("Cannot find FastQC file for given key")
