from pathlib import Path

DIRECTORY_TRIMMING_ONT = Path('trimming_ont')
SNAKEFILE_TRIMMING_ONT = f'{Path(__file__).parent / Path(__file__).stem}.smk'

INPUT_ONT_FASTQ = DIRECTORY_TRIMMING_ONT / 'input' / 'fastq.io'

# Report and summary
OUTPUT_TRIMMING_ONT_REPORT = DIRECTORY_TRIMMING_ONT / 'report' / 'html.io'
OUTPUT_TRIMMING_ONT_SUMMARY = DIRECTORY_TRIMMING_ONT / 'summary' / 'summary_out.tsv'

# Trimming
OUTPUT_TRIMMING_ONT_READS = DIRECTORY_TRIMMING_ONT / 'filtlong' / 'fastq.io'
OUTPUT_TRIMMING_ONT_INFORMS = DIRECTORY_TRIMMING_ONT / 'filtlong' / 'informs.io'
OUTPUT_TRIMMING_ONT_DICT = DIRECTORY_TRIMMING_ONT / 'fastq_all.io'

# NanoPlot
OUTPUT_TRIMMING_ONT_NANOPLOT_TXT_PRE = DIRECTORY_TRIMMING_ONT / 'nanoplot-pre' / 'txt.io'
OUTPUT_TRIMMING_ONT_NANOPLOT_HTML_PRE = DIRECTORY_TRIMMING_ONT / 'nanoplot-pre' / 'html.io'
OUTPUT_TRIMMING_ONT_NANOPLOT_INFORMS_PRE = DIRECTORY_TRIMMING_ONT / 'nanoplot-pre' / 'informs.io'
OUTPUT_TRIMMING_ONT_NANOPLOT_TXT_POST = DIRECTORY_TRIMMING_ONT / 'nanoplot-post' / 'txt.io'
OUTPUT_TRIMMING_ONT_NANOPLOT_HTML_POST = DIRECTORY_TRIMMING_ONT / 'nanoplot-post' / 'html.io'
OUTPUT_TRIMMING_ONT_NANOPLOT_INFORMS_POST = DIRECTORY_TRIMMING_ONT / 'nanoplot-post' / 'informs.io'
