import logging

from camel.app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from camel.app.tools.tool import Tool


class QualityCriteriaChecker(Tool):

    """
    Tools that checks if the quality of the data is sufficient to proceed.
    """

    def __init__(self, camel):
        """
        Initialize this tool.
        :param camel: CAMEL instance
        """
        super(QualityCriteriaChecker, self).__init__('Quality Criteria Checker', '0.1', camel)

    def _check_input(self):
        """
        Checks if the input is valid.
        :return: None
        """
        if 'cgmlst' not in self._input_informs:
            raise InvalidInputSpecificationError("No cgMLST information found")
        if 'coverage' not in self._input_informs:
            raise InvalidInputSpecificationError("No coverage information found")
        if 'mapping' not in self._input_informs:
            raise InvalidInputSpecificationError("No mapping information found")
        if 'fastqc_checks' not in self._input_informs:
            raise InvalidInputSpecificationError("No FASTQC checks information found")
        super(QualityCriteriaChecker, self)._check_input()

    def _execute_tool(self):
        """
        Executes this tool.
        :return: None
        """
        self.informs['warnings'] = []
        self.informs['fails'] = []
        self.__check_additional_fastqc_tests()
        self.__check_assembly_mapping_rate()
        self.__check_coverage()
        self.__check_cgmlst()

    def __check_additional_fastqc_tests(self):
        """
        Checks the additional quality tests on the data generated by FastQC.
        :return: None
        """
        logging.debug("Checking FastQC additional checks")
        informs = self._input_informs['fastqc_checks']
        for input_file, index in zip(informs['samples'], list(range(0, len(informs['samples'])))):
            for test_name, state in informs['tests'].items():
                if state[index] == 'Warn':
                    self.informs['warnings'].append("'{}' had a warning for the '{}' test".format(
                        input_file, test_name))
                if state[index] == 'Fail':
                    self.informs['fails'].append("'{}' does not pass '{}' test".format(input_file, test_name))

    def __check_assembly_mapping_rate(self):
        """
        Checks the assembly mapping rate.
        :return: None
        """
        logging.debug("Checking assembly mapping rate")
        mapping_rate = float(self._input_informs['mapping']['stats_map_rate'])
        if mapping_rate < float(self._parameters['minimal_mapping_rate_fail'].value):
            self.informs['fails'].append('Not enough reads mapped against assembly ({}% required)'.format(
                self._parameters['minimal_mapping_rate_fail'].value))
        elif mapping_rate < float(self._parameters['minimal_mapping_rate_warn'].value):
            self.informs['warnings'].append('Number of reads mapped against assembly is low')

    def __check_coverage(self):
        """
        Checks the coverage.
        :return: None
        """
        logging.debug("Checking coverage")
        coverage = float(self._input_informs['coverage']['median_depth'])
        if coverage < float(self._parameters['minimal_coverage_fail'].value):
            self.informs['fails'].append('Coverage is not sufficient ({}x required)'.format(
                self._parameters['minimal_coverage_fail'].value))
        elif coverage < float(self._parameters['minimal_coverage_warn'].value):
            self.informs['warnings'].append('Coverage is low')

    def __check_cgmlst(self):
        """
        Checks if the fraction of detected cgMLST genes is sufficient.
        :return: None
        """
        cgmlst_stats = self._input_informs['cgmlst']
        fraction_of_genes_detected = 100.0 * float(cgmlst_stats['hits_found']) / cgmlst_stats['nb_of_loci']
        min_fail = self._parameters['minimal_cgmlst_percentage_genes_fail'].value
        if fraction_of_genes_detected < float(min_fail):
            self.informs['fails'].append('Not enough cgMLST genes detected ({}% required)'.format(min_fail))
        elif fraction_of_genes_detected < float(self._parameters['minimal_cgmlst_percentage_genes_warn'].value):
            self.informs['warnings'].append('Low amount of cgMLST genes detected')
