################################################################################################
# This YAML file contains the additional configuration data for the Hybrid assembly pipeline.  #
# The values are added to the configuration data constructed by the BasePipeline class.        #
################################################################################################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Li_2009-samtools
    - Clark_2013-ale
    - Garrison_2012-freebayes
    - Kolmogorov_2019-flye
    - oxford_2023-medaka
    - Sedlazeck_2018-sniffles
    - Smolka_2022-sniffles
    - Wick_2017-unicycler
    - Wick_2022-polypolish
    - Zimin_2020-polca

