################################################################################################
# This YAML file contains the additional configuration data for the hybrid assembly pipeline.  #
# The values are added to the configuration data constructed by the BasePipeline class.        #
################################################################################################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Li_2009-samtools
    - Clark_2013-ale
    - Garrison_2012-freebayes
    - Kolmogorov_2019-flye
    - Sedlazeck_2018-sniffles
    - Wick_2017-unicycler
    - Wick_2022-polypolish
    - Zimin_2020-polca
    - Bouras_2024-pypolca

####################
# Reference genome #
####################
reference:
  expected_gc: null
  expected_size: null

#########################
# Tool specific options #
#########################
downsampling:
  disabled: true

assembly:
  flye:
    genome_size: {expected_size}
    meta: {is_meta}
    nano_corr: {nano_corr}
    nano_hq: {nano_hq}
    nano_raw: {nano_raw}
  min_contig_length: 1000
  no_alt_contigs: true

polishing:
  medaka:
    consensus:
      model: {medaka_model}

freebayes:
  min_alternate_count: {freebayes_min_alternate_count}
  min_alternate_fraction: {freebayes_min_alternate_fraction}
  ploidy: {freebayes_ploidy}

clair3:
  haploid_precise: {clair3_haploid_precise}
  long_indel: {clair3_long_indel}
  model_path: {clair3_model_path}

sniffles:
  mapq: {sniffles_mapq}
  min_support: {sniffles_min_support}
  min_svlen: {sniffles_min_svlen}
