import json
from pathlib import Path

import pandas as pd

from camel.app.core.io.tooliofile import ToolIOFile
from camel.app.core.snakemake.step import Step
from camel.app.core.snakemake import snakemakeutils
from camel.app.core.snakemake import snakepipelineutils

rule all:
    input:
        BAM = 'sam_to_bam/bam.io',
        JSON = 'stats_mapping.json',
        JSON_informs = 'informs_all.json'

rule bwa_index_ref:
    """
    Creates a BWA index for the reference genome.
    """
    input:
        FASTA = config['input']['FASTA']
    output:
        FASTA = 'bwa/index/fasta.iob'
    params:
        dir_ = 'bwa/index'
    run:
        from camel.app.tools.bwa.bwaindex import BWAIndex
        bwa_index = BWAIndex()

        # Create the working directory
        dir_ = Path(params.dir_).absolute()
        path_symlink = dir_ / Path(input.FASTA).name
        path_symlink.symlink_to(Path(input.FASTA))

        # Create the index
        step = Step(rule_name=str(rule), tool=bwa_index, dir_=Path(str(params.dir_)).absolute())
        bwa_index.add_input_files({'FASTA_REF': [ToolIOFile(path_symlink)]})
        step.run()
        snakemakeutils.dump_tool_output(bwa_index, 'INDEX_GENOME_PREFIX', Path(output.FASTA))

rule bwa_map_reads_pe:
    """
    Maps the Illumina PE reads using BWA.
    """
    input:
        FASTA = rules.bwa_index_ref.output.FASTA,
        FASTQ = 'input/fq_dict.io'
    output:
        SAM = 'bwa/map_pe/sam.io',
        INFORMS = 'bwa/map_pe/informs.io'
    threads: 16
    params:
        dir_ = 'bwa/map_pe'
    run:
        from camel.app.tools.bwa.bwamap import BWAMap
        bwa_map = BWAMap()
        snakemakeutils.add_pickle_input(bwa_map, 'INDEX_GENOME_PREFIX', Path(input.FASTA))
        bwa_map.add_input_files(snakepipelineutils.extract_fq_input(Path(
            input.FASTQ), drop_empty=True, read_type='PE'))
        bwa_map.run(Path(str(params.dir_)))
        snakemakeutils.dump_tool_outputs(bwa_map, output)

rule bwa_map_reads_se:
    """
    Maps the Illumina SE reads using BWA.
    """
    input:
        FASTA = rules.bwa_index_ref.output.FASTA,
        FASTQ = 'input/fq_dict.io'
    output:
        SAM = 'bwa/map_se_{key}/sam.io',
        INFORMS = 'bwa/map_se_{key}/informs.io'
    threads: 16
    params:
        dir_ = lambda wildcards: f'bwa/map_se_{wildcards.key}',
        key = lambda wildcards: wildcards.key
    run:
        from camel.app.core.utils import sambamutils
        from camel.app.scriptutils.fastqinput import FastqInput
        from camel.app.tools.bwa.bwamap import BWAMap

        fq_dict = FastqInput.from_fq_dict(Path(input.FASTQ), 'illumina')
        fq_in = fq_dict.se_fwd if params.key == 'fwd' else fq_dict.se_rev
        if fq_in is None:
            # If there are no SE reads -> create empty output file
            path_out = Path(str(params.dir_), 'empty.sam')
            path_fasta = snakemakeutils.load_object(Path(input.FASTA))[0].value
            sambamutils.create_empty(path_out, path_fasta, compress=False)
            snakemakeutils.dump_object([ToolIOFile(path_out)], Path(output.SAM))
            Path(output.INFORMS).touch()
        else:
            # Map SE reads
            bwa_map = BWAMap()
            snakemakeutils.add_pickle_input(bwa_map, 'INDEX_GENOME_PREFIX', Path(input.FASTA))
            bwa_map.add_input_files({'FASTQ_SE': fq_in})
            bwa_map.run(Path(str(params.dir_)))
            snakemakeutils.dump_tool_outputs(bwa_map, output)

rule bwa_map_merge_sam:
    """
    Merges the SAM files generated by BWA.
    """
    input:
        SAM_pe = rules.bwa_map_reads_pe.output.SAM,
        SAM_se_fwd = str(rules.bwa_map_reads_se.output.SAM).format(key='fwd'),
        SAM_se_rev = str(rules.bwa_map_reads_se.output.SAM).format(key='rev'),
        INFORMS_pe = rules.bwa_map_reads_pe.output.INFORMS,
        INFORMS_se_fwd = str(rules.bwa_map_reads_se.output.INFORMS).format(key='fwd'),
        INFORMS_se_rev = str(rules.bwa_map_reads_se.output.INFORMS).format(key='rev')
    output:
        SAM = 'bwa/map/sam.io',
        INFORMS = 'bwa/map/informs.io'
    params:
        dir_ = 'bwa/map'
    run:
        from camel.app.core.utils import sambamutils
        from camel.app.tools.samtools.samtoolsmerge import SamtoolsMerge
        merge = SamtoolsMerge()
        merge.update_parameters(output_filename='bwa_merged.sam')

        # Collect non-empty SAM files
        sam_input = snakemakeutils.load_object(Path(input.SAM_pe)) \
                    + snakemakeutils.load_object(Path(input.SAM_se_fwd)) \
                    + snakemakeutils.load_object(Path(input.SAM_se_rev))
        sam_input = [io for io in sam_input if not sambamutils.is_empty(io.path)]
        if len(sam_input) == 0:
            raise RuntimeError(f'All SAM files are empty')

        # Run samtools merge
        merge.add_input_files({'SAM': sam_input})
        merge.run(Path(str(params.dir_)))
        snakemakeutils.dump_tool_output(merge, 'SAM', Path(output.SAM))

        # Collect informs
        informs = []
        for path_inform in [Path(x) for x in (input.INFORMS_pe, input.INFORMS_se_fwd, input.INFORMS_se_rev)]:
            if path_inform.stat().st_size == 0:
                logger.info(f'Skipping empty informs: {path_inform}')
                continue
            informs.append(snakemakeutils.load_object(path_inform))
        informs.append(merge.informs)
        snakemakeutils.dump_object(informs, Path(output.INFORMS))

rule minimap2_map_reads:
    """
    Maps ONT reads using Minimap2.
    """
    input:
        FASTA = config['input']['FASTA'],
        FASTQ = 'input/fq_dict.io'
    output:
        SAM = 'minimap2/map/sam.io',
        INFORMS = 'minimap2/map/informs.io'
    params:
        dir_ = 'minimap2/map'
    threads: 16
    run:
        from camel.app.tools.minimap2.minimap2mapping import Minimap2Mapping
        minimap2 = Minimap2Mapping()

        # Create the working directory
        dir_ = Path(params.dir_).absolute()
        dir_.mkdir(exist_ok=True, parents=True)

        # Add inputs
        minimap2.add_input_files({'FASTA': [ToolIOFile(Path(input.FASTA))]})
        fq_se_in = snakepipelineutils.extract_fq_input(Path(input.FASTQ), read_type='SE', key_se='FASTQ')
        minimap2.add_input_files(fq_se_in)

        # Run tool and collect output
        minimap2.update_parameters(threads=threads)
        minimap2.run(dir_)
        snakemakeutils.dump_tool_outputs(minimap2, output)

rule sam_to_bam:
    """
    Converts the output SAM file to sorted BAM format.
    """
    input:
        SAM = f"{config['mapper']}/map/sam.io"
    output:
        BAM = 'sam_to_bam/bam.io'
    params:
        dir_ = 'sam_to_bam',
        name = f"{config['input']['prefix']}.bam"
    run:
        from camel.app.core.piping import pipeutils
        from camel.app.tools.samtools.samtoolssort import SamtoolsSort
        from camel.app.tools.samtools.samtoolsview import SamtoolsView
        from camel.app.tools.samtools.samtoolsindex import SamtoolsIndex

        # View and sort
        samtools_view = SamtoolsView()
        samtools_sort = SamtoolsSort()
        snakemakeutils.add_pickle_input(samtools_view, 'SAM', Path(input.SAM))
        pipeutils.run_as_pipe([samtools_view, samtools_sort], Path(str(params.dir_)).absolute())

        # Create index
        samtools_index = SamtoolsIndex()
        samtools_index.update_parameters(output_filename=params.name)
        samtools_index.add_input_files({'BAM': samtools_sort.tool_outputs['BAM']})
        samtools_index.run(Path(str(params.dir_)).absolute())
        snakemakeutils.dump_tool_output(samtools_index, 'BAM', Path(output.BAM))

rule samtools_depth:
    """
    Runs samtools depth on the generated BAM file.
    """
    input:
        BAM = rules.sam_to_bam.output.BAM
    output:
        TSV = 'depth/tsv.io',
        INFORMS = 'depth/informs.io'
    params:
        max_depth = 100_000,
        name = f"depth_{config['input']['prefix']}.tsv",
        dir_ = 'depth'
    run:
        from camel.app.tools.samtools.samtoolsdepth import SamtoolsDepth
        depth = SamtoolsDepth()
        snakemakeutils.add_pickle_inputs(depth, input)
        depth.update_parameters(
            maximum_coverage_depth=params.max_depth, output_filename=params.name, output_all_positions_absolutely=True)
        depth.run(Path(params.dir_).absolute())
        snakemakeutils.dump_tool_outputs(depth, output)

rule samtools_flagstat:
    """
    Runs samtools flagstat to determine the mapping rate.
    """
    input:
        BAM = rules.sam_to_bam.output.BAM
    output:
        INFORMS = 'flagstat/txt.io'
    params:
        dir_ = 'flagstat'
    run:
        from camel.app.tools.samtools.samtoolsflagstat import SamtoolsFlagstat
        flagstat = SamtoolsFlagstat()
        snakemakeutils.add_pickle_inputs(flagstat, input)
        flagstat.run(Path(params.dir_).absolute())
        # Calculate mapping rate
        try:
            flagstat.informs['mapping_rate'] = flagstat.informs['mapped'][0] / flagstat.informs['total'][0]
        except ZeroDivisionError:
            flagstat.informs['mapping_rate'] = None
        snakemakeutils.dump_tool_outputs(flagstat, output)

rule collect_low_depth_regions:
    """
    Collects low depth regions.
    """
    input:
        FASTA = config['input']['FASTA'],
        BAM = rules.sam_to_bam.output.BAM
    output:
        BED = 'low_depth/bed.io',
        INFORMS = 'low_depth/informs.io'
    params:
        dir_ = 'low_depth',
        gap_depth_cutoff = config['low_depth'].get('gap_depth_cutoff'),
        gap_len_cutoff = config['low_depth'].get('gap_len_cutoff')
    run:
        from camel.app.tools.pipelines.viral_consensus.collectlowdepthregions import CollectLowDepthRegions
        collect_low_depth = CollectLowDepthRegions()
        snakemakeutils.add_pickle_input(collect_low_depth, 'BAM', Path(input.BAM))
        collect_low_depth.update_parameters(
            gap_depth_cutoff=params.gap_depth_cutoff, gap_len_cutoff=params.gap_len_cutoff)
        collect_low_depth.add_input_files({'FASTA': [ToolIOFile(Path(input.FASTA))]})
        collect_low_depth.run(Path(params.dir_).absolute())
        snakemakeutils.dump_tool_outputs(collect_low_depth, output)

rule combine_stats:
    """
    Combines the read mapping statistics.
    """
    input:
        TSV = rules.samtools_depth.output.TSV,
        INFORMS_flagstat = rules.samtools_flagstat.output.INFORMS,
        INFORMS_low_cov = rules.collect_low_depth_regions.output.INFORMS
    output:
        JSON = 'stats_mapping.json'
    run:
        from scipy.stats import iqr

        # Parse informs
        informs_flagstat = snakemakeutils.load_object(Path(input.INFORMS_flagstat))
        informs_low_cov = snakemakeutils.load_object(Path(input.INFORMS_low_cov))

        # Parse depth stats
        path_tsv = snakemakeutils.load_object(Path(input.TSV))[0].path
        data_depth = pd.read_table(path_tsv, names=['chr', 'pos', 'depth'])
        stats_out = {
            'total': {
                'length': len(data_depth),
                'depth_median': data_depth['depth'].median(),
                'depth_iqr': iqr(data_depth['depth']),
                'covered_rate': sum(data_depth['depth'] > 0) / len(data_depth),
                'mapping_rate': informs_flagstat['mapping_rate'],
                'low_cov_regions': informs_low_cov['total']['nb_gaps'],
                'low_cov_total_bp': informs_low_cov['total']['total_gap_size'],
                'low_cov_perc': informs_low_cov['total']['perc_gaps'],
            },
            'by_chr': {
                chr: {
                    'length': len(data_chr),
                    'depth_median': data_chr['depth'].median(),
                    'depth_iqr': iqr(data_chr['depth']),
                    'covered_rate': sum(data_chr['depth'] > 0) / len(data_chr),
                    'low_cov_regions': informs_low_cov['by_seq_id'][chr]['nb_gaps'],
                    'low_cov_total_bp': informs_low_cov['by_seq_id'][chr]['total_gap_size'],
                    'low_cov_perc': informs_low_cov['by_seq_id'][chr]['perc_gaps']
                } for chr, data_chr in data_depth.groupby('chr')
            }
        }
        with open(output.JSON, 'w') as handle:
            json.dump(stats_out, handle, indent=2)

rule collect_informs:
    """
    Collects the informs (commands, versions, etc).
    """
    input:
        INFORMS_mapping = f"{config['mapper']}/map/informs.io",
        INFORMS_depth = rules.samtools_depth.output.INFORMS,
        INFORMS_flagstat = rules.samtools_flagstat.output.INFORMS
    output:
        JSON = 'informs_all.json'
    run:
        data_out = []
        for path_in in [Path(x) for x in (input.INFORMS_mapping, input.INFORMS_depth, input.INFORMS_flagstat)]:
            informs = snakemakeutils.load_object(path_in)
            if isinstance(informs, list):
                data_out.extend(informs)
            else:
                data_out.append(snakemakeutils.load_object(path_in))
        with open(output.JSON, 'w') as handle:
            json.dump(data_out, handle, indent=2)
