import json
from pathlib import Path

from camelcore.app.command import Command
from camelcore.app.io.tooliofile import ToolIOFile

from camel.app.core.snakemake.step import Step
from camel.app.loggers import initialize_logging
from camel.app.core.snakemake import snakemakeutils


initialize_logging()


rule samtools_ampliconclip:
    """
    Clips the primer sequences.
    """
    input:
        BAM = config['input']['bam']
    output:
        BAM = 'ampliconclip/tool/alignment_clipped.bam',
        INFORMS = 'ampliconclip/tool/informs.io'
    params:
        path_bed = config.get('bed_primers')
    run:
        from camel.app.tools.samtools.samtoolsampliconclip import SamtoolsAmpliconClip

        # Perform amplicon clipping
        ampliconclip = SamtoolsAmpliconClip()
        step = Step(str(rule), ampliconclip, dir_=snakemakeutils.get_rule_dir(output))
        ampliconclip.add_input_files({
            'BAM': [ToolIOFile(Path(input.BAM).absolute())],
            'BED': [ToolIOFile(Path(params.path_bed).absolute())]
        })
        ampliconclip.update_parameters(
            both_ends=True,
            output=str(Path(output.BAM).absolute()),
        )
        step.run_step()
        snakemakeutils.dump_io_outputs(ampliconclip, output, keys=['INFORMS'])

rule samtools_ampliconclip_sort:
    """
    Sorts and indexes the output file generated by samtools ampliconclip.
    """
    input:
        BAM = rules.samtools_ampliconclip.output.BAM
    output:
        BAM = 'ampliconclip/sorted/alignment_clipped.sorted.bam'
    run:
        from camel.app.tools.samtools.samtoolsindex import SamtoolsIndex
        from camel.app.tools.samtools.samtoolssort import SamtoolsSort

        samtools_sort = SamtoolsSort()
        step = Step(str(rule), samtools_sort, dir_=snakemakeutils.get_rule_dir(output))
        samtools_sort.add_input_files({
            'BAM': [ToolIOFile(Path(input.BAM).absolute())]
        })
        samtools_sort.run()

        # Index the BAM file
        samtools_index = SamtoolsIndex()
        samtools_index.add_input_files({
            'BAM': samtools_sort.tool_outputs['BAM']
        })
        samtools_index.update_parameters(output_filename=str(Path(output.BAM).absolute()))
        samtools_index.run(Path(output.BAM).parent)

rule create_bam_for_seq_id:
    """
    Creates a BAM file for the given sequence id.
    """
    input:
        BAM = config['input']['bam'] if config.get('primers_bed') is None else rules.samtools_ampliconclip_sort.output.BAM
    output:
        BAM = 'by_seq_id/{seq_id}/{seq_id}.bam',
        INFORMS = 'by_seq_id/{seq_id}/informs.io'
    params:
        seq_id = lambda wildcards: wildcards.seq_id
    run:
        from camel.app.tools.samtools.samtoolsview import SamtoolsView

        samtools_view = SamtoolsView()
        step = Step(rule_name=str(rule), tool=samtools_view, dir_=snakemakeutils.get_rule_dir(output))
        samtools_view.add_input_files({'BAM': [ToolIOFile(Path(input.BAM).absolute())]})
        samtools_view.update_parameters(
            output_filename=str(Path(output.BAM).absolute()),
            output_format='BAM',
            keep_header=False,
            regions=str(params.seq_id)
        )
        step.run()
        snakemakeutils.dump_io_outputs(samtools_view, output, keys=['INFORMS'])

rule downsample_bam:
    """
    Down-samples the BAM file to the required coverage (if needed).
    """
    input:
        BAM = rules.create_bam_for_seq_id.output.BAM
    output:
        BAM = 'by_seq_id/{seq_id}/{seq_id}-ds.bam'
    params:
        ratio = lambda wildcards: config['downsampling'][wildcards.seq_id]
    run:
        from camel.app.tools.samtools.samtoolsview import SamtoolsView

        if params.ratio is not None:
            samtools_view = SamtoolsView()
            step = Step(str(rule), samtools_view, dir_=snakemakeutils.get_rule_dir(output))
            samtools_view.add_input_files({
                'BAM': [ToolIOFile(Path(input.BAM).absolute())]
            })
            samtools_view.update_parameters(
                output_filename=str(Path(output.BAM).absolute()),
                output_format='BAM',
                subsample=str(params.ratio)
            )
            step.run()
        else:
            Path(output.BAM).absolute().symlink_to(Path(input.BAM).absolute())

rule extract_fq_ont:
    """
    Extracts FASTQ files for single-end data.
    """
    input:
        BAM = rules.downsample_bam.output.BAM
    output:
        FASTQ = 'by_seq_id/{seq_id}/fastq/ont/{seq_id}.fastq',
        INFORMS = 'by_seq_id/{seq_id}/fastq/ont/informs_{seq_id}.io'
    run:
        import shutil
        from camel.app.tools.samtools.samtoolsfastq import SamtoolsFastq
        samtools_fastq = SamtoolsFastq()
        samtools_fastq.add_input_files({
            'BAM': [ToolIOFile(Path(str(input.BAM)).absolute())]
        })
        samtools_fastq.update_parameters(read_other='reads_se.fastq')
        step = Step(rule_name=str(rule), tool=samtools_fastq, dir_=snakemakeutils.get_rule_dir(output))
        step.run()
        snakemakeutils.dump_io_outputs(samtools_fastq, output, keys=['INFORMS'])
        shutil.move(samtools_fastq.tool_outputs['FASTQ_OTHER'][0].path, Path(output.FASTQ))

rule extract_fq_ont_merge:
    """
    Merges the extracted SE FASTQ files. 
    """
    input:
        FASTQ = [str(rules.extract_fq_ont.output.FASTQ).format(seq_id=seq_id) for seq_id in config['downsampling'].keys()]
    output:
        FQ_dict = 'merged/ont/fq_dict.io'
    params:
        dir_ = 'merged/ont'
    threads: 4
    run:
        from camelcore.app.utils import fileutils
        from camel.app.scriptutils.basepipe.fastqinput import FastqInput

        dir_ = Path(params.dir_).absolute()
        dir_.mkdir(parents=True, exist_ok=True)
        fq_out = dir_ / 'merged.fastq'
        fileutils.concatenate_files(fq_out, [Path(x).absolute() for x in input.FASTQ])
        fileutils.gzip_compress(fq_out, fq_out.with_suffix('.gz'), threads=threads)
        fq_dict = FastqInput('ont', se=[ToolIOFile(fq_out.with_suffix('.gz'))], is_trimmed=True, is_pe=False)
        snakemakeutils.dump_object(fq_dict.to_fq_dict(), Path(output.FQ_dict))

rule extract_fq_illumina:
    """
    Extracts FASTQ files for paired-end Illumina data.
    """
    input:
        BAM = rules.downsample_bam.output.BAM
    output:
        FASTQ_FWD = 'by_seq_id/{seq_id}/fastq/illumina/reads_1P.fastq',
        FASTQ_REV = 'by_seq_id/{seq_id}/fastq/illumina/reads_2P.fastq',
        FASTQ_SE = 'by_seq_id/{seq_id}/fastq/illumina/reads_single.fastq',
        FASTQ_ORPHANED = 'by_seq_id/{seq_id}/fastq/illumina/reads_orphaned.fastq',
        INFORMS = 'by_seq_id/{seq_id}/fastq/illumina/informs_{seq_id}.io'
    run:
        from camel.app.tools.samtools.samtoolsfastq import SamtoolsFastq

        samtools_fastq = SamtoolsFastq()
        step = Step(rule_name=str(rule), tool=samtools_fastq, dir_=snakemakeutils.get_rule_dir(output))
        samtools_fastq.add_input_files({
            'BAM': [ToolIOFile(Path(input.BAM).absolute())]
        })
        samtools_fastq.update_parameters(
            append_suffix=True,
            read_1=str(Path(output.FASTQ_FWD).absolute()),
            read_2=str(Path(output.FASTQ_REV).absolute()),
            singletons=str(Path(output.FASTQ_SE).absolute()),
            read_other=str(Path(output.FASTQ_ORPHANED).absolute()),
        )
        step.run()
        snakemakeutils.dump_io_outputs(samtools_fastq, output, keys=['INFORMS'])

rule split_singletons_illumina:
    """
    Splits singleton reads by mate and assembles the final FASTQ dictionary.
    """
    input:
        FASTQ_FWD = rules.extract_fq_illumina.output.FASTQ_FWD,
        FASTQ_REV = rules.extract_fq_illumina.output.FASTQ_REV,
        FASTQ_SE = rules.extract_fq_illumina.output.FASTQ_SE,
        FASTQ_ORPHANED = rules.extract_fq_illumina.output.FASTQ_ORPHANED
    output:
        FASTQ = 'by_seq_id/{seq_id}/fastq/illumina/{seq_id}_fq_dict.io'
    run:
        from camelcore.app.utils import fileutils
        from camel.app.scriptutils.basepipe.fastqinput import FastqInput
        from camel.app.tools.bbtools.demuxbyname import Demuxbyname

        dir_demux = Path(output.FASTQ).parent / 'demux'
        dir_demux.mkdir(exist_ok=True, parents=True)

        # Split singleton reads by mate (/1 → reads_1U.fastq, /2 → reads_2U.fastq)
        demuxbyname = Demuxbyname()
        demuxbyname.add_input_files({
            'FASTQ': [ToolIOFile(Path(input.FASTQ_SE).absolute())]
        })
        demuxbyname.update_parameters(
            delimiter='/',
            prefixmode='f',
            out='reads_%U.fastq'
        )
        demuxbyname.run(dir_demux)
        if len(demuxbyname.tool_outputs['FASTQ']) != 2:
            raise ValueError(f'Two FASTQ output files expected, found: {len(demuxbyname.tool_outputs["FASTQ"])}')

        # Concatenate orphaned reads into the forward unpaired file
        fq_1u_out_merged = Path(output.FASTQ).parent / 'reads-merged_1U.fastq'
        fileutils.concatenate_files(
            fq_1u_out_merged,
            [demuxbyname.tool_outputs['FASTQ'][0].path, Path(input.FASTQ_ORPHANED).absolute()])

        # Save output dictionary
        fq_dict_out = FastqInput(
            'illumina',
            pe=[ToolIOFile(Path(input.FASTQ_FWD).absolute()), ToolIOFile(Path(input.FASTQ_REV).absolute())],
            se_fwd=[ToolIOFile(fq_1u_out_merged)],
            se_rev=[demuxbyname.tool_outputs['FASTQ'][1]],
        )
        snakemakeutils.dump_object(fq_dict_out.to_fq_dict(), Path(output.FASTQ))

rule extract_fq_illumina_merge:
    """
    Merges the extracted SE FASTQ files. 
    """
    input:
        FASTQ = [str(rules.split_singletons_illumina.output.FASTQ).format(seq_id=seq_id) for seq_id in config['downsampling'].keys()]
    output:
        FQ_dict = 'merged/illumina/fq_dict.io'
    params:
        dir_ = 'merged/illumina'
    run:
        from camel.app.scriptutils.basepipe.fastqinput import FastqInput

        # Create working directory
        dir_ = Path(params.dir_).absolute()
        dir_.mkdir(parents=True, exist_ok=True)

        # Parse input FASTQ dictionaries
        fq_dicts: list[FastqInput] = [FastqInput.from_fq_dict(Path(p), 'illumina') for p in input.FASTQ]
        output_files = {
            'reads_1P.fastq.gz': [fq_dict.pe[0] for fq_dict in fq_dicts],
            'reads_2P.fastq.gz': [fq_dict.pe[1] for fq_dict in fq_dicts],
            'reads_1U.fastq.gz': [fq_dict.se_fwd[0] for fq_dict in fq_dicts],
            'reads_2U.fastq.gz': [fq_dict.se_rev[0] for fq_dict in fq_dicts],
        }
        for path_out, io_objs in output_files.items():
            command = Command(
                f"cat {' '.join(str(io.path.absolute()) for io in io_objs)} | gzip > {dir_ / path_out};")
            command.run(dir_)
            if not command.exit_code == 0:
                raise RuntimeError(f'Error merged FASTQ files: {command.exit_code}')
        fq_dict = FastqInput(
            'illumina',
            pe=[ToolIOFile(dir_ / 'reads_1P.fastq.gz'), ToolIOFile(dir_ / 'reads_2P.fastq.gz')],
            se_fwd=[ToolIOFile(dir_ / 'reads_1U.fastq.gz')],
            se_rev=[ToolIOFile(dir_ / 'reads_2U.fastq.gz')],
            is_trimmed=True, is_pe=True)
        snakemakeutils.dump_object(fq_dict.to_fq_dict(), Path(output.FQ_dict))

rule collect_informs:
    """
    Collects the informs for the workflow (limited to the first seq_id).
    """
    input:
        INFORMS_clipping = rules.samtools_ampliconclip.output.INFORMS if config.get('bed_primers') is not None else [],
        INFORMS_create_bam = str(rules.create_bam_for_seq_id.output.INFORMS).format(seq_id=next(iter(config['downsampling'].keys()))),
        INFORMS_fastq = str('by_seq_id/{seq_id}/fastq/{input_type}/informs_{seq_id}.io').format(
            input_type=config['input']['input_type'], seq_id=next(iter(config['downsampling'].keys())))
    output:
        JSON = 'informs_all.json'
    run:
        data_out = []
        for input_str in (input.INFORMS_clipping, input.INFORMS_create_bam, input.INFORMS_fastq):
            if len(str(input_str)) == 0:
                continue
            with Path(input_str).open() as handle:
                data_out.append(json.load(handle))
        with open(output.JSON, 'w') as handle:
            json.dump(data_out, handle, indent=2)
