from dataclasses import dataclass


@dataclass
class TypingHit:
    """
    This class represents a hit generated by the sequence typing assay.
    """
    locus: str
    allele_id: str
    p_ident: float
    p_covered: float

    @staticmethod
    def parse(input_str: str) -> 'TypingHit':
        """
        Parses a value from the summary output.
        :param input_str: Input string
        :return: Parsed typing hit
        """
        parts = input_str.split(',')
        try:
            p_covered = 100 * int(parts[3].split('/')[0]) / int(parts[3].split('/')[1])
        except ValueError:
            p_covered = 0
        try:
            p_ident = float(parts[2])
        except ValueError:
            p_ident = 0
        return TypingHit(parts[0], parts[1], p_ident, p_covered)

    def is_perfect(self) -> bool:
        """
        Returns True if it is a perfect hit.
        :return: True if perfect hit
        """
        return self.p_covered == 100.0 and self.p_ident == 100.0

    def matches(self, other: 'TypingHit') -> bool:
        """
        Check if two hits are matching.
        :param other: Other hit
        :return: True if hits match, false otherwise
        """
        if self.is_perfect() and other.is_perfect():
            return self.allele_id == other.allele_id
        # Otherwise, if one is perfect there is no match
        return not (self.is_perfect() or other.is_perfect())
