import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Any

from camel.app.components.genedetection.genedetectionutils import GeneDetectionUtils
from camel.app.loggers import logger


@dataclass
class GeneDetectionDBInfo:
    cluster_by_seq: Dict[str, str]
    seq_by_allele: Dict[str, str]
    metadata_by_seq: Dict[str, str]


@dataclass
class AnalysisStats:
    """
    This class is used to track performance stats for an analysis.
    """
    tp: int = 0
    fp: int = 0
    fn: int = 0
    tn: int = 0
    mismatches_fp: List[str] = field(default_factory=list)
    mismatches_fn: List[str] = field(default_factory=list)


class ValidationUtils(object):
    """
    This class contains utility functions to help with the validation of tools / pipelines.
    """

    @staticmethod
    def parse_summary_out(path_tsv: Path) -> Dict[str, str]:
        """
        Parses the tabular summary output file generated by the pipeline.
        Warning: types are not converted (everything is returned as a string)
        :param path_tsv: Path to summary file
        :return: Summary information
        """
        logger.info(f"Parsing summary info: {path_tsv}")
        with path_tsv.open(encoding='utf-8') as handle:
            return {p[0]: p[1].strip() for p in [l.split('\t') for l in handle.readlines()]}

    @staticmethod
    def get_gene_detection_db_info(db_folder: Path) -> GeneDetectionDBInfo:
        """
        Parses the information from a gene detection database folder.
        :param db_folder: Database folder
        :return: Database information
        """
        clusters_by_seq = GeneDetectionUtils.parse_clusters(
            str(db_folder / f'{db_folder.name.lower()}-clustered_80.fasta'))
        with open(str(db_folder / 'mapping.txt')) as handle:
            mapping = json.load(handle)
        metadata_by_seq = {s: GeneDetectionUtils.parse_header(header)[-1] for s, header in mapping.items()}
        seq_by_allele = {metadata['allele']: seq for seq, metadata in metadata_by_seq.items()}
        return GeneDetectionDBInfo(clusters_by_seq, seq_by_allele, metadata_by_seq)

    @staticmethod
    def parse_gene_detection_output(dir_gene_detection_out: Path) -> List[Dict[str, Any]]:
        """
        Parses the output directory generated by the gene detection workflow and returns the detected hits as a list
        of dictionaries.
        :param dir_gene_detection_out: Output directory
        :return: List of detected genes
        """
        try:
            tsv_path = list(dir_gene_detection_out.glob('**/genes-*.tsv'))[0]
        except IndexError:
            return []
        with tsv_path.open() as handle:
            header = handle.readline().strip().split('\t')
            return [{k: v for k, v in zip(header, l.strip().split('\t'))} for l in handle.readlines()]
