import logging
from pathlib import Path
from typing import Dict


class ValidationUtils(object):
    """
    This class contains utility function to help with the validation of tools / pipelines.
    """

    @staticmethod
    def parse_summary_out(path: Path) -> Dict[str, str]:
        """
        Parses the tabular summary output file generated by the pipeline.
        Warning: types are not converted (everything is returned as a string)
        :param path: Path to summary file
        :return: Summary information
        """
        logging.info(f"Parsing summary info: {path}")
        with open(str(path)) as handle:
            return {p[0]: p[1].strip() for p in [l.split('\t') for l in handle.readlines()]}
