#####################
# Pipeline settings #
#####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Gupta_2014-argannot
    - McArthur_2013-card
    - Zankari_2012-resfinder
    - Feldgarden_2019-ndaro
    - Joensen_2014-virulencefinder
    - Jaureguy_2008-pasteur
    - Jolley_2010-bigsdb

#########################
# Tool specific options #
#########################
read_trimming:
  export_fastq: '{export_fastq}'

contamination_check:
  db: /db/kraken2/latest/abfhpv/
  expected_species: Listeria monocytogenes

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: 38.0

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

############################
# Gene detection databases #
############################
gene_detection:
  # AMR
  argannot:
    path: /db/gene_detection/ARG-ANNOT

  card:
    path: /db/gene_detection/CARD

  ncbi_amr:
    path: /db/gene_detection/NCBI_AMR/
    perc_identity_cutoff: 90

  resfinder:
    path: /db/gene_detection/ResFinder
    perc_identity_cutoff: 90
    metadata:
      name: Antibiotic(s)
      key: antibiotics

  # Virulence
  virulencefinder:
    path: /db/gene_detection/VirulenceFinder-Listeria
    perc_identity_cutoff: 90
    extra_column:
      name: Protein function
      key: protein_function

  vfdb_core:
    path: /db/gene_detection/VFDB_core
    perc_identity_cutoff: 90
    metadata:
      name: Gene
      key: gene

  # Plasmid replicons
  plasmidfinder:
    path: /db/gene_detection/PlasmidFinder-gram_positive
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 60
      srst2:
        max_divergence: 5
        min_coverage: 60
    metadata:
      name: Notes
      key: notes

###################
# Sequence typing #
###################
sequence_typing:
  mlst:
    path: /db/sequence_typing/listeria/mlst
  cgmlst:
    path: /db/sequence_typing/listeria/cgmlst
    detection_method: blast
  species_confirmation:
    path: /db/sequence_typing/listeria/species_confirmation
  typing_amr:
    path: /db/sequence_typing/listeria/antibiotic_resistance
  typing_virulence:
    path: /db/sequence_typing/listeria/virulence
  metal_detergent:
    path: /db/sequence_typing/listeria/metal_detergent_resistance
  pcr_serogroup:
    path: /db/sequence_typing/listeria/serogroup
