#####################
# Pipeline settings #
#####################
citations:
  main: null
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Manni_2021-busco
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Bortolaia_2020-resfinder_4.0
    - Feldgarden_2019-ndaro
    - Joensen_2014-virulencefinder
    - Jaureguy_2008-pasteur
    - Jolley_2010-bigsdb

#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 2_944_528

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Listeria monocytogenes

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: 38.0

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

confindr:
  db: /db/confindr/0.8.1

quast:
  ref:
    fasta: /db/refgenomes/Listeria_monocytogenes/NC_003210.1.fasta
    gff3: /db/refgenomes/Listeria_monocytogenes/NC_003210.1.gff3

amrfinder:
  db: /db/amrfinder/by_version/latest

resfinder4:
  db: /db/resfinder4
  point: false

mob_suite:
  db: /db/mob_suite/latest

############################
# Gene detection databases #
############################
gene_detection:
  # AMR
  ncbi_amr:
    path: /db/gene_detection/NCBI_AMR/
    perc_identity_cutoff: 90
    metadata:
      name: Antibiotic(s)
      key: subclass

  # Virulence
  virulencefinder:
    path: /db/gene_detection/VirulenceFinder-Listeria
    perc_identity_cutoff: 90
    extra_column:
      name: Protein function
      key: protein_function
    hidden: true

  vfdb_core:
    path: /db/gene_detection/VFDB_core
    perc_identity_cutoff: 90
    metadata:
      name: Gene
      key: gene
    hidden: true

  # Plasmid replicons
  plasmidfinder:
    path: /db/gene_detection/PlasmidFinder-gram_positive
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 60
      srst2:
        max_divergence: 5
        min_coverage: 60
    metadata:
      name: Notes
      key: notes
    message:
      content: The presence of a replicon does not mean that the corresponding plasmid is present.
      category: warning

###################
# Sequence typing #
###################
sequence_typing:
  cgmlst:
    path: /db/sequence_typing/listeria/cgmlst
    detection_method: blast
  mlst:
    path: /db/sequence_typing/listeria/mlst
  pcr_serogroup:
    path: /db/sequence_typing/listeria/serogroup
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info
  species_confirmation:
    path: /db/sequence_typing/listeria/species_confirmation
  typing_amr:
    path: /db/sequence_typing/listeria/antibiotic_resistance
  typing_virulence:
    path: /db/sequence_typing/listeria/virulence
