############################################################################################
# This YAML file contains the additional configuration data for the Mycobacterium pipeline #
# The values are added to the configuration data constructed by the BasePipeline class.    #
############################################################################################
####################
# Pipeline options #
####################
citations:
  main: Bogaerts_2021-mycobacterium_validation
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Li_2011-bcftools
    - Kaas_2014-csi_phylogeny
    - Ezewudo_2018-reseqtb_uvp
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Xia_2016-spotyping
    - Lipworth_2019-snpit
    - Coll_2014-myco_snp_lineage
    - Dai_2011-myco_hsp65
    - Srilohasin_2014-myco_51snp
    - Zankari_2017-pointfinder
    - Danecek_2017-bcftools_csq
    - Miotto_2017-myco_amr
    - Jolley_2010-bigsdb

################
# Tool options #
################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 4_411_532

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Mycobacterium tuberculosis

quality_checks:
  typing_scheme: {qc_typing_scheme}
  expected_gc_content: 65.6
  coverage_mode: ref
  skipped:
    - map_rate_assembly_illumina
    - cov_assembly_illumina
  forced:
    - map_rate_ref_illumina
    - cov_ref_illumina

confindr:
  db: /db/confindr/0.8.1

quast:
  ref:
    fasta: /db/refgenomes/Mycobacterium_tuberculosis/H37Rv.fasta
    gff3: /db/refgenomes/Mycobacterium_tuberculosis/H37Rv.gff

variant_calling:
  ploidy: 1
  report_include_bam: {export_bam}
  reference:
    path: /db/refgenomes/Mycobacterium_tuberculosis/H37Rv.fasta
    name: H37Rv
    url: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000195955.2
    annotation_gff: /db/refgenomes/Mycobacterium_tuberculosis/H37Rv.gff
    annotation_tab: /db/refgenomes/Mycobacterium_tuberculosis/H37Rv.tab.ann.gz

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

variant_filtering:
  region:
    bed_file: /db/pipelines/mycobacterium/variant_filtering/excluded_regions.bed
  depth:
    min_fwd_depth: 1
    min_rev_depth: 1
  distance:
    min_distance: 0

snp_lineage:
  bed: /db/pipelines/mycobacterium/snp_lineage/tbdb-2024_02_23.bed

amr:
  bed_regions: /db/pipelines/mycobacterium/amr/who_2023.6/amr_regions.bed
  mutation_db: /db/pipelines/mycobacterium/amr/who_2023.6

sequence_typing:
  mlst:
    path: /db/sequence_typing/mycobacterium/mlst
  cgmlst:
    path: /db/sequence_typing/mycobacterium/cgmlst
    detection_method: blast
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info

51snp:
  bed: /db/pipelines/mycobacterium/51snp/51snp_locations.bed
  profiles: /db/pipelines/mycobacterium/51snp/profiles.tsv

gene_detection:
  amr_cds:
    path: /db/pipelines/mycobacterium/amr/gene_detection/myco_amr_cds
    force_detection_method: kma
    params:
      min_coverage: 20
    metadata:
      name: Antibiotics
      key: antibiotics

  csb_rd:
    path: /db/pipelines/mycobacterium/csb_rd
    force_detection_method: srst2

  ncbi_16s:
    path: /db/gene_detection/NCBI_16S
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 90
    filtering_method: score
    force_detection_method: blast
    metadata:
      name: Species
      key: species

  hsp65:
    path: /db/pipelines/mycobacterium/hsp65
    metadata:
      name: Species
      key: species_name

pointfinder:
  db: mycobacterium_tuberculosis
