import logging
import re

from app.components.blast.blasthitparser import BlastHitParser
from app.components.blasttyping.blasthitfiltering import BlastHitFiltering
from app.components.sequencetyping.blasthit import BlastHit
from app.error.invalidinputspecificationerror import InvalidInputSpecificationError
from app.io.tooliovalue import ToolIOValue
from app.tools.tool import Tool


class BestHitSelector(Tool):
    """
    This tool selects the best hit from a tabular blast output.
    The blast output needs to be generated with the following outfmt option:


    Input:
        TSV: Tabular file generated by Blastn with the following outfmt option: '7 pident sseqid sseq slen qseqid qstart
             qend'
    Output:
        VAL_Hit: The best hit.
    """

    def __init__(self, camel):
        """
        Initializes this tool.
        :param camel: Camel instance
        """
        super().__init__('Typing: Best Hit Selector', '0.1', camel)

    def _check_input(self):
        """
        Checks if the provided input is valid.
        :return: None
        """
        if 'TSV' not in self._tool_inputs:
            raise InvalidInputSpecificationError("TSV input is required")
        if len(self._tool_inputs['TSV']) != 1:
            raise InvalidInputSpecificationError("Only 1 TSV input can be processed")
        super()._check_input()

    def _execute_tool(self):
        """
        Executes this tool.
        :return: None
        """
        metadata = self._input_informs['locus']
        hits = self.__parse_blast_output(metadata)
        hits = BlastHitFiltering.filter_percent_identity(hits, float(self._parameters['min_percent_identity'].value))
        hits = BlastHitFiltering.filter_coverage(hits, float(self._parameters['min_percent_covered'].value))
        detected_allele = self.__get_detected_allele(hits, metadata)
        detected_allele.locus = metadata.get('name')
        self._tool_outputs['VAL_Hit'] = [ToolIOValue(detected_allele)]

    def __parse_blast_output(self, metadata):
        """
        Parses the output generated by blast.
        :return: Blast hits
        """
        blast_output_data = BlastHitParser.parse_output_file(self._tool_inputs['TSV'][0].path)
        hits = [BlastHit.create_from_dict(output_dict, metadata.get('type')) for output_dict in blast_output_data]
        logging.info("{} hits parsed".format(len(hits)))
        return hits

    def __get_detected_allele(self, hits, metadata):
        """
        Returns the detected allele.
        :param hits: Input hits
        :param metadata: Locus metadata
        :return: Detected allele
        """
        if len(hits) == 0:
            logging.info("No hit passed filtering")
            detected_allele = BlastHit.generate_empty_hit(metadata.get('name'), self._input_informs['locus']['type'])
        else:
            detected_allele = self.__select_best_hit(hits, metadata.get('name'), metadata.get('type'))
        if detected_allele.allele_id not in ('?', '-'):
            detected_allele.allele_id = self.__get_allele_id(
                detected_allele.subject, self._input_informs['locus']['allele_id_regex'])
        return detected_allele

    @staticmethod
    def __select_best_hit(hits, locus_name, locus_type):
        """
        Selects the best allele from a set of hits.
        :param hits: Hits
        :param locus_name: Name of the locus
        :param locus_type: Type of locus
        :return: Best hit(s)
        """
        best_hits = BlastHitFiltering.detect_best_hits(hits)
        if len(best_hits) == 1:
            return best_hits[0]
        elif len(best_hits) > 1:
            return BlastHit.generate_multi_hit(locus_name, locus_type)
        else:
            return BlastHit.generate_empty_hit(locus_name, locus_type)

    def __get_allele_id(self, full_allele_name, regex):
        """
        Returns the allele identifier.
        :param full_allele_name: Full name of the allele
        :param regex: Regular expression of the allele id
        :return: Allele identifier
        """
        if regex is None:
            regex = self._parameters['default_allele_id_regex'].value
        m = re.findall(BestHitSelector.__cleanup_regex(regex), full_allele_name)
        if not len(m) == 1:
            raise ValueError("Cannot determine allele identifier for '{}' (RE: {})".format(full_allele_name, regex))
        return m[0]

    @staticmethod
    def __cleanup_regex(regex):
        """
        Cleans a regular expression, PubMLST regexps have to be adapted to be used.
        :param regex: Regular expression
        :return: Cleaned up regular expression
        """
        characters_to_replace = [('^', ''), ('(', '['), (')', ']')]
        cleaned_regex = regex
        for char, repl in characters_to_replace:
            cleaned_regex = cleaned_regex.replace(char, repl)
        return cleaned_regex
