####################
# Pipeline options #
####################
citations:
  main: Bogaerts_2021-shigella
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Li_2011-bcftools
    - Kaas_2014-csi_phylogeny
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Gupta_2014-argannot
    - McArthur_2013-card
    - Zankari_2012-resfinder
    - Feldgarden_2019-ndaro
    - Zankari_2017-pointfinder
    - Joensen_2014-virulencefinder
    - Joensen_2015-serotypefinder
    - Carattoli_2020-plasmidfinder
    - Jaureguy_2008-pasteur
    - Zhou_2020-enterobase
    - Jolley_2010-bigsdb


#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 4_762_774

read_trimming:
  export_fastq: {export_fastq}

contamination_check:
  db: /db/kraken2_full/latest/full
  expected_species: Escherichia coli

quality_checks:
  expected_gc_content: 50.5

variant_calling:
  ploidy: 1
  eport_bam: {export_bam}
  reference:
    path: /db/refgenomes/Escherichia_coli/NC_002695.2.fasta
    name: <i>Escherichia coli</i> O157:H7 (NC_002695.2)
    url: https://www.ncbi.nlm.nih.gov/nuccore/NC_002695.2

variant_filtering: {variant_filtering}

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

##################
# Identification #
##################
subspecies_identification:
  bed_speG: /db/pipelines/shigella/speG/speG.bed
  threshold_speG_depth: 10

flexneri_type:
  fasta_gtr_promotor: /db/pipelines/shigella/flexneri_gtr_promotor/promotor.fasta
  fasta_separate: /db/pipelines/shigella/flexneri_type_separate/
  fasta_combined: /db/pipelines/shigella/flexneri_type/
  tsv_profiles: /db/pipelines/shigella/flexneri_type_profiles/serotype_profiles.tsv

############################
# Gene detection databases #
############################
gene_detection:
  argannot:
    path: /db/gene_detection/ARG-ANNOT

  resfinder:
    path: /db/gene_detection/ResFinder
    metadata:
      name: Antibiotic(s)
      key: antibiotics

  card:
    path: /db/gene_detection/CARD

  ncbi_amr:
    path: /db/gene_detection/NCBI_AMR
    metadata:
      name: Antibiotic(s)
      key: subclass

  virulencefinder:
    path: /db/gene_detection/VirulenceFinder-Ecoli
    metadata:
      name: Protein function
      key: protein_function

  virulencefinder_shiga:
    path: /db/gene_detection/VirulenceFinder-Shiga
    metadata:
      name: stx variant
      key: stx_variant

  plasmidfinder:
    path: /db/gene_detection/PlasmidFinder-entero
    params:
      blastn:
        min_percent_identity: 95
        min_coverage: 60
      srst2:
        max_divergence: 5
        min_coverage: 60

  subspecies_identification:
    path: /db/pipelines/shigella/subspecies_identification/
    force_detection_method: srst2

  flexneri_type:
    path: /db/pipelines/shigella/flexneri_type

###################
# Sequence typing #
###################
sequence_typing:
  mlst_pasteur:
    path: /db/sequence_typing/ecoli/mlst-pasteur
  mlst_warwick:
    path: /db/sequence_typing/ecoli/mlst-warwick
  cgmlst:
    path: /db/sequence_typing/ecoli/cgmlst
    detection_method: blast
    blast_task: blastn
