####################
# Pipeline options #
####################
citations:
  main: Bogaerts_2021-shigella
  other:
    - Bolger_2014-trimmomatic
    - Bankevich_2012-spades
    - Gurevich_2013-quast
    - Wood_2019-kraken2
    - Low_2019-confindr
    - Manni_2021-busco
    - Langmead_2012-bowtie2
    - Li_2009-samtools
    - Li_2011-bcftools
    - Kaas_2014-csi_phylogeny
    - Camacho_2009-blast
    - Clausen_2018-kma
    - Inouye_2014-srst2
    - Feldgarden_2019-ndaro
    - Bortolaia_2020-resfinder_4.0
    - Joensen_2014-virulencefinder
    - Jaureguy_2008-pasteur
    - Zhou_2020-enterobase
    - Jolley_2010-bigsdb
    - Zhang_2021-shigeifinder
    - Wu_2019-shigatyper


#########################
# Tool specific options #
#########################
downsampling:
  coverage_max: {coverage_max}
  expected_genome_size: 4_762_774

read_trimming:
  export_fastq: {export_fastq}

contamination_check:
  db: /db/kraken2_microbial/latest
  expected_species: Shigella
  level_of_depth: G

quast:
  ref:
    fasta: /db/refgenomes/Escherichia_coli/NC_002695.2.fasta
    gff3: /db/refgenomes/Escherichia_coli/NC_002695.2.gff

quality_checks:
  expected_gc_content: 50.5

confindr:
  db: /db/confindr/0.8.1

assembly:
  spades:
    cov_cutoff: 10
  min_contig_length: 1000

############################
# Gene detection databases #
############################
mykrobe:
  db: /db/mykrobe/latest/

amrfinder:
  db: /db/amrfinder/by_version/latest
  species: Escherichia

resfinder4:
  db: /db/resfinder4
  species: Escherichia coli

mob_suite:
  db: /db/mob_suite/latest

gene_detection:
  virulencefinder:
    path: /db/gene_detection/VirulenceFinder-Ecoli
    metadata:
      name: Protein function
      key: protein_function

  virulencefinder_shiga:
    path: /db/gene_detection/VirulenceFinder-Shiga
    metadata:
      name: stx variant
      key: stx_variant

###################
# Sequence typing #
###################
sequence_typing:
  mlst_pasteur:
    path: /db/sequence_typing/ecoli/mlst_pasteur
  mlst_warwick:
    path: /db/sequence_typing/ecoli/mlst_warwick
  cgmlst:
    path: /db/sequence_typing/ecoli/cgmlst
    detection_method: blast
    blast_task: blastn
  rmlst:
    path: /db/sequence_typing/various/rmlst
    message:
      content: rMLST is only available for noncommercial use, see <a href="https://pubmlst.org/species-id">PubMLST</a> for more info.
      category: info
